{
  "hash": "609aecf646f8799e67db33e06ab9a5a2",
  "result": {
    "engine": "knitr",
    "markdown": "# Logistic regression (for binary data)\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\nWhen our response variable is binary, we can use a glm with a **binomial** error distribution\n\nSo far we have only considered continuous and discrete data as response variables. What if our response is a categorical variable (e.g passing or failing an exam, voting yes or no in a referendum, whether an egg has successfully fledged or been predated, infected/uninfected, alive/dead)? \n\nWe can model the **probability** $p$ of being in a particular class as a function of other\nexplanatory variables.\n\nThese type of **binary** data are assumed to follow a **Bernoulli** distribution (which is a special case of *Binomial*) which has the following characteristics:\n\n$$\nY \\sim \\mathcal{Bern}(p)\n$$\n\n* **Binary** variable, taking the values 0 or 1 (yes/no, pass/fail).\n* A **probability** parameter $p$, where $0 < p < 1$.\n* **Mean** = $p$  \n* **Variance** = $p(1 - p)$\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](17-binomial_files/figure-html/bernplot-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\nLet us now place the Gaussian (simple linear regression), Poisson and logistic models next to each other:\n\n$$\n\\begin{aligned}\nY & \\sim \\mathcal{N}(\\mu, \\sigma^2) &&& Y  \\sim \\mathcal{Pois}(\\lambda) &&& Y  \\sim \\mathcal{Bern}(p)\\\\\n\\mu & = \\beta_0 + \\beta_1X &&& \\log{\\lambda} = \\beta_0 + \\beta_1X &&& ?? = \\beta_0 + \\beta_1X\n\\end{aligned}\n$$\n\nNow we need to fill in the `??` with the appropriate term. Similar to the Poisson regression case, \nwe cannot simply model the probabiliy as $p = \\beta_0 + \\beta_1X$, because $p$ **cannot** be negative.\n$\\log{p} = \\beta_0 + \\beta_1X$ won't work either, because $p$ cannot be greater than 1. Instead we \nmodel the **log odds** $\\log\\left(\\frac{p}{1 - p}\\right)$ as a linear function. So our logistic regression model looks\nlike this:\n\n$$\n\\begin{aligned}\nY  & \\sim \\mathcal{Bern}(p)\\\\\n\\log\\left(\\frac{p}{1 - p}\\right) &  = \\beta_0 + \\beta_1 X\n\\end{aligned}\n$$\n\nAgain, note that we are still \"only\" fitting straight lines through our data, but this time in the log odds space.\nAs a shorthand notation we write $\\log\\left(\\frac{p}{1 - p}\\right) = \\text{logit}(p) = \\beta_0 + \\beta_1 X$.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](17-binomial_files/figure-html/unnamed-chunk-4-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\nWe can also re-arrange the above equation so that we get an expression for $p$\n\n$$\np = \\frac{e^{\\beta_0 + \\beta_1 X}}{1 + e^{\\beta_0 + \\beta_1 X}}\n$$\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](17-binomial_files/figure-html/unnamed-chunk-5-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\nNote how $p$ can only vary between 0 and 1. \n\nTo implement the logistic regression model in R, we choose `family=binomial(link=logit)` (the Bernoulli distribution is a special case of the Binomial distribution).\n\n```\nglm(response ~ explanatory, family=binomial(link=logit))\n```\n\n## Example: Challenger Disaster\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/space-shuttle.jpg){fig-align='center' fig-alt='Space shuttle at launch' width=80%}\n:::\n:::\n\n\n[The Challenger Disaster](https://en.wikipedia.org/wiki/Space_Shuttle_Challenger_disaster#O-ring_concerns)\n\nIn 1985, NASA made the decision to send the first civilian into space. \n\nThis decision brought a huge amount of public attention to the STS-51-L mission, which would be Challenger’s 25th trip to space and school teacher Christa McAuliffe’s 1st. On the afternoon of January 28th, 1986 students around America tuned in to watch McAuliffe and six other astronauts launch from Cape Canaveral, Florida. 73 seconds into the flight, the shuttle experienced a critical failure and broke apart in mid air, resulting in the deaths of all seven crewmembers: Christa McAuliffe, Dick Scobee, Judy Resnik, Ellison Onizuka, Ronald McNair, Gregory Jarvis, and Michael Smith.\n\nAfter an investigation into the incident, it was discovered that the failure was caused by an O-ring in the solid rocket booster. Additionally, it was revealed that such an incident was foreseeable.\n\nIn this half of the worksheet we will discuss how the right statistical model could have predicted the critical failure of an O-ring on that day. \n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<a href=\"https://github.com/UEABIO/5023B/blob/dev/files/Challenger.csv\">\n<button class=\"btn btn-success\"><i class=\"fa fa-save\"></i> Download Challenger data as csv</button>\n</a>\n```\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nhead(challenger)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| oring_tot| oring_dt| temp| flight|\n|---------:|--------:|----:|------:|\n|         6|        0|   66|      1|\n|         6|        1|   70|      2|\n|         6|        0|   69|      3|\n|         6|        0|   68|      4|\n|         6|        0|   67|      5|\n|         6|        0|   72|      6|\n\n</div>\n:::\n:::\n\n\nThe data columns are:\n\n- **oring_tot**: Total number of orings on the flight\n\n- **oring_dt** : number of orings that failed during a flight\n\n- **temp**: Outside temperature on the date of the flight\n\n- **flight** order of flights\n\nIt was frequently discussed issue that temperature might play a role in the critical safety of the o-rings on the shuttles.\nOne of the biggest mistakes made in assessing the flight risk for the Challenger was to only look at the flights **where a failure had occurred**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nchallenger %>% \n  filter(oring_dt > 0) %>% \nggplot(aes(y=oring_dt, x=temp))+geom_point()+\n  ggtitle(\"Temperature on flight launches where an O-ring incident occurred\")\n```\n\n::: {.cell-output-display}\n![](17-binomial_files/figure-html/unnamed-chunk-10-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\nFrom this it was concluded that temperature did not appear to affect o-ring risk of failure, as o-ring failures were detected at a range of different temperatures.\n\nHowever when we compare this to the full data that was available a very different picture emerges. \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nchallenger |> \nggplot(aes(y=oring_dt, \n           x=temp))+\n  geom_point()+\n  geom_smooth(method=\"lm\")+\n  ggtitle(\"All launch data\")\n```\n\n::: {.cell-output-display}\n![](17-binomial_files/figure-html/unnamed-chunk-11-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\nWhen we include the flights without incident *and* those with incident, we can see that there is a very clear relationship between temperature and the risk of an o-ring failure. It has been argued that the clear presentation of this data should have allowed even the casual observer to determine the high risk of disaster.\n\nHowever if we want to understand the actual relationship between temperature and risk then there are several issues with fitting a linear model here - once again the data is an integer, and bounded by zero (our model predicts negative failure rates within the observed data range). \n\nWe COULD consider this as suitable for a Poisson model - but if we are really interested in determining the binary risk of **having a flight with o-ring failure vs. no failure**. Then we should implement a GLM with a Binomial distribution.\n\nWe can use dplyr to generate a binary column of no incident '0' and fail '1' for anything >0. \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nchallenger <- challenger |> \n  mutate(oring_int = oring_tot - oring_dt) # create variable containing orings left intact\n```\n:::\n\n\nFitting a binary GLM \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbinary_model <- glm(cbind(oring_dt, oring_int) ~ temp, family = binomial(link = \"logit\"), data = challenger)\n\nbinary_model |> \n  broom::tidy(conf.int=T)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|term        |   estimate| std.error| statistic|   p.value|   conf.low|  conf.high|\n|:-----------|----------:|---------:|---------:|---------:|----------:|----------:|\n|(Intercept) |  8.8169241| 3.6069715|  2.444412| 0.0145089|  1.9549041| 16.4913814|\n|temp        | -0.1794922| 0.0582182| -3.083096| 0.0020486| -0.3073739| -0.0725742|\n\n</div>\n:::\n:::\n\n\nSo we are now fitting the following model\n\n$$\n Y \\sim Bern(p)\n$$\n$$\n\\log\\left[ \\frac { P( \\operatorname{oring\\_binary} = fail) }{ 1 - P( \\operatorname{oring\\_binary} = fail) } \\right] = \\beta_{0} + \\beta_{1}(\\operatorname{temp})\n$$\n\nWhich in R will look like this:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbinary_model <- glm(cbind(oring_dt, oring_int) ~ temp, family=binomial, data=challenger)\n```\n:::\n\n\n- Intercept = $\\beta_{0}$ = 23.77\n\nWhen the temperature is 0&deg;F the mean *log-odds* are 8.82 [95%CI: 1.95-\t16.5] for a failure incident in the O-rings\n\n- Temp = $\\beta_{1}$ = -0.179 [95%CI: -0.307 - -0.0726]\n\nFor every rise in the temperature by 1&deg;F, the *log-odds* of a critical incident fall by 0.179.\n\n### Interpreting model coefficients\n\nWe first consider why we are dealing with odds  $\\frac{p}{1-p}$ instead of just $p$. They contain the same information, so the choice is somewhat arbitrary, however we’ve been using probabilities for so long that it feels unnatural to switch to odds. There are good reasons for this, however. Odds  $\\frac{p}{1-p}$ can take on any value from 0 to ∞ and so part of our translation of $p$ to an unrestricted domain is already done ($P$ is restricted to 0-1). Take a look at some examples below: \n\n+----------------+-------------------------------------------+------------------------+\n|  Probability   |               Odds                        |      Verbiage          |\n+================+===========================================+========================+\n|   $p=.95$      |  $\\frac{95}{5} = \\frac{19}{1} = 19$       |   19 to 1 odds for     |\n+----------------+-------------------------------------------+------------------------+\n|   $p=.75$      |  $\\frac{75}{25} = \\frac{3}{1} = 3$        |   3 to 1 odds for      |\n+----------------+-------------------------------------------+------------------------+\n|   $p=.50$      |  $\\frac{50}{50} = \\frac{1}{1} = 1$        |   1 to 1 odds          |\n+----------------+-------------------------------------------+------------------------+\n|   $p=.25$      |  $\\frac{25}{75} = \\frac{1}{3} = 0.33$     |  3 to 1 odds against   |\n+----------------+-------------------------------------------+------------------------+\n|   $p=.05$      |  $\\frac{95}{5}  = \\frac{1}{19} = 0.0526$  |  19 to 1 odds against  |\n+----------------+-------------------------------------------+------------------------+\n\nWhen we use a binomial model, we produce the 'log-odds', this produces a fully unconstrained linear regression as anything less than 1, can now occupy an infinite negative value -∞ to ∞. \n\n$$\n\\log\\left(\\frac{p}{1-p}\\right)\t=\t\\beta_{0}+\\beta_{1}x_{1}+\\beta_{2}x_{2}\n$$\n\n$$\n\\frac{p}{1-p}\t=\te^{\\beta_{0}}e^{\\beta_{1}x_{1}}e^{\\beta_{2}x_{2}}\n$$\n\n\nWe can interpret $\\beta_{1}$ and $\\beta_{2}$ as the increase in the log odds for every unit increase in $x_{1}$ and $x_{2}$. We could alternatively interpret $\\beta_{1}$ and $\\beta_{2}$ using the notion that a one unit change in $x_{1}$ as a percent change of $e^{\\beta_{1}}$ in the odds. That is to say, $e^{\\beta_{1}}$ is the odds ratio of that change. \n\nIf you want to find out more about [Odds and log-odds head here](https://www.youtube.com/watch?v=8nm0G-1uJzA)\n\n\n## Probability\n\n\n### Making predictions\n\n\nIf we use the `emmeans()` function it will convert *log-odds* to estimate the probability of o-ring failure at the mean value of x (temperature). And add confidence intervals! \n\n\n\n\n:::{.task}\n::::{.task-header}\nA powerful use of logisitic regression is prediction. Can we predict the probability of an event occuring using our data? \n::::\n::::{.task-container}\n\n- Use emmeans to calculate the log-odds of O-ring failure?\n\n- Specify the type argument to get the \"probability\" of o-ring failure\n\n::::\n:::\n\n\n\n<div class='webex-solution'><button>Solution</button>\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nemmeans::emmeans(binary_model, specs=~temp, \n                 type=\"response\") # set type = \"response to get calculated probabilities\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n temp   prob     SE  df asymp.LCL asymp.UCL\n 69.6 0.0249 0.0151 Inf   0.00745    0.0797\n\nConfidence level used: 0.95 \nIntervals are back-transformed from the logit scale \n```\n\n\n:::\n:::\n\n\n\n</div>\n\n\n### Odds and Probability\n\nBut how do log-odds and probability actually relate?\n\n\nThis is the equation to work out probability using the **exponent** of the linear regression equation:\n\n$$\nP(\\operatorname{risk of failure at }  X=69.6)\\left[ \\frac{e^{8.81+(-0.18 \\times 69.6)}}{1+e^{8.81+(-0.18 \\times 69.6)}} \\right]\n$$\n\nWhich produces the following result and we can confirm the risk of an o-ring failure on an *average* day is 0.025\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nodds_at_69.6 <- exp(coef(binary_model)[1]+coef(binary_model)[2]*69.6)\n# To convert from odds to a probability, divide the odds by one plus the odds\n\nprobability <-  odds_at_69.6/(1+odds_at_69.6)\nprobability\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept) \n 0.02470508 \n```\n\n\n:::\n:::\n\n\n### Changes in probability\n\nA useful *rule-of-thumb* can be the **divide-by-four** rule.\n\nThis can be described as the **maximum** difference in probability for a unit change in $X$ is $\\beta/4$.\n\nIn our example the **maximum difference** in probability from a one degree change in Temp is $-0.18/4 = -0.045$\n\nSo the **maximum difference** in probability of failure corresponding to a one degree change is 4.5%\n\n\n### Emmeans \n\nAlternatively we can also do this calculation via emmeans\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nemmeans::emmeans(binary_model, \n                 specs = ~ temp, \n                 at=list(temp=c(66:27)), \n                 type='response') \n```\n:::\n\n\n\n:::{.task}\n::::{.task-header}\nMake a ggplot of the change in probability of Oring failure against temperature\n::::\n::::{.task-container}\n\n- Use emmeans to calculate the probability of failure at different temperatures?\n\n- Add this to a ggplot\n\n- Include 95% confidence intervals\n\n::::\n:::\n\n\n\n<div class='webex-solution'><button>Solution</button>\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nemmeans::emmeans(binary_model, \n                 specs = ~ temp, \n                 at=list(temp=c(27:80)), \n                 type='response') %>% \n  as_tibble() %>% \n  ggplot(aes(x=temp, y=prob))+\n  geom_line(aes(x=temp, y=prob))+\n  geom_ribbon(aes(ymin=asymp.LCL, \n                  ymax=asymp.UCL), alpha=0.2)\n```\n:::\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](17-binomial_files/figure-html/unnamed-chunk-19-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n</div>\n\n\n## Challenger launch\n\nOn the day the Challenger launched the outside air temperature was 36&deg;F\n\nWe can use our model to make predictions about the risk of o-ring failure\n\n\n### More predictions\n\n:::{.task}\n::::{.task-header}\nMake a specific prediction about the probability of o-ring failure on the day of the Challenger launch\n::::\n::::{.task-container}\n\n- Use emmeans to calculate the probability of failure at this specific temperature?\n\n\n::::\n:::\n\n\n<div class='webex-solution'><button>Solution</button>\n\n\n\nFirst - we make a new dataset with the temperature on the day of the Challenger Launch **36&deg;F**\n  \n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n emmeans::emmeans(binary_model, \n                 specs = ~ temp, \n                 at = list(temp = 36),                  \n                 type='response')\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n temp  prob    SE  df asymp.LCL asymp.UCL\n   36 0.913 0.122 Inf     0.338     0.995\n\nConfidence level used: 0.95 \nIntervals are back-transformed from the logit scale \n```\n\n\n:::\n:::\n\n\nWe can see from our fitted model, an O-ring failure on the day of the Challenger launch could have been predicted with a probability of \n\n> 0.91 [91.3%CI: 0.34-99.5]\n\n\n</div>\n\n\n\n## Assumptions\n\nThe `performance` package detects and alters the checks. Pay particular attention to the binned residuals plot - this is your best estimate of possible overdispersion (requiring a quasi-likelihood fit). In this case there is likely not enough data for robust checks - we could consider a quasi-likelihood model in order to have more conservative confidence intervals. \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nperformance::check_model(binary_model,\n                         residual_type = \"normal\",\n                         detrend = FALSE)\n```\n\n::: {.cell-output-display}\n![](17-binomial_files/figure-html/unnamed-chunk-21-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n:::{.task}\n::::{.task-header}\nTry fitting a quasi-likelihood model\n::::\n::::{.task-container}\n\n- Fit a quasibinomial model\n\n- How does this change the means, standard errors and significance tests\n\n::::\n:::\n\n\n\n<div class='webex-solution'><button>Solution</button>\n\n\n- Estimates from the model will not change\n\n- Standard errors will be widened by a fixed dispersion parameter (> 1)\n\n- This may increase p-values, but here there is no change in interpretation\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nquasibinary_model <- glm(cbind(oring_dt, oring_int) ~ temp, \n                    family=quasibinomial, # quasilikelihood\n                    data=challenger)\n\nsummary(quasibinary_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = cbind(oring_dt, oring_int) ~ temp, family = quasibinomial, \n    data = challenger)\n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)   \n(Intercept)  8.81692    2.93149   3.008  0.00670 **\ntemp        -0.17949    0.04732  -3.794  0.00106 **\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for quasibinomial family taken to be 0.6605263)\n\n    Null deviance: 20.706  on 22  degrees of freedom\nResidual deviance:  9.527  on 21  degrees of freedom\nAIC: NA\n\nNumber of Fisher Scoring iterations: 6\n```\n\n\n:::\n:::\n\n\n\n</div>\n\n\n\n## Write-ups\n\n:::{.task}\n::::{.task-header}\nWrite up the results\n::::\n::::{.task-container}\n\n- How would you write up for findings from this analysis?\n\n::::\n:::\n\n\n\n\n<div class='webex-solution'><button>Write-up</button>\n\n\nAnalysis: I used a Binomial logit-link Generalized Linear Model to analyse the effect of temperature on the likelihood of O-ring failure.\n\nAll analyses were carried out in R (ver 4.1.3) (R Core Team 2021) with the following packages;  tidyverse (Wickham et al 2019).\n\nResults: I found a significant negative relationship between temperature and probability of o-ring failure (logit-odds = -0.17 [95%CI: -0.31 - -0.07], *z* = -3.1, df = 21, *P* = 0.002). At an average temperature of 69.6&deg;F the probability of o-ring failure was estimated at 0.025[0.007-0.08], but this rose to 0.91[0.34-1] at 36&deg;F.\n\n> Note you could use anova( test = \"Chisq\") here, but as there is only one, continuous variable, we can also report directly from the summary table. \n\n\n</div>\n\n\n\n## Final checklist\n\n* Think carefully about the hypotheses to test, use your scientific knowledge and background reading to support this\n\n* Import, clean and understand your dataset: use data visuals to investigate trends and determine if there is clear support for your hypotheses\n\n* **Decide on the appropriate error structure for your model (Gaussian = continuous, Poisson = count, Binomial = binary)**\n\n* **Start with canonical link functions, but these can be altered if needed**\n\n* Fit a (generalized) linear model, including interaction terms with caution\n\n* Investigate the fit of your model, understand that parameters may never be perfect, but that classic patterns in residuals may indicate a poorly fitting model - sometimes this can be fixed with careful consideration of missing variables or through data transformation\n\n* **Check for overdispersion in models where variance is not estimated independently of the mean (Poisson and Binomial) - may have to use quasi-likelihood fitting** \n\n* Test the removal of any interaction terms from a model, look at AIC and significance tests (Remember test = \"F\" for Gaussian and Quasilikelihood models, \"Chisq\" for Poisson and Binomial models)\n\n* Make sure you understand the output of a model summary, sense check this against the graphs you have made - Do estimates need converting back to the original response scale?\n\n* The direction and size of any effects are the priority - produce estimates and uncertainties. Make sure the observations are clear.\n\n* Write-up your significance test results, taking care to report not just significance (and all required parts of a significance test). Do you know *what* to report? Within a complex model - reporting *t/z* will indicate the slope of the line for that single term against the intercept, *F/Chi* is the overall effect of a predictor across all levels, *post-hoc* if you wish to compare across all levels. \n\n* Well described tables and figures can enhance your results sections - take the time to make sure these are informative and attractive. \n\n",
    "supporting": [
      "17-binomial_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"site_libs/font-awesome-5.13.0/js/script.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}