{
  "hash": "f6921f5b878c9ca8f7aa8ec265db294c",
  "result": {
    "engine": "knitr",
    "markdown": "# Complex models\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Required packages\nlibrary(here)\nlibrary(tidyverse)\nlibrary(GGally)\nlibrary(skimr)\nlibrary(colorspace)\nlibrary(ggridges)\nlibrary(performance)\nlibrary(patchwork)\n```\n:::\n\n\n\nIn the previous chapter @sec-causal we worked through the process of including/excluding variables based on our **causal** hypotheses.\nHowever, we did not consider the potential role of *complex interactions* and in this chapter we will work through potential complexity in *non-factorial* experimental designs.\n\n## Experimental Design\n\nIn order to make clear hypothesis statements, and then test these - we need to have a good understanding of the experimental design\n\n:::{.task}\n::::{.task-header}\nYour turn\n::::\n::::{.task-container}\n\nWrite some quick code to understand the distribution of treatment types and partner numbers across the experimental design. \n\nIs the experiment a full <a class='glossary'>factorial<span class='def'>Every possible combination of levels for multiple factors is present, providing a complete understanding of individual factor effects and their interactions</span></a> design?\n\n\n<div class='webex-solution'><button>Solution</button>\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndros_clean |> \n  group_by(partners, type) |> \n  summarise(n = n())\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| partners|type        |  n|\n|--------:|:-----------|--:|\n|        0|Control     | 25|\n|        1|Inseminated | 25|\n|        1|Virgin      | 25|\n|        8|Inseminated | 25|\n|        8|Virgin      | 25|\n\n</div>\n:::\n:::\n\n\n\n</div>\n\n\nThe experimental design is <select class='webex-select'><option value='blank'></option><option value=''>factorial</option><option value='answer'>non-factorial</option></select>\n\n\n<div class='webex-solution'><button>Explanation</button>\n\n\nNot all type x partner combinations exist:\n\n- Partners = 0 exists only for Control\n\n- Partners = 1,8 exist only for Virgin and Inseminated\n\n> This doesn't affect our initial consideration of model structure, but we will revisit this later\n\n\n</div>\n\n\n::::\n:::\n\n\n## Complex model interactions\n\nSometimes, the relationship between a covariate and the outcome *differs between groups*.\n\nWe have previously investigated models to examine the causal effect of mating types on male longevity - with five experimental groups\n\n- Control: Unmated flies (0 partners)\n\n- Virgin - 1 partner: Males paired with a single unmated female \n\n- Virgin - 8 partners: Males paired with multiple unmated females\n\n- Inseminated - 1 partner: Males paired with a single previously mated female \n\n- Inseminated - 8 partners: Males paired with multiple mated females\n\n> We now wish to consider some key questions in our experiment around interactions. \n\n1. Does the number of females a male is paired with change the effect mating type has on male longevity?\n\n2. Does the size of a male change the effect of mating type on male longevity?\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| partners|type        |  n|\n|--------:|:-----------|--:|\n|        0|Control     | 25|\n|        1|Inseminated | 25|\n|        1|Virgin      | 25|\n|        8|Inseminated | 25|\n|        8|Virgin      | 25|\n\n</div>\n:::\n:::\n\n\n**This is a non-factorial design** - not all type × partner combinations exist. Control flies only appear at 0 partners, while Virgin and Inseminated flies only appear at 1 or 8 partners.\n\n\nLet's start by fitting an interaction term with what seems like the obvious model:\n\n$$\n\\text{longevity}_i = \\beta_0 + \\beta_1 \\, \\text{type}_i + \\beta_2 \\, \\text{thorax}_i + \\beta_3 \\, \\text{partners}_i + \\beta_4 \\, (\\text{type}_i \\times \\text{thorax}_i) + \\beta_5 \\, (\\text{type}_i \\times \\text{partners}_i) \\varepsilon_i\n$$\n\n- This allows the **the effect of size on longevity to depend on mating partner**.\n\n- As a second interaction test it allows **the effect of mating partner on longevity to depend on the number of partners**\n\nBefore fitting new models, we should make sure our data is in the appropriate format: \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Use mutate to set type and partners as factorial variables\ndros_clean2 <- dros_clean |> \n  mutate(type = factor(type),\n         partners = factor(partners))\n```\n:::\n\n\n**Question 1.** Why is it important for partners to be treated as a factor (rather than numeric)?\n\n\n<div class='webex-solution'><button>Solution</button>\n\n\nPartners is a numeric column - but this does not make sense with our experimental design, there are only three treatments with respect to number of partners, 0,1 or 8. \nIf we leave partners as a numeric in our model, R will attempt to fit a single slope to explain the variance explained by partners as though it is a continuous variable.\nWe have no reason to think the effect of partners is strictly linear, and with only three different observations it makes much more sense to treat this as categorical. \n\n\n</div>\n\n\n:::{.task}\n::::{.task-header}\nYour turn\n::::\n::::{.task-container}\n\nWrite a linear model that includes type, thorax and partners as main effects and include expressions to include an interaction effect between type:thorax and type:partners.\n\n\n<div class='webex-solution'><button>Solution</button>\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nflyls2 <- lm(longevity ~ type + \n               thorax + \n               partners +\n               type:thorax + # specifies the interaction effect\n               type:partners, # specifies the interaction effect\n             data = dros_clean2)\n```\n:::\n\n\n\n</div>\n\n\n\n::::\n:::\n\n\n## Issues with interpreting the fitted model\n\nLet's take a look at the fitted model now we have included our interaction terms:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(flyls2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = longevity ~ type + thorax + partners + type:thorax + \n    type:partners, data = dros_clean2)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-26.4634  -6.5711  -0.9363   6.8499  30.1715 \n\nCoefficients: (4 not defined because of singularities)\n                          Estimate Std. Error t value Pr(>|t|)    \n(Intercept)               -50.2420    21.5582  -2.331  0.02149 *  \ntypeInseminated             0.1163    27.0616   0.004  0.99658    \ntypeVirgin                -15.3390    27.1769  -0.564  0.57355    \nthorax                    136.1268    25.6625   5.304 5.42e-07 ***\npartners1                  13.1379     3.0940   4.246 4.38e-05 ***\npartners8                       NA         NA      NA       NA    \ntypeInseminated:thorax      4.7442    32.6180   0.145  0.88461    \ntypeVirgin:thorax          -5.7505    32.8543  -0.175  0.86136    \ntypeInseminated:partners1 -14.5153     4.3258  -3.356  0.00107 ** \ntypeVirgin:partners1            NA         NA      NA       NA    \ntypeInseminated:partners8       NA         NA      NA       NA    \ntypeVirgin:partners8            NA         NA      NA       NA    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 10.59 on 117 degrees of freedom\nMultiple R-squared:  0.6568,\tAdjusted R-squared:  0.6362 \nF-statistic: 31.98 on 7 and 117 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nThe intercept is Control at partners=0 (the reference levels for both factors). But look at what the other parameters mean:\n\n- typeInseminated = -0.116: Difference between Inseminated and Control at partners=0\n\n> Problem: Inseminated flies don't exist at partners=0! This is meaningless.\n\n- partners1 = 13.14: Effect of having 1 partner for Control flies\n\n> Problem: Control flies don't exist at partners=1! This is also meaningless.\n\nMany NA values: R can't estimate these parameters because the combinations don't exist\n\n:::{callout-note}\n\nWhile the model is technically functional - interpretation and coefficients are suboptimal. The Control level only exists at partners = 0, this creates a fundamental mismatch when trying to estimate values\n\n:::\n\n\n:::{.task}\n::::{.task-header}\nYour turn\n::::\n::::{.task-container}\n\nWe need to revisit our key hypotheses and fix our model accordingly. \n\nCan you write out specific testable questions we might have about interaction effects in our data?\n\n\n<div class='webex-solution'><button>Solution</button>\n\n\n- Question 1: Within Virgin flies, does having 1 vs 8 partners affect longevity?\n\n- Question 2: Within Inseminated flies, does having 1 vs 8 partners affect longevity?\n\n- Question 3: At the same partner level, do Inseminated and Virgin flies differ in longevity?\n\n- Question 4: How do our mated treatments compare to unmated Controls?\n\n- Question 5: At the same body size, do Inseminated and Virgin flies differ in longevity?\n\n> With these questions in place we can \"relevel\" our factors to set the intercept to a different value - allowing for better comparisons\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# By setting Virgin and partners = 1 as the first level in the factors for type and partners this will become the new intercept\n\ndros_clean3 <- dros_clean2 |> \n  mutate(type = fct_relevel(type, \"Virgin\"),\n         partners = fct_relevel(partners, \"1\"))\n\n# Refit the model\n\nflyls3 <- lm(longevity ~ type + \n               thorax + \n               partners +\n               type:thorax + # specifies the interaction effect\n               type:partners, # specifies the interaction effect\n             data = dros_clean3)\n\nsummary(flyls3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = longevity ~ type + thorax + partners + type:thorax + \n    type:partners, data = dros_clean3)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-26.4634  -6.5711  -0.9363   6.8499  30.1715 \n\nCoefficients: (4 not defined because of singularities)\n                          Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                -52.443     17.313  -3.029  0.00302 ** \ntypeControl                  2.201     27.649   0.080  0.93668    \ntypeInseminated              0.940     24.094   0.039  0.96895    \nthorax                     130.376     20.514   6.355 4.15e-09 ***\npartners0                       NA         NA      NA       NA    \npartners8                  -13.138      3.094  -4.246 4.38e-05 ***\ntypeControl:thorax           5.750     32.854   0.175  0.86136    \ntypeInseminated:thorax      10.495     28.744   0.365  0.71569    \ntypeControl:partners0           NA         NA      NA       NA    \ntypeInseminated:partners0       NA         NA      NA       NA    \ntypeControl:partners8           NA         NA      NA       NA    \ntypeInseminated:partners8   14.515      4.326   3.356  0.00107 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 10.59 on 117 degrees of freedom\nMultiple R-squared:  0.6568,\tAdjusted R-squared:  0.6362 \nF-statistic: 31.98 on 7 and 117 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nThe intercept is Virgin at partners=1 (the reference levels for both factors). \n\n- typeControl = 2.2 Difference between Virgin and Control (note control only has 0 partners)\n\n- typeInseminated = 0.940 Difference between Inseminated and Virgin at partners=1\n\n> Correct: Both treatments have examples of 1 partner.\n\n- partners8 = -13.14 Difference between Virgin flies with 8 partners compare to 1\n\n> Correct\n\n- Inseminated:partners8 = 14.515 Adjustment needed for estimating the effect of partners in Inseminated flies\n\n> Correct: Total difference in partners8 between Inseminated1 and Inseminated8 = -13.1 + 14.5 = 1.4\n> Total difference in partners8 between Virgin8 and Inseminated8 = 0.9 + 13.1 + 14.5 = 28.5\n\nNA values: R can't estimate these parameters because the combinations don't exist\n\n\n</div>\n\n\n::::\n:::\n\n\n## Determining a minimally sufficient model\n\n- A significant interaction means the relationship between body size and longevity, and parners and longevity is **not the same** across partner types.\n\nR compares the nested models via a likelihood ratio test (LRT):\n\n\n- H₀: β₃ = 0 (no interaction; same slope for all partner types)\n\n- H₁: β₃ ≠ 0 (interaction; slopes differ)\n\nIf the p-value is small (typically < 0.05), the more complex model explains significantly more variation — implying the interaction is meaningful.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndrop1(flyls3, test = \"F\")\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|              | Df|  Sum of Sq|      RSS|      AIC|    F value|    Pr(>F)|\n|:-------------|--:|----------:|--------:|--------:|----------:|---------:|\n|<none>        | NA|         NA| 13129.69| 597.7897|         NA|        NA|\n|type:thorax   |  2|   14.98103| 13144.67| 593.9322|  0.0667487| 0.9354658|\n|type:partners |  1| 1263.55212| 14393.24| 607.2750| 11.2596451| 0.0010686|\n\n</div>\n:::\n:::\n\n\n\n<div class='webex-solution'><button>Explanation</button>\n\n\nThe `drop1` function produces a series of LRT where a term is removed from the model and the difference in variance is compared to the maximal model with an F-test.\nA significant result indicates a statisticall significant reduction in variance explained.\n\n> What does this mean?: We can safely remove terms that are non-significant as not helping explain variance in our data.\n\n\n</div>\n\n\n### Refitting to produce the most optimal model\n\nHaving determined that there *is* evidence for an interaction effect between `type:partners` but there *is not* evidence for an interaction between `type:thorax` we can refit our model: \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nflyls4 <- lm(longevity ~ type + \n               thorax + \n               partners +\n               type:partners, # specifies the interaction effect\n             data = dros_clean3)\n\nsummary(flyls4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = longevity ~ type + thorax + partners + type:partners, \n    data = dros_clean3)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-26.189  -6.599  -0.989   6.408  30.244 \n\nCoefficients: (4 not defined because of singularities)\n                          Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                -57.002     10.629  -5.363 4.08e-07 ***\ntypeControl                  7.017      2.973   2.361 0.019874 *  \ntypeInseminated              9.670      2.976   3.249 0.001507 ** \nthorax                     135.819     12.439  10.919  < 2e-16 ***\npartners0                       NA         NA      NA       NA    \npartners8                  -12.933      3.009  -4.298 3.55e-05 ***\ntypeControl:partners0           NA         NA      NA       NA    \ntypeInseminated:partners0       NA         NA      NA       NA    \ntypeControl:partners8           NA         NA      NA       NA    \ntypeInseminated:partners8   14.210      4.210   3.375 0.000996 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 10.51 on 119 degrees of freedom\nMultiple R-squared:  0.6564,\tAdjusted R-squared:  0.6419 \nF-statistic: 45.46 on 5 and 119 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nThis is our best fitting model - and the one we should report\n\n\n## Pairwise comparisons\n\nUsing the [emmeans](https://aosmith.rbind.io/2019/03/25/getting-started-with-emmeans/) package is a very easy way to produce the estimate mean values (rather than mean differences) for different categories `emmeans`. \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmeans <- emmeans::emmeans(flyls4, specs = \n                   ~ type + thorax + partners)\n\nmeans\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n type        thorax partners emmean   SE  df lower.CL upper.CL\n Virgin       0.821 1          54.5 2.11 119     50.3     58.7\n Control      0.821 1        nonEst   NA  NA       NA       NA\n Inseminated  0.821 1          64.2 2.10 119     60.0     68.3\n Virgin       0.821 0        nonEst   NA  NA       NA       NA\n Control      0.821 0          61.5 2.11 119     57.3     65.7\n Inseminated  0.821 0        nonEst   NA  NA       NA       NA\n Virgin       0.821 8          41.6 2.12 119     37.4     45.8\n Control      0.821 8        nonEst   NA  NA       NA       NA\n Inseminated  0.821 8          65.4 2.11 119     61.3     69.6\n\nConfidence level used: 0.95 \n```\n\n\n:::\n:::\n\n\nIf the term `pairs()` is included then it will also include post-hoc pairwise comparisons between all levels with a tukey test (adjustment for multiple comparisons), we can turn off p-value adjustments by including the argument `adjust = \"none\"`.\n\n:::{.panel-tabset}\n\n## Raw comparisons\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npairs(means,\n      adjust = \"none\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast                                                                 \n Virgin thorax0.82096 partners1 - Control thorax0.82096 partners1         \n Virgin thorax0.82096 partners1 - Inseminated thorax0.82096 partners1     \n Virgin thorax0.82096 partners1 - Virgin thorax0.82096 partners0          \n Virgin thorax0.82096 partners1 - Control thorax0.82096 partners0         \n Virgin thorax0.82096 partners1 - Inseminated thorax0.82096 partners0     \n Virgin thorax0.82096 partners1 - Virgin thorax0.82096 partners8          \n Virgin thorax0.82096 partners1 - Control thorax0.82096 partners8         \n Virgin thorax0.82096 partners1 - Inseminated thorax0.82096 partners8     \n Control thorax0.82096 partners1 - Inseminated thorax0.82096 partners1    \n Control thorax0.82096 partners1 - Virgin thorax0.82096 partners0         \n Control thorax0.82096 partners1 - Control thorax0.82096 partners0        \n Control thorax0.82096 partners1 - Inseminated thorax0.82096 partners0    \n Control thorax0.82096 partners1 - Virgin thorax0.82096 partners8         \n Control thorax0.82096 partners1 - Control thorax0.82096 partners8        \n Control thorax0.82096 partners1 - Inseminated thorax0.82096 partners8    \n Inseminated thorax0.82096 partners1 - Virgin thorax0.82096 partners0     \n Inseminated thorax0.82096 partners1 - Control thorax0.82096 partners0    \n Inseminated thorax0.82096 partners1 - Inseminated thorax0.82096 partners0\n Inseminated thorax0.82096 partners1 - Virgin thorax0.82096 partners8     \n Inseminated thorax0.82096 partners1 - Control thorax0.82096 partners8    \n Inseminated thorax0.82096 partners1 - Inseminated thorax0.82096 partners8\n Virgin thorax0.82096 partners0 - Control thorax0.82096 partners0         \n Virgin thorax0.82096 partners0 - Inseminated thorax0.82096 partners0     \n Virgin thorax0.82096 partners0 - Virgin thorax0.82096 partners8          \n Virgin thorax0.82096 partners0 - Control thorax0.82096 partners8         \n Virgin thorax0.82096 partners0 - Inseminated thorax0.82096 partners8     \n Control thorax0.82096 partners0 - Inseminated thorax0.82096 partners0    \n Control thorax0.82096 partners0 - Virgin thorax0.82096 partners8         \n Control thorax0.82096 partners0 - Control thorax0.82096 partners8        \n Control thorax0.82096 partners0 - Inseminated thorax0.82096 partners8    \n Inseminated thorax0.82096 partners0 - Virgin thorax0.82096 partners8     \n Inseminated thorax0.82096 partners0 - Control thorax0.82096 partners8    \n Inseminated thorax0.82096 partners0 - Inseminated thorax0.82096 partners8\n Virgin thorax0.82096 partners8 - Control thorax0.82096 partners8         \n Virgin thorax0.82096 partners8 - Inseminated thorax0.82096 partners8     \n Control thorax0.82096 partners8 - Inseminated thorax0.82096 partners8    \n estimate   SE  df t.ratio p.value\n   nonEst   NA  NA      NA      NA\n    -9.67 2.98 119  -3.249  0.0015\n   nonEst   NA  NA      NA      NA\n    -7.02 2.97 119  -2.361  0.0199\n   nonEst   NA  NA      NA      NA\n    12.93 3.01 119   4.298 <0.0001\n   nonEst   NA  NA      NA      NA\n   -10.95 3.00 119  -3.650  0.0004\n   nonEst   NA  NA      NA      NA\n   nonEst   NA  NA      NA      NA\n   nonEst   NA  NA      NA      NA\n   nonEst   NA  NA      NA      NA\n   nonEst   NA  NA      NA      NA\n   nonEst   NA  NA      NA      NA\n   nonEst   NA  NA      NA      NA\n   nonEst   NA  NA      NA      NA\n     2.65 2.98 119   0.891  0.3745\n   nonEst   NA  NA      NA      NA\n    22.60 2.99 119   7.560 <0.0001\n   nonEst   NA  NA      NA      NA\n    -1.28 2.98 119  -0.428  0.6695\n   nonEst   NA  NA      NA      NA\n   nonEst   NA  NA      NA      NA\n   nonEst   NA  NA      NA      NA\n   nonEst   NA  NA      NA      NA\n   nonEst   NA  NA      NA      NA\n   nonEst   NA  NA      NA      NA\n    19.95 3.01 119   6.636 <0.0001\n   nonEst   NA  NA      NA      NA\n    -3.93 3.00 119  -1.311  0.1923\n   nonEst   NA  NA      NA      NA\n   nonEst   NA  NA      NA      NA\n   nonEst   NA  NA      NA      NA\n   nonEst   NA  NA      NA      NA\n   -23.88 2.97 119  -8.031 <0.0001\n   nonEst   NA  NA      NA      NA\n```\n\n\n:::\n:::\n\n\n## Adjusted comparisons\n\nIn this example a Tukey HSD test adjustment has been applied - the p-values have been adjusted for *a family of 5 estimates* representing the five different experimental groups\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npairs(means)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast                                                                 \n Virgin thorax0.82096 partners1 - Control thorax0.82096 partners1         \n Virgin thorax0.82096 partners1 - Inseminated thorax0.82096 partners1     \n Virgin thorax0.82096 partners1 - Virgin thorax0.82096 partners0          \n Virgin thorax0.82096 partners1 - Control thorax0.82096 partners0         \n Virgin thorax0.82096 partners1 - Inseminated thorax0.82096 partners0     \n Virgin thorax0.82096 partners1 - Virgin thorax0.82096 partners8          \n Virgin thorax0.82096 partners1 - Control thorax0.82096 partners8         \n Virgin thorax0.82096 partners1 - Inseminated thorax0.82096 partners8     \n Control thorax0.82096 partners1 - Inseminated thorax0.82096 partners1    \n Control thorax0.82096 partners1 - Virgin thorax0.82096 partners0         \n Control thorax0.82096 partners1 - Control thorax0.82096 partners0        \n Control thorax0.82096 partners1 - Inseminated thorax0.82096 partners0    \n Control thorax0.82096 partners1 - Virgin thorax0.82096 partners8         \n Control thorax0.82096 partners1 - Control thorax0.82096 partners8        \n Control thorax0.82096 partners1 - Inseminated thorax0.82096 partners8    \n Inseminated thorax0.82096 partners1 - Virgin thorax0.82096 partners0     \n Inseminated thorax0.82096 partners1 - Control thorax0.82096 partners0    \n Inseminated thorax0.82096 partners1 - Inseminated thorax0.82096 partners0\n Inseminated thorax0.82096 partners1 - Virgin thorax0.82096 partners8     \n Inseminated thorax0.82096 partners1 - Control thorax0.82096 partners8    \n Inseminated thorax0.82096 partners1 - Inseminated thorax0.82096 partners8\n Virgin thorax0.82096 partners0 - Control thorax0.82096 partners0         \n Virgin thorax0.82096 partners0 - Inseminated thorax0.82096 partners0     \n Virgin thorax0.82096 partners0 - Virgin thorax0.82096 partners8          \n Virgin thorax0.82096 partners0 - Control thorax0.82096 partners8         \n Virgin thorax0.82096 partners0 - Inseminated thorax0.82096 partners8     \n Control thorax0.82096 partners0 - Inseminated thorax0.82096 partners0    \n Control thorax0.82096 partners0 - Virgin thorax0.82096 partners8         \n Control thorax0.82096 partners0 - Control thorax0.82096 partners8        \n Control thorax0.82096 partners0 - Inseminated thorax0.82096 partners8    \n Inseminated thorax0.82096 partners0 - Virgin thorax0.82096 partners8     \n Inseminated thorax0.82096 partners0 - Control thorax0.82096 partners8    \n Inseminated thorax0.82096 partners0 - Inseminated thorax0.82096 partners8\n Virgin thorax0.82096 partners8 - Control thorax0.82096 partners8         \n Virgin thorax0.82096 partners8 - Inseminated thorax0.82096 partners8     \n Control thorax0.82096 partners8 - Inseminated thorax0.82096 partners8    \n estimate   SE  df t.ratio p.value\n   nonEst   NA  NA      NA      NA\n    -9.67 2.98 119  -3.249  0.0129\n   nonEst   NA  NA      NA      NA\n    -7.02 2.97 119  -2.361  0.1336\n   nonEst   NA  NA      NA      NA\n    12.93 3.01 119   4.298  0.0003\n   nonEst   NA  NA      NA      NA\n   -10.95 3.00 119  -3.650  0.0035\n   nonEst   NA  NA      NA      NA\n   nonEst   NA  NA      NA      NA\n   nonEst   NA  NA      NA      NA\n   nonEst   NA  NA      NA      NA\n   nonEst   NA  NA      NA      NA\n   nonEst   NA  NA      NA      NA\n   nonEst   NA  NA      NA      NA\n   nonEst   NA  NA      NA      NA\n     2.65 2.98 119   0.891  0.8996\n   nonEst   NA  NA      NA      NA\n    22.60 2.99 119   7.560 <0.0001\n   nonEst   NA  NA      NA      NA\n    -1.28 2.98 119  -0.428  0.9929\n   nonEst   NA  NA      NA      NA\n   nonEst   NA  NA      NA      NA\n   nonEst   NA  NA      NA      NA\n   nonEst   NA  NA      NA      NA\n   nonEst   NA  NA      NA      NA\n   nonEst   NA  NA      NA      NA\n    19.95 3.01 119   6.636 <0.0001\n   nonEst   NA  NA      NA      NA\n    -3.93 3.00 119  -1.311  0.6849\n   nonEst   NA  NA      NA      NA\n   nonEst   NA  NA      NA      NA\n   nonEst   NA  NA      NA      NA\n   nonEst   NA  NA      NA      NA\n   -23.88 2.97 119  -8.031 <0.0001\n   nonEst   NA  NA      NA      NA\n\nP value adjustment: tukey method for comparing a family of 5 estimates \n```\n\n\n:::\n:::\n\n\n:::\n\n:::{.callout-note}\n## Should we use raw or adjusted p-values?\n\nIt depends - adjusted p-values are more conservative - and there is a good reason to use these (preventing Type 1 errors) - especially if we didn't have a clear set of initial hypotheses.\nHowever, in this example we have a clear experimental design, and we aren't actually interested in looking at every comparison possible. We are interested in the difference between the three treatment groups and whether partner number changes this. With these careful planned contrasts we should be ok using unadjusted p-values\n\n:::\n\n\n## Visualising models\n\nWe can make visualisations of our models with `ggplot()`. \n\nBecause we have included thorax as a stabilising predictor in our models we have some options on how to present our results: \n\n1) Thorax does not interact with other predictors - as such it is a constant and `emmeans` has set these to the mean value within the dataset, so comparisons are constant between categories at the average value of all continuous variables.\n\n2) If we wish to model continuous predictions we need to specify these by asking for model predictions across the observed range of thorax values\n\n:::{.panel-tabset}\n\n## Type and partner differences across the average for thorax\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmeans |> \n    as_tibble() |> \n    ggplot(aes(x=type, y = emmean, colour = partners, fill = partners))+\n    geom_pointrange(aes(ymin=lower.CL, ymax=upper.CL), position = position_dodge(width =.2))+\n    geom_point(data = dros_clean3, \n               aes(x = type, \n                   y = longevity),\n               show.legend = FALSE, \n               alpha = .2, \n               position = position_dodge(width =.2))+\n  scale_colour_discrete_qualitative() +\n  theme_classic()+ \n  theme(strip.text = element_blank())+\n  facet_wrap(~factor(type, \n                     levels = c(\"Control\", \n                                \"Inseminated\", \n                                \"Virgin\")), \n             scales = \"free_x\")\n```\n\n::: {.cell-output-display}\n![](14a-complex-models_files/figure-html/unnamed-chunk-14-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n## Type and partner differences across the observed range for thorax\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# use the final model to produce model predictions set to the new dataframe\n\n\nemmeans::emmeans(flyls4, \n                 specs = ~ type + thorax + partners,\n                 at = list(thorax = seq(0.64,0.94, .1))) |> \n  as_tibble() |> \n  ggplot(\n       aes(x=thorax, \n           y = emmean, \n           colour = type, \n           fill = type))+\n  geom_ribbon(aes(ymin=lower.CL, \n                  ymax=upper.CL), \n              alpha = 0.2)+\n    geom_line(linetype = \"dashed\", \n              show.legend = FALSE)+\n  geom_point(data = dros_clean, \n             aes(x = thorax, \n                 y = longevity),\n             show.legend = FALSE)+\nscale_fill_discrete_qualitative() +\nscale_colour_discrete_qualitative() +\n  labs(y = \"Lifespan in days\",\n       x = \"Thorax length (mm)\",\n       fill = \"Type of female exposure\")+\n  guides(colour = \"none\")+\n  theme_classic()+\n  theme(legend.position = \"bottom\")+\n    facet_wrap(~factor(partners, \n                       levels = c(0, 1, 8)))\n```\n\n::: {.cell-output-display}\n![](14a-complex-models_files/figure-html/unnamed-chunk-15-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n:::\n\n\n## Model checking\n\nBefore we can interpret the terms in our model, we should check to see if this is even a good way of fitting and measuring our data. We should check the assumptions of our model are being met.\n\nR has ways to do this with the `plot()` function, but the `performance` packages @R-performance from `easystats` also gives nice residual checks:\n\n:::{.panel-tabset}\n\n## base R\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Set plotting area to 2x2 (four panels)\npar(mfrow = c(2, 2))\n\n# Plot diagnostic plots\nplot(flyls4)\n```\n\n::: {.cell-output-display}\n![](14a-complex-models_files/figure-html/unnamed-chunk-16-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n## performance\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nperformance::check_model(flyls4,\n                         detrend = F)\n```\n\n::: {.cell-output-display}\n![](14a-complex-models_files/figure-html/unnamed-chunk-17-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n:::\n\n- Posterior Predictive Check – Assesses whether the model’s predicted values align well with the observed data, indicating good model fit.\n\n- Linearity Check – Ensures that the relationship between predictor variables and the outcome is approximately linear, a key assumption of linear regression.\n\n- Homogeneity of Variance Check – Tests whether residuals (errors) have constant variance across all levels of predictors, known as homoscedasticity.\n\n- Influential Observation Check – Identifies individual data points that have a disproportionately large impact on the model’s estimates.\n\n- Collinearity Check – Detects whether predictor variables are highly correlated with each other, which can distort model estimates and reduce interpretability.\n\n- Normality Check – Examines whether the residuals of the model follow a normal distribution, an assumption necessary for reliable inference in linear regression.\n\n### Homogeneity of variance\n\n**Question - IS the assumption of homogeneity of variance met?** <select class='webex-select'><option value='blank'></option><option value='answer'>Yes</option><option value=''>No</option></select>\n\n\n<div class='webex-solution'><button>Solution</button>\n\n\n* Mostly - the reference line is fairly flat (there is a slight curve).\n\n* It looks as though there might be some increasing heterogeneity with larger values, though very minor.\n\nVERDICT, pretty much ok, should be fine for making inferences. \n\nWith a slight curvature this could indicate that you *might* get a better fit with a transformation, or perhaps that there is a missing variable that if included in the model would improve the residuals. In this instance I wouldn't be overly concerned. See here for a great explainer on intepreting residuals^[https://www.qualtrics.com/support/stats-iq/analyses/regression-guides/interpreting-residual-plots-improve-regression/].\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Runs a Breusch-Pagan Test for heteroscedasticity\n# Sensitive to outliers, non-normality and sample size\nperformance::check_heteroscedasticity(flyls4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWarning: Heteroscedasticity (non-constant error variance) detected (p = 0.007).\n```\n\n\n:::\n:::\n\n\n\n</div>\n\n\n### Normality of residuals\n\n<select class='webex-select'><option value='blank'></option><option value='answer'>Yes</option><option value=''>No</option></select>\n\n\n<div class='webex-solution'><button>Solution</button>\n\n\nYes - the QQplot looks pretty good, a very minor indication of a right skew, but nothing to worry about. \n\n[Interpreting QQ plots][What is a Quantile-Quantile (QQ) plot?]\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Runs a Shapiro Wilk test of normality\n# Sensitive to outliers, sample size\nperformance::check_normality(flyls4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOK: residuals appear as normally distributed (p = 0.680).\n```\n\n\n:::\n:::\n\n\n\n</div>\n\n\n\n### Collinearity\n\n**Question - IS their an issue with Collinearity?** <select class='webex-select'><option value='blank'></option><option value=''>Yes</option><option value='answer'>No</option></select>\n\n:::{.callout-tip}\n\nWhat does it mean to have (multi)collinearity?\n\nThis is when one or more predictors are correlated - leading to increased uncertainty about their contributions to the outcome variable. \n\nThe result is wider standard error and confidence intervals. \n\nWhile there are many discussions about what can be done with multicollinearity - I subscribed to the views outlined [here](https://janhove.github.io/posts/2019-09-11-collinearity/). \n\nIt should be reported - but that's it - it represents genuine uncertainty around the contributions of your predictors. \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncheck_collinearity(flyls4)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|Term          |      VIF| VIF_CI_low| VIF_CI_high| SE_factor| Tolerance| Tolerance_CI_low| Tolerance_CI_high|\n|:-------------|--------:|----------:|-----------:|---------:|---------:|----------------:|-----------------:|\n|type          | 2.407136|   1.916931|    3.159412|  1.245590| 0.4154314|        0.3165146|         0.5216672|\n|thorax        | 1.042019|   1.000713|    3.475709|  1.020793| 0.9596755|        0.2877111|         0.9992873|\n|partners      | 2.459411|   1.954827|    3.230645|  1.252298| 0.4066014|        0.3095357|         0.5115541|\n|type:partners | 3.208678|   2.499097|    4.254132|  1.791278| 0.3116548|        0.2350656|         0.4001445|\n\n</div>\n:::\n:::\n\n\n:::\n\n\n\n\n",
    "supporting": [
      "14a-complex-models_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}