{
  "hash": "d39eacb0155119f13e95a310a34c941b",
  "result": {
    "engine": "knitr",
    "markdown": "# Interactions {#sec-interaction}\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\nSo far we have worked almost exclusively with single explanatory variables either continuous (regression) or categorical (t-test or ANOVA). But what about analyses where we have more than one possible explanatory variable? Extra terms can easily be incorporated into linear models in order to test this. \n\n## Factorial linear models\n\n> The example data is the response of above ground plant biomass production of grassland plots in relation to two resource addition treatments. The addition of Fertiliser to the soil and the addition of Light to the grassland understorey. If biomass is limited by the nutrients in the soil, we would expect the addition of fertiliser to increase production. If biomass is limited by low levels of light caused by plant crowding we would expect an addition of light to increase biomass. \n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<a href=\"https://raw.githubusercontent.com/UEABIO/5027A/refs/heads/dev/files/biomass.csv\">\n<button class=\"btn btn-success\"><i class=\"fa fa-save\"></i> Download biomass data as csv</button>\n</a>\n```\n\n:::\n:::\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbiomass <- read_csv(here(\"data\", \"biomass.csv\"))\n```\n:::\n\n\n\nYou should first check the data and look at the top rows, we can see that this shows the application or non-application of fertiliser and light additions:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nhead(biomass)\n```\n:::\n\n\n\nInspection of the dataset shows that the same data is presented in *two* ways:\n\n* Column **Fert** shows the status of Fertiliser only (F +/-) (two levels)\n\n* Column **Light** shows the status of Light only (L +/-) (two levels)\n\n* Column **FL** shows whether fertiliser **and** light have been applied (four levels, a combination of the previous two columns)\n\n* Column **Biomass.m2** shows the biomass per metre squared of coverage\n\n\nA simple analysis of the dataset will show that we have *all four* possible combinations are present, this is known as a *fully factorial design*:\n\n* control (F- L-, no added light or fertiliser)\n\n* fertiliser (F+ L-)\n\n* light (F- L+)\n\n* addition of both (F+ L+)\n\nThere are <input class='webex-solveme nospaces' size='2' data-answer='[\"16\"]'/> observations for each treatment combination.\n\n:::{.task}\n::::{.task-header}\nRun the code to count the combinations of data levels\n::::\n::::{.task-container}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbiomass |> \n  group_by(Fert, Light) |> \n  summarise(n = n())\n```\n:::\n\n::::\n\n:::\n\n\n\n## Data visualisation\n\nBefore we start any analysis or modelling it is a good idea to visualise our data:\n\n:::{.task}\n::::{.task-header}\nData visualisation\n::::\n::::{.task-container}\n\nProduce a simple plot of the group level differences between treatments\n\n\n<div class='webex-solution'><button>Possible Solution</button>\n\n\n:::{.panel-tabset}\n\n## Using Fert and Light columns\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbiomass |>  \n  ggplot(aes(x=Fert, y=Biomass.m2))+\n  geom_boxplot(aes(fill=Light), \n               width = .5,\n               alpha = .4,\n               outlier.shape = NA)+\n  geom_point(aes(colour = Light),\n              position = position_jitterdodge(dodge.width =.5,\n                                              jitter.width = .2)) # Dodge and jitter data points\n```\n\n::: {.cell-output-display}\n![](13-interaction_files/figure-html/unnamed-chunk-8-1.png){fig-align='center' width=100%}\n:::\n\n```{.r .cell-code}\n # biomass |>  \n #  ggplot(aes(x=Fert, y=Biomass.m2))+\n #  geom_boxplot(aes(fill=Light), \n #               width = .5,\n #               alpha = .4,\n #               outlier.shape = NA)+\n #  geom_beeswarm(aes(colour = Light),\n #              dodge.width = .5)\n```\n:::\n\n\n\n## Using FL columns\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbiomass |>  \n  ggplot(aes(x=FL, y=Biomass.m2))+\n  geom_boxplot(width = .5,\n               alpha = .4,\n               outlier.shape = NA)+\n  geom_beeswarm() \n```\n\n::: {.cell-output-display}\n![](13-interaction_files/figure-html/unnamed-chunk-9-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n:::\n\n\n</div>\n\n::::\n\n:::\n\n## ANOVA\n\nIf we use the `FL` column as a predictor then this is equivalent to a four-level **one way ANOVA**.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nls_1 <- lm(Biomass.m2 ~ FL, data = biomass)\nsummary(ls_1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Biomass.m2 ~ FL, data = biomass)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-233.619  -42.842    1.356   67.961  175.381 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   355.79      23.14  15.376  < 2e-16 ***\nFLF-L+         30.13      32.72   0.921  0.36095    \nFLF+L-         93.69      32.72   2.863  0.00577 ** \nFLF+L+        219.23      32.72   6.699 8.13e-09 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 92.56 on 60 degrees of freedom\nMultiple R-squared:  0.4686,\tAdjusted R-squared:  0.442 \nF-statistic: 17.63 on 3 and 60 DF,  p-value: 2.528e-08\n```\n\n\n:::\n:::\n\n\n- We can see that the control treatment `F- L-` is the intercept with a mean of 356g and standard error of 23g. \n\n- The Light treatment adds an average of 30g to the biomass (but this close to the standard error of this estimated mean difference - 32.72g). \n\n- In contrast the addition of fertiliser `F+L-` adds 93g to the biomass. \n\n- The `F+ L+` Treatment effect adds 219g of biomass compared to the no fertiliser and no light treatment. \n\n:::{.callout-note}\n\nRemember the intercept represents the value of y when x = 0, when applied to factorial predictors it represents the mean of one of the levels. In this data there are two conditions for each variable: +/-. So in this model the intercept represents Biomass when both Fert and Light are \"-\". \n\n:::\n\nIf we wanted to get the precise confidence intervals of effect sizes we could use `broom::tidy(ls_1, conf.int = T)` or `confint(ls1)`. \n\nWe can visualise these differences with a coefficient plot, and see clearly that adding light by itself produce a slight increase in the mean biomass of our samples **but** the 95% confidence interval includes zero, so we don't have any real confidence that this is a consistent/true effect.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nGGally::ggcoef_model(ls_1,\n                      show_p_values=FALSE,\n                      signif_stars = FALSE,\n                     conf.level=0.95)\n```\n\n::: {.cell-output-display}\n![Effects of light and fertiliser treatments on biomass relative to an untreated control (error bars = 95% CI)](13-interaction_files/figure-html/unnamed-chunk-11-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n### Reporting and understanding ANOVA\n\nOur model summary provides a lot of information, can you identify this information?\n\n- Raw variance in Biomass explained: \n\n\n<div class='webex-solution'><button>Solution</button>\n\nMultiple R-squared is 0.47, 47% of the total variance in biomass can be explained by the Fert and Light treatments\n\n</div>\n\n\n- Adjusted variance in Biomass explained: \n\n\n<div class='webex-solution'><button>Solution</button>\n\nAccounting for the number of different categories in the model (complexity) the adjusted variance explained is 44%\n\n</div>\n\n\n- Whether variance explained by treatments is statistically significant?\n\n\n<div class='webex-solution'><button>Solution</button>\n\n\nWe can read this directly from the model summary *or* \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nanova(ls_1)\n\n# drop1(ls_1)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|          | Df|   Sum Sq|    Mean Sq|  F value| Pr(>F)|\n|:---------|--:|--------:|----------:|--------:|------:|\n|FL        |  3| 453214.1| 151071.368| 17.63487|      0|\n|Residuals | 60| 513997.7|   8566.629|       NA|     NA|\n\n</div>\n:::\n:::\n\n\nThe overall effect of treatments *is* statistically significant F~3,60~=17.64, P<0.001\n\n\n\n</div>\n\n\n\n## Interaction effects\n\nLooking at the estimates from the four different treatments - do you think the effects of Fertiliser and Light on Biomass are *independent* of each other? \n\nAn interaction effect in a linear model is when the effect of one variable depends on the level of another variable. \n\nBelow are two figures that show the slope or effect we might expect to see if Fertiliser and Light have only *additive* effects (they each affect Biomass but do not interact with each other) or if they have an *interaction* effect (fertiliser and light *each* have more of an effect in the presence of each other).\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Left an illustration of an additive model, Right an illustration of a model with an interaction effect.](13-interaction_files/figure-html/unnamed-chunk-13-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n:::{.task}\n::::{.task-header}\nYour turn\n::::\n::::{.task-container}\n\nLook at the plots you made previously, and the estimates of your original model - do you think there is evidence of an interaction effect?\n\n\n<div class='webex-solution'><button>Discussion</button>\n\nIt's not hard to imagine that Light might help with plant growth on its own, and fertiliser might help on its own, but the combined effect of fertiliser and light could be greater (or sometimes different) than what you’d expect just by adding up the effects of each one separately. That extra effect, due to the two variables interacting, is the **interaction effect**.\n\nIf you don’t include an interaction effect when it's needed, your model might be misleading. It could either underestimate or overestimate the true effect of each variable because it doesn't account for how they work together. This could lead to wrong conclusions about the impact of each variable, making your predictions or understanding of the relationships less accurate. \n\nIn our case I think it is **highly likely** that Light and Fertiliser have an interaction effect\n\n\n</div>\n\n\n::::\n:::\n\n### Modelling an interaction effect\n\n\nTo produce an interaction model, we need to use the *separate* columns for fertiliser and light and then to include an interaction term we add this as `Light:Fert` written out as follows:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nls_2 <- lm(Biomass.m2 ~ Fert + # main effect\n             Light + # main effect\n             Fert:Light, # interaction term\n           data = biomass)\n\nsummary(ls_2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Biomass.m2 ~ Fert + Light + Fert:Light, data = biomass)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-233.619  -42.842    1.356   67.961  175.381 \n\nCoefficients:\n               Estimate Std. Error t value Pr(>|t|)    \n(Intercept)      355.79      23.14  15.376  < 2e-16 ***\nFertF+            93.69      32.72   2.863  0.00577 ** \nLightL+           30.13      32.72   0.921  0.36095    \nFertF+:LightL+    95.41      46.28   2.062  0.04359 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 92.56 on 60 degrees of freedom\nMultiple R-squared:  0.4686,\tAdjusted R-squared:  0.442 \nF-statistic: 17.63 on 3 and 60 DF,  p-value: 2.528e-08\n```\n\n\n:::\n:::\n\n\n\nNotice that estimates in the model for the effect of Fert:Light have changed. All of the other estimates and terms have stayed the same on every other row *except this one*. Why has this changed?\n\nAn interaction model changes the hypothesis we are asking - rather than trying to make an estimate of the mean difference for `F+L+` vs `F-L-` as in our first model, *now* we testing explicitly whether there is **more of an effect** on Biomass when Fert and Light are combined than we might expect from simply adding their effects together. \n\nHere the model is quantifying that we are finding an *extra* 95.4 g/m^2 of Biomass when we combine Fertiliser and Light treatments than we would predict from each effect individually. \n\n\n<div class='webex-solution'><button>The maths</button>\n\n\nSo in model 2 we have separated the treatment of `F+L+` into three parts, the effect of adding light, the effect of adding fertiliser and the effect of combining them. Add these together and it should match our original estimate from model 1.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# model 2\ncoef(ls_2)[2] + coef(ls_2)[3] + coef(ls_2)[4]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n FertF+ \n219.225 \n```\n\n\n:::\n:::\n\n\n\n\n</div>\n\n\nThis effect appears to be statistically significant (but only just): \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nGGally::ggcoef_model(ls_2,\n                      show_p_values=FALSE,\n                      signif_stars = FALSE,\n                     conf.level=0.95)\n```\n\n::: {.cell-output-display}\n![](13-interaction_files/figure-html/unnamed-chunk-16-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n\n:::{callout-warning}\n\nDon't make the mistake of looking at the main effect of light treatment, and reporting there is no effect because the uncertainty intervals cross zero. The main effect of light gives the average effect across the two fertiliser treatments. However, because of the interaction effect, we know this doesn't tell the whole story - whether light has an effect depends on whether fertiliser has been applied. \n\nSo, if you have a significant interaction term, you must consider the main effects, regardless of whether they are significant on their own. \n\n:::\n\n### Write-up\n\nWe could now write this up as follows:\n\n> There was an interaction effect of light and fertiliser treatments (ANOVA *F*~1,60~ = 4.25, *P* = 0.044) in which combining treatments produced substantially more biomass (95.4g [95% CI: 2.8 - 188]) than expected from the additive effects alone (Fertiliser 93.7g [28.2 - 159.2], Light 30.1g [-35.3 - 95.6]). \n\nDo not make the mistake of *just* reporting the statistics, the interesting bit is the size of the effect (estimate) and the uncertainty (confidence intervals). \n\n\n<div class='webex-solution'><button>reporting ANOVA</button>\n\n\n### ANOVA tables\n\nSo you have made a linear model with an interaction term, how do you report whether this interaction is significant? How do you report the main effect terms when there is an interaction present?\n\n1. **Start with the interaction**\n\nIn previous chapters we ran the `anova()` function directly on our linear model. This works well for simple & 'balanced' designs (there are equal sample sizes in each level of a factor), but can be misleading with ['unbalanced' designs or models with complex interactions](https://mcfromnz.wordpress.com/2011/03/02/anova-type-iiiiii-ss-explained/). \n\nIn order to report an *F* statistic for the interaction effect, we need to carry out an *F*-test of two models, one *with* and one *without* the interaction effect. Here we can use the `anova()` function again but we will compare *nested models*\n\n::: {.panel-tabset}\n\n## anova()\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# A simpler model with the interaction term removed\nls_3 <- lm(Biomass.m2 ~ Fert + Light, data = biomass)\n\n# Put the simpler model first\nanova(ls_3, ls_2,  test = \"F\")\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| Res.Df|      RSS| Df| Sum of Sq|        F|    Pr(>F)|\n|------:|--------:|--:|---------:|--------:|---------:|\n|     61| 550407.1| NA|        NA|       NA|        NA|\n|     60| 513997.7|  1|  36409.41| 4.250144| 0.0435871|\n\n</div>\n:::\n:::\n\n\n## drop1()\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# An equivalent function can be performed with drop1 which will do this automatically\n\ndrop1(ls_2, test = \"F\")\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|           | Df| Sum of Sq|      RSS|      AIC|  F value|    Pr(>F)|\n|:----------|--:|---------:|--------:|--------:|--------:|---------:|\n|<none>     | NA|        NA| 513997.7| 583.4298|       NA|        NA|\n|Fert:Light |  1|  36409.41| 550407.1| 585.8099| 4.250144| 0.0435871|\n\n</div>\n:::\n:::\n\n\n:::\n\nThis *F*-test is testing the *null hypothesis* that there is no true interaction effect. The significance test rejects the null hypothesis (just). It also provides the **Akaike information criterion (AIC)**, an alternative method of model selection (more on this later). \n\n\n\n\n</div>\n\n\n\n### Check Model fit\n\nWe need to make sure that any model we make fits our data and our assumptions well. It is important to do this *before* analysing any statistical tests or interpreting our results:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nperformance::check_model(ls_2,\n                         detrend = FALSE)\n```\n\n::: {.cell-output-display}\n![](13-interaction_files/figure-html/unnamed-chunk-19-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\nIn this case it looks like our model is a good fit and we can happily proceed:\n\n### post-hoc\n\n\nIn this example it is unnecessary to spend time looking at pairwise comparisons between the four possible levels, the interesting finding is to report the strength of the interaction effect. **But** it is possible to generate estimated means, and produce pairwise comparisons with the `emmeans()` package\n\n\n:::{.panel-tabset}\n\n## Estimated means\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nemmeans::emmeans(ls_2, specs = ~ Light + Fert) |>  \n  confint()\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|Light |Fert |   emmean|       SE| df| lower.CL| upper.CL|\n|:-----|:----|--------:|--------:|--:|--------:|--------:|\n|L-    |F-   | 355.7937| 23.13902| 60| 309.5088| 402.0787|\n|L+    |F-   | 385.9187| 23.13902| 60| 339.6338| 432.2037|\n|L-    |F+   | 449.4875| 23.13902| 60| 403.2026| 495.7724|\n|L+    |F+   | 575.0187| 23.13902| 60| 528.7338| 621.3037|\n\n</div>\n:::\n:::\n\n\n## Contrasts\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nemmeans::emmeans(ls_2, specs = pairwise ~ Light + Fert) |>  \n  confint()\n# including the argument pairwise in front of the ~ prompts the post-hoc pairwise comparisons.\n # $emmeans contains the estimate mean values for each possible combination (with confidence intervals)\n # $ contrasts contains tukey test post hoc comparisons between levels\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$emmeans\n Light Fert emmean   SE df lower.CL upper.CL\n L-    F-      356 23.1 60      310      402\n L+    F-      386 23.1 60      340      432\n L-    F+      449 23.1 60      403      496\n L+    F+      575 23.1 60      529      621\n\nConfidence level used: 0.95 \n\n$contrasts\n contrast          estimate   SE df lower.CL upper.CL\n (L- F-) - (L+ F-)    -30.1 32.7 60     -117    56.35\n (L- F-) - (L- F+)    -93.7 32.7 60     -180    -7.22\n (L- F-) - (L+ F+)   -219.2 32.7 60     -306  -132.75\n (L+ F-) - (L- F+)    -63.6 32.7 60     -150    22.90\n (L+ F-) - (L+ F+)   -189.1 32.7 60     -276  -102.63\n (L- F+) - (L+ F+)   -125.5 32.7 60     -212   -39.06\n\nConfidence level used: 0.95 \nConf-level adjustment: tukey method for comparing a family of 4 estimates \n```\n\n\n:::\n:::\n\n\n:::\n\n\n\n## ANCOVA {#sec-ancova}\n\nThe previous section looked at an interaction between two categorical variables, we can also examine interactions between a factor and a continuous variable. Often referred to as ANCOVA. \n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<a href=\"https://raw.githubusercontent.com/UEABIO/5027A/refs/heads/dev/files/pollution.csv\">\n<button class=\"btn btn-success\"><i class=\"fa fa-save\"></i> Download pollution data as csv</button>\n</a>\n```\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\nThe data is from an experimental study of the effects of low-level atmospheric pollutants and drought on agricultural yields. The experiment aimed to see how the yields soya bean (William variety), were affected by stress and Ozone levels. **Your task is to first determine whether there is any evidence of an interaction effect, and if not drop this term from your model and then report the estimates and confidence intervals from the simplified model**. \n\n### Activity: Build your own analysis\n\nTry and make as much progress as you can without checking the solutions. Click on the boxes when you need help/to check your working\n\n#### Task: Explore the data!\n\nCheck the data for errors and formatting\n\n\n<div class='webex-solution'><button>Solution</button>\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# check the structure of the data\nglimpse(pollution)\n\n# check data is in a tidy format\nhead(pollution)\n\n# check variable names\ncolnames(pollution)\n\n# check for duplication\npollution |>  \n  duplicated() |>  \n  sum()\n\n# check for typos - by looking at impossible values\n# quick summary\n\nsummary(biomass)\n\n# check for typos by looking at distinct characters/values\npollution |>  \n  distinct(Stress)\n\n\n# missing values\nbiomass |>  \n  is.na() |>  \n  sum()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 30\nColumns: 3\n$ Stress  <chr> \"Well-watered\", \"Well-watered\", \"Well-watered\", \"Well-watered\"…\n$ O3      <dbl> 0.02, 0.05, 0.07, 0.08, 0.10, 0.02, 0.05, 0.07, 0.08, 0.10, 0.…\n$ William <dbl> 8.623533, 8.690642, 8.360071, 8.151910, 8.032685, 8.535426, 8.…\n```\n\n\n:::\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|Stress       |   O3|  William|\n|:------------|----:|--------:|\n|Well-watered | 0.02| 8.623533|\n|Well-watered | 0.05| 8.690642|\n|Well-watered | 0.07| 8.360071|\n|Well-watered | 0.08| 8.151910|\n|Well-watered | 0.10| 8.032685|\n|Well-watered | 0.02| 8.535426|\n\n</div>\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Stress\"  \"O3\"      \"William\"\n[1] 0\n     Fert              Light                FL              Biomass.m2   \n Length:64          Length:64          Length:64          Min.   :152.3  \n Class :character   Class :character   Class :character   1st Qu.:370.1  \n Mode  :character   Mode  :character   Mode  :character   Median :425.9  \n                                                          Mean   :441.6  \n                                                          3rd Qu.:517.2  \n                                                          Max.   :750.4  \n```\n\n\n:::\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|Stress       |\n|:------------|\n|Well-watered |\n|Stressed     |\n\n</div>\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n:::\n\n\n\n</div>\n\n\n\n#### Visualise the data\n\nMake simple scatterplots to look at relationships\n\n\n\n<div class='webex-solution'><button>Solution</button>\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npollution |>  \n  ggplot(aes(x = O3, y = William))+\n  geom_point()+\n  facet_wrap(~ Stress)+\n    labs(x = expression(paste(Ozone~mu~L~L^-1)),\n       y = expression(paste(Log~Yield~(kg~ha^-1))))\n```\n\n::: {.cell-output-display}\n![](13-interaction_files/figure-html/unnamed-chunk-25-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n</div>\n\n\n\n\n#### Model the data\n\nBuild a linear model\n\n\n<div class='webex-solution'><button>Solution</button>\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nWilliam_ls1 <- lm(William ~ O3 + Stress + O3:Stress, data = pollution)\n\nWilliam_ls1 |>  \n    broom::tidy(conf.int = T)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|term                  |   estimate| std.error|  statistic|   p.value|   conf.low|  conf.high|\n|:---------------------|----------:|---------:|----------:|---------:|----------:|----------:|\n|(Intercept)           |  8.4902296| 0.0974956| 87.0832016| 0.0000000|  8.2898245|  8.6906347|\n|O3                    | -6.4671581| 1.4014008| -4.6147812| 0.0000929| -9.3477788| -3.5865375|\n|StressWell-watered    |  0.2642307| 0.1378796|  1.9163870| 0.0663707| -0.0191849|  0.5476463|\n|O3:StressWell-watered | -1.3472822| 1.9818801| -0.6798001| 0.5026393| -5.4210950|  2.7265306|\n\n</div>\n:::\n:::\n\n\nIt looks as though there is no strong evidence here for an interaction effect, but before we proceed any further we should check that the model is a good fit for our data. \n\n\n</div>\n\n\n#### Check the model fit\n\n\n\n<div class='webex-solution'><button>Solution</button>\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nperformance::check_model(William_ls1,\n                         detrend = FALSE)\n```\n\n::: {.cell-output-display}\n![](13-interaction_files/figure-html/unnamed-chunk-27-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n</div>\n\n\n#### Simplify the model\n\n\nEverything looks pretty good, so now we could go ahead and simplify our model. \n\n\n\n<div class='webex-solution'><button>Solution</button>\n\n\nTesting that dropping the interaction term does not significantly reduce the variance explained\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nWilliam_ls2 <- lm(William ~ O3 + Stress, data = pollution)\n\nanova(William_ls2, William_ls1, test = \"F\")\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| Res.Df|       RSS| Df| Sum of Sq|         F|    Pr(>F)|\n|------:|---------:|--:|---------:|---------:|---------:|\n|     27| 0.5799809| NA|        NA|        NA|        NA|\n|     26| 0.5698523|  1| 0.0101286| 0.4621281| 0.5026393|\n\n</div>\n:::\n:::\n\n\n\nGet the F values of the simpler model\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nWilliam_ls3a <- lm(William ~ Stress, data = pollution)\nWilliam_ls3b <- lm(William ~ O3, data = pollution)\n\nanova(William_ls3a, William_ls2, test = \"F\")\nanova(William_ls3b, William_ls2, test = \"F\")\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| Res.Df|       RSS| Df| Sum of Sq|        F| Pr(>F)|\n|------:|---------:|--:|---------:|--------:|------:|\n|     28| 1.7181003| NA|        NA|       NA|     NA|\n|     27| 0.5799809|  1|  1.138119| 52.98317|  1e-07|\n\n</div><div class=\"kable-table\">\n\n| Res.Df|       RSS| Df| Sum of Sq|        F|    Pr(>F)|\n|------:|---------:|--:|---------:|--------:|---------:|\n|     28| 0.8176233| NA|        NA|       NA|        NA|\n|     27| 0.5799809|  1| 0.2376424| 11.06303| 0.0025466|\n\n</div>\n:::\n:::\n\n\n\n\n</div>\n\n\n#### Report the estimates and confidence intervals of the new model\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nWilliam_ls2 |>  \n    broom::tidy(conf.int = T)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|term               |   estimate| std.error|  statistic|   p.value|   conf.low|  conf.high|\n|:------------------|----------:|---------:|----------:|---------:|----------:|----------:|\n|(Intercept)        |  8.5333427| 0.0733079| 116.404189| 0.0000000|  8.3829273|  8.6837580|\n|O3                 | -7.1407992| 0.9810200|  -7.278954| 0.0000001| -9.1536861| -5.1279124|\n|StressWell-watered |  0.1780046| 0.0535173|   3.326113| 0.0025466|  0.0681962|  0.2878131|\n\n</div>\n:::\n:::\n\n\n\n\n\n#### Write up the results\n\n\n\n<div class='webex-solution'><button>Solution</button>\n\n\nI hypothesised that plants under stress might react more negatively to pollution than non-stressed plants, however when tested I found no evidence of a negative interation effect between stress and Ozone levels (*F*~1,26~ = 0.4621, *P* = 0.5). Individually however, while well-watered plants had higher yields than stressed plants (mean 0.178 [95% CI: 0.0682 - 0.288]) (*F*~1,27~ = 11, *P* = 0.003), there was a much larger effect of Ozone, where every unit increase ($\\mu$L L^-1^) produced a mean decrease in yield of 7.14 kg ha^-1^ [5.13 - 9.15] (*F*~1,27~ = 53, *P* < 0.001). \n\n\n</div>\n\n\n## Summary\n\n* Always have a good hypothesis for including an interaction\n\n* When models have significant interaction effects you must always consider the main terms even if they are not significant by themselves\n\n* Report *F* values from interactions as a priority\n\n* **IF** interactions are significant then estimates should come from the full model, while *F*-values should come from a reduced model (for main effects). **IF** interaction terms are not significant they can be removed (model simplification).\n\n* Use nested models to avoid mistakes when using an unbalanced experiment design\n\n* Always report estimates and effect sizes - this is the important bit - and easy to lose sight of when models get more complicated\n\n\n",
    "supporting": [
      "13-interaction_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"site_libs/font-awesome-6.7.2/js/script.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}