{
  "hash": "d13d222995858ad0bdd9e290c5265853",
  "result": {
    "engine": "knitr",
    "markdown": "# Foundations of Mixed Modelling\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n\n\n\n\n\n\n## What is a mixed model?\n\nMixed models (also known as linear mixed models or hierarchical linear models) are statistical tests that build on the simpler tests of regression, t-tests and ANOVA. All of these tests are special cases of the general linear model; they all fit a straight line to data to explain variance in a systematic way. \n\nThe key difference with a linear mixed-effects model is the inclusion of random effects - variables where our observations are grouped into subcategories that systematically affect our outcome - to account for important structure in our data. \n\nThe mixed-effects model can be used in many situations instead of one of our more straightforward tests when this structure may be important. The main advantages of this approach are: \n\ni) mixed-effects models account for more of the variance \nii) mixed-effects models incorporate group and even individual-level differences\niii) mixed-effects models cope well with missing data, unequal group sizes and repeated measurements\n\n\n## Fixed vs Random effects\n\nFixed effects and random effects are terms commonly used in mixed modeling, which is a statistical framework that combines both in order to analyze data. \n\nIn mixed modeling, the fixed effects are used to estimate the overall relationship between the predictors and the response variable, while the random effects account for the within-group variability and allow for the modeling of the individual differences or group-specific effects.\n\nThe hierarchical structure of data refers to a data organization where observations are nested within higher-level groups or clusters. For example, students nested within classrooms, patients nested within hospitals, or employees nested within companies. This hierarchical structure introduces dependencies or correlations within the data, as observations within the same group tend to be more similar to each other than observations in different groups.\n\nThe need for mixed models arises when we want to account for these dependencies and properly model the variability at different levels of the hierarchy. Traditional regression models, such as ordinary least squares (OLS), assume that the observations are independent of each other. However, when working with hierarchical data, this assumption is violated, and ignoring the hierarchical structure can lead to biased or inefficient estimates, incorrect standard errors, and misleading inference.\n\nBy including random effects, mixed models allow for the estimation of both within-group and between-group variability. They provide a flexible framework for modeling the individual or group-specific effects and can capture the heterogeneity within and between groups. Additionally, mixed models can handle unbalanced or incomplete data, where some groups may have different numbers of observations.\n\n### Fixed effects\n\nIn broad terms, fixed effects are variables that we expect will affect the dependent/response variable: they’re what you call explanatory variables in a standard linear regression. \n\nFixed effects are more common than random effects, at least in their use. Fixed effects estimate different levels with no relationship assumed between the levels. For example, in a model with a dependent variable of body length and a fixed effect for fish sex, you would get an estimate of mean body length for males and then an estimate for females separately. \n\nWe can consider this in terms of a very simple linear model, here the estimated intercept is the expected value of the outcome $y$ when the predictor $x$ has a value of 0. The estimated slope is the expected change in $y$ for a single unit change in $x$. These parameters are \"fixed\", meaning that each individual in the population has the same expected value for the intercept and slope. \n\nThe difference between the expected value and true value is called \"residual error\".\n\n$$Y_i = \\beta_0 + \\beta_1X_i + \\epsilon_i$$\n\n#### Examples: \n\n1. Medical Research: In a clinical trial studying the effectiveness of different medications for treating a specific condition, the fixed effects could include categorical variables such as treatment group (e.g., medication A, medication B, placebo) or dosage level (e.g., low, medium, high). These fixed effects would capture the systematic differences in the response variable (e.g., symptom improvement) due to the specific treatment received.\n\n2. Education Research: Suppose a study examines the impact of teaching methods on student performance in different schools. The fixed effects in this case might include variables such as school type (e.g., public, private), curriculum approach (e.g., traditional, progressive), or classroom size. These fixed effects would help explain the differences in student achievement across schools, accounting for the systematic effects of these factors.\n\n3. Environmental Science: Imagine a study investigating the factors influencing bird species richness across different habitats. The fixed effects in this context could include variables such as habitat type (e.g., forest, grassland, wetland), habitat disturbance level (e.g., low, medium, high), or geographical region. These fixed effects would capture the systematic variations in bird species richness associated with the specific habitat characteristics.\n\nFixed effects are the default effects that we all learn as we begin to understand statistical concepts, and fixed effects are the default effects in functions like `lm()` and `aov()`.\n\n### Random effects\n\nRandom effects are less commonly used but perhaps more widely encountered in nature. Each level can be considered a random variable from an underlying process or distribution in a random effect. \n\nA random effect is a parameter that is allowed to vary across groups or individuals. Random effects do not take a single fixed value, rather they follow a distribution (usually the normal distribution). Random effects can be added to a model to account for variation around an intercept or slope. Each individual or group then gets their own estimated random effect, representing an adjustment from the mean. \n\nSo random effects are usually grouping factors for which we are trying to control. They are always categorical, as you can’t force R to treat a continuous variable as a random effect. A lot of the time we are not specifically interested in their impact on the response variable, but we know that they might be influencing the patterns we see.\n\n#### Examples: \n\n1. Longitudinal Health Study: Consider a study tracking the blood pressure of individuals over multiple time points. In this case, a random effect can be included to account for the individual-specific variation in blood pressure. Each individual's blood pressure measurements over time would be treated as repeated measures within that individual, and the random effect would capture the variability between individuals that is not explained by the fixed effects. This random effect allows for modeling the inherent individual differences in blood pressure levels.\n\n2. Social Network Analysis: Suppose a study examines the influence of peer groups on adolescent behavior. The study may collect data on individual behaviors within schools, where students are nested within classrooms. In this scenario, a random effect can be incorporated at the classroom level to account for the shared social environment within each classroom. The random effect captures the variability in behavior among classrooms that is not accounted for by the fixed effects, enabling the study to analyze the effects of individual-level and classroom-level factors simultaneously.\n\n3. Ecological Study: Imagine a research project investigating the effect of environmental factors on species abundance in different study sites. The study sites may be geographically dispersed, and a random effect can be included to account for the variation between study sites. The random effect captures the unexplained heterogeneity in species abundance across different sites, allowing for the examination of the effects of environmental variables while accounting for site-specific differences.\n\nThe random effect $U_i$ is often assumed to follow a normal distribution with a mean of zero and a variance estimated during the model fitting process.\n\n$$Y_i = β_0 + U_j + ε_i$$\n\n::: {.callout-warning}\nIn the book \"Data analysis using regression and multilevel/hierarchical models\" (@gelman_hill_2006). The authors examined five definitions of fixed and random effects and found no consistent agreement. \n\n(1) Fixed effects are constant across individuals, and random effects vary. For example, in a growth study, a model with random intercepts a_i and fixed slope b corresponds to parallel lines for different individuals i, or the model y_it = a_i + b t thus distinguish between fixed and random coefficients.\n\n(2) Effects are fixed if they are interesting in themselves or random if there is interest in the underlying population.\n\n(3) “When a sample exhausts the population, the corresponding variable is fixed; when the sample is a small (i.e., negligible) part of the population the corresponding variable is random.”\n\n(4) “If an effect is assumed to be a realized value of a random variable, it is called a random effect.” \n\n(5) Fixed effects are estimated using least squares (or, more generally, maximum likelihood) and random effects are estimated with shrinkage. \n\nThus it turns out fixed and random effects are not born but made. We must make the decision to treat a variable as fixed or random in a particular analysis. \n:::\n\n\n> When determining what should be a fixed or random effect in your study, consider what are you trying to do? What are you trying to make predictions about? What is just variation (a.k.a “noise”) that you need to control for?\n\n::: {.callout-warning}\nMore about random effects:\n\nNote that the golden rule is that you generally want your random effect to have at least five levels. So, for instance, if we wanted to control for the effects of fish sex on body length, we would fit sex (a two level factor: male or female) as a fixed, not random, effect.\n\nThis is, put simply, because estimating variance on few data points is very imprecise. Mathematically you could, but you wouldn’t have a lot of confidence in it. If you only have two or three levels, the model will struggle to partition the variance - it will give you an output, but not necessarily one you can trust.\n\nFinally, keep in mind that the name random doesn’t have much to do with mathematical randomness. Yes, it’s confusing. Just think about them as the grouping variables for now. Strictly speaking it’s all about making our models representative of our questions and getting better estimates. Hopefully, our next few examples will help you make sense of how and why they’re used.\n\n There’s no firm rule as to what the minimum number of factor levels should be for random effect and really you can use any factor that has two or more levels. However it is commonly reported that you may want five or more factor levels for a random effect in order to really benefit from what the random effect can do (though some argue for even more, 10 levels). Another case in which you may not want to random effect is when you don’t want your factor levels to inform each other or you don’t assume that your factor levels come from a common distribution. As noted above, male and female is not only a factor with only two levels but oftentimes we want male and female information estimated separately and we’re not necessarily assuming that males and females come from a population of sexes in which there is an infinite number and we’re interested in an average.\n\n:::\n\n## Why use mixed models?\n\nThe provided code generates a dataset that is suitable for testing mixed models. Let's break down the code and annotate each step:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Generating a fake dataset with different means for each group\nset.seed(123)  # Setting seed for reproducibility\n\n\nrand_eff <- data.frame(group = as.factor(seq(1:5)),\n            b0 = rnorm(5, mean = 0, sd = 20),\n            b1 = rnorm(5, 0, 0.5))\n```\n:::\n\n\nThis section creates a data frame called rand_eff containing random effects. It consists of five levels of a grouping variable (group), and for each level, it generates random effects (b0 and b1) using the `rnorm` function.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndata <- expand.grid(\n  group = as.factor(seq(1:10)),\n  obs = as.factor(seq(1:100))\n) |>\n  (\\(df) left_join(df, rand_eff, by = \"group\"))() |>\n  (\\(df) mutate(\n    df,\n    x = runif(n = nrow(df), 0, 10),\n    B0 = 20,\n    B1 = 2,\n    E = rnorm(n = nrow(df), 0, 10)\n  ))() |>\n  (\\(df) mutate(df, y = B0 + b0 + x * (B1 + b1) + E))()\n\n\ndata <- expand.grid(group = as.factor(seq(1:4)), \n                    obs = as.factor(seq(1:100)))\n```\n:::\n\n\nThis section creates the main dataset (data) for testing mixed models. It uses `expand.grid` to create a combination of levels for the grouping variable (group) and observation variable (obs). It then performs a `left join` with the rand_eff data frame, matching the group variable to incorporate the random effects for each group.\n\nThe code continues to `mutate` the dataset by adding additional variables:\n\n- x is a random predictor variable generated using `runif` to have values between 0 and 10.\n\n- B0 and B1 represent fixed effects of the intercept and slope with predetermined values of 20 and 2, respectively.\n\n- E represents the error term, generated using `rnorm` with a mean of 0 and standard deviation of 10.\n\n- Finally, y is created as the response variable using a linear model equation that includes the fixed effects (B0 and B1), random effects (b0 and b1), the predictor variable (x), and the error term (E).\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndata.1 <- expand.grid(group = as.factor(5),\n          obs = as.factor(seq(1:30)))\n\ndata <- bind_rows(data, data.1) |>  \n  (\\(df) left_join(df, rand_eff, by = \"group\"))() |>\n  (\\(df) mutate(\n    df,\n    x = runif(n = nrow(df), 0, 10),\n    B0 = 20,\n    B1 = 2,\n    E = rnorm(n = nrow(df), 0, 10)\n  ))() |>\n  (\\(df) mutate(df, y = B0 + b0 + x * (B1 + b1) + E))()\n```\n:::\n\n\nThis section creates an additional dataset (`data.1`) with a specific group (group = 5) and a smaller number of observations (obs = 30) for testing purposes. This is then appended to the original dataset, we will see the effect of having a smaller group within our random effects when we discuss partial pooling and shrinkage later on. \n\n\nNow we have three variables to consider in our models: x, y and group (with five levels).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndata |>  \n  select(x, y, group, obs) |>  \n  head()\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|         x|          y|group |obs |\n|---------:|----------:|:-----|:---|\n| 4.0584411| -0.5487802|1     |1   |\n| 7.2250893| 17.3260398|2     |1   |\n| 0.5963383| 41.2256737|3     |1   |\n| 3.3034922| 16.0958571|4     |1   |\n| 7.7676400| 32.0586590|1     |2   |\n| 8.4045935| 50.1274193|2     |2   |\n\n</div>\n:::\n:::\n\n\nNow that we have a suitable simulated dataset, let's start modelling!\n\n### All in one model\n\nWe will begin by highlighting the importance of considering data structure and hierarchy when building linear models. To illustrate this, we will delve into an example that showcases the consequences of ignoring the underlying data structure. We might naively construct a single linear model that ignores the group-level variation and treats all observations as independent. This oversimplified approach fails to account for the fact that observations within groups are more similar to each other due to shared characteristics.\n\n$$Y_i = \\beta_0 + \\beta_1X_i + \\epsilon_i$$\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbasic_model <- lm(y ~ x, data = data)\nsummary(basic_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = y ~ x, data = data)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-37.23 -12.11  -2.36  11.00  44.53 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  21.0546     1.6490  12.768   <2e-16 ***\nx             2.5782     0.2854   9.034   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 16.96 on 428 degrees of freedom\nMultiple R-squared:  0.1602,\tAdjusted R-squared:  0.1582 \nF-statistic: 81.62 on 1 and 428 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nHere we can see that the basic linear model has produced a statistically significant regression analysis (*t*~428~ = 9.034, *p* <0.001) with an $R^2$ of 0.16. There is a medium effect positive relationship between changes in x and y (Estimate = 2.58, S.E. = 0.29).\n\nWe can see that clearly if we produce a simple plot of x against y: \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot(data$x, data$y)\n```\n\n::: {.cell-output-display}\n![Simple scatter plot x against y](mixed-model_files/figure-html/unnamed-chunk-8-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\nHere if we use the function `geom_smooth()` on the scatter plot, the plot also includes a fitted regression line obtained using the \"lm\" method. This allows us to examine the overall trend and potential linear association between the variables.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(data, aes(x = x, \n                 y = y)) +\n  geom_point() +\n  labs(x = \"Independent Variable\", \n       y = \"Dependent Variable\")+\n  geom_smooth(method = \"lm\")\n```\n\n::: {.cell-output-display}\n![Scatter plot displaying the relationship between the independent variable and the dependent variable. The points represent the observed data, while the fitted regression line represents the linear relationship between the variables. The plot helps visualize the trend and potential association between the variables.](mixed-model_files/figure-html/unnamed-chunk-9-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\nThe `check_model()`  function from the `performance` package (@R-performance) is used to evaluate the performance and diagnostic measures of a statistical model. It provides a comprehensive assessment of the model's fit, assumptions, and predictive capabilities. By calling this function, you can obtain a summary of various evaluation metrics and diagnostic plots for the specified model. \n\nIt enables you to identify potential issues, such as violations of assumptions, influential data points, or lack of fit, which can affect the interpretation and reliability of your model's results\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nperformance::check_model(basic_model)\n```\n\n::: {.cell-output-display}\n![](mixed-model_files/figure-html/unnamed-chunk-10-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\nLooking at the fit of our model we would be tempted to conclude that we have an accurate and robust model.\n\nHowever, when data is hierarchically structured, such as individuals nested within groups, there is typically correlation or similarity among observations within the same group. By not accounting for this clustering effect, estimates derived from a single model can be biased and inefficient. The assumption of independence among observations is violated, leading to incorrect standard errors and inflated significance levels. \n\nFrom the figure below we can see the difference in median and range of x values within each of our groups: \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(data, aes(x = group, \n                 y = y)) +\n  geom_boxplot() +\n  labs(x = \"Groups\", \n       y = \"Dependent Variable\")\n```\n\n::: {.cell-output-display}\n![Linear model conducted on all data](mixed-model_files/figure-html/unnamed-chunk-11-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\nIn this figure,  we colour tag the data points by group, this can be useful for determining if a mixed model is appropriate.\n\nHere's why:\n\nBy colour-coding the data points based on the grouping variable, the plot allows you to visually assess the within-group and between-group variability. If there are noticeable differences in the data patterns or dispersion among the groups, it suggests that the data may have a hierarchical structure, where observations within the same group are more similar to each other than to observations in other groups.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Color tagged by group\nplot_group <- ggplot(data, aes(x = x, \n                               y = y, \n                               color = group,\n                               group = group)) +\n  geom_point(alpha = 0.6) +\n  labs(title = \"Data Coloured by Group\", \n       x = \"Independent Variable\", \n       y = \"Dependent Variable\")+\n  theme(legend.position=\"none\")\n\nplot_group\n```\n\n::: {.cell-output-display}\n![](mixed-model_files/figure-html/unnamed-chunk-12-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\nFrom the above plots, it confirms that our observations from within each of the ranges aren’t independent. We can’t ignore that: as we’re starting to see, it could lead to a completely erroneous conclusion.\n\n\n### Multiple analyses approach\n\nRunning separate linear models per group, also known as stratified analysis, can be a feasible approach in certain situations. However, there are several drawbacks including\n\n- Increased complexity\n\n- Inability to draw direct conclusions on overall variability \n\n- Reduced statistical power\n\n- Inflated Type 1 error risk\n\n- Inconsistent estimates\n\n- Limited ability to handle unbalanced/missing data\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Plotting the relationship between x and y with group-level smoothing\nggplot(data, aes(x = x, y = y, color = group, group = group)) +\n  geom_point(alpha = 0.6) +  # Scatter plot of x and y with transparency\n  labs(title = \"Data Colored by Group\", x = \"Independent Variable\", y = \"Dependent Variable\") +\n  theme(legend.position = \"none\") +\n  geom_smooth(method = \"lm\") +  # Group-level linear regression smoothing\n  facet_wrap(~group)  # Faceting the plot by group\n```\n\n::: {.cell-output-display}\n![Scatter plot showing the relationship between the independent variable (x) and the dependent variable (y) colored by group. Each subplot represents a different group. The line represents the group-level linear regression smoothing.](mixed-model_files/figure-html/unnamed-chunk-13-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Creating nested data by grouping the data by 'group'\nnested_data <- data |> \n  group_by(group) |> \n  nest()\n\n# Fitting linear regression models to each nested data group\nmodels <- map(nested_data$data, ~ lm(y ~ x, data = .)) |>  \n          map(broom::tidy)\n\n# Combining the model results into a single data frame\ncombined_models <- bind_rows(models)\n\n# Filtering the rows to include only the 'x' predictor\nfiltered_models <- combined_models |> \n                   filter(term == \"x\")\n\n# Adding a column for the group index using rowid_to_column function\ngroup_indexed_models <- filtered_models |> \n                        rowid_to_column(\"group\")\n\n# Modifying the p-values using a custom function report_p\nfinal_models <- group_indexed_models |> \n                mutate(p.value = report_p(p.value))\n\nfinal_models\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| group|term |   estimate| std.error|  statistic|p.value   |\n|-----:|:----|----------:|---------:|----------:|:---------|\n|     1|x    |  3.0643940| 0.3620254|  8.4645823|p < 0.001 |\n|     2|x    |  2.5162898| 0.3354848|  7.5004590|p < 0.001 |\n|     3|x    |  1.3904720| 0.3192878|  4.3549169|p < 0.001 |\n|     4|x    |  1.6856649| 0.3550511|  4.7476686|p < 0.001 |\n|     5|x    | -0.0755633| 0.6576868| -0.1148926|p= 0.909  |\n\n</div>\n:::\n:::\n\n\nIn the code above, the dataset data is first grouped by the variable 'group' using the `group_by` function, and then the data within each group is nested using the `nest` function. This results in a new dataset nested_data where each group's data is stored as a nested tibble.\n\nNext, a linear regression model (`lm`) is fit to each nested data group using the `map` function. The `broom::tidy` function is applied to each model using map to extract the model summary statistics, such as coefficients, p-values, and standard errors. The resulting models are stored in the models object.\n\nThe `bind_rows` function is used to combine the model results into a single data frame called combined_models. The data frame is then filtered to include only the rows where the predictor is 'x' using the `filter` function, resulting in the filtered_models data frame.\n\nTo add a column for the group index, the `rowid_to_column` function is applied to the filtered_models data frame, creating the group_indexed_models data frame with an additional column named 'group'.\n\nFinally, the p-values in the group_indexed_models data frame are modified using a custom function `report_p`\n\n\n<div class='webex-solution'><button>report_p function</button>\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n report_p <- function(p, digits = 3) {\n     reported <- if_else(p < 0.001,\n             \"p < 0.001\",\n             paste(\"p=\", round(p, digits)))\n     \n     return(reported)\n }\n```\n:::\n\n\n\n</div>\n\n\n### Complex model\n\nUsing a group level term with an interaction on x as a fixed effect means explicitly including the interaction term between x and the group as a predictor in the model equation. This approach assumes that the relationship between x and the outcome variable differs across groups and that these differences are constant and fixed. It implies that each group has a unique intercept (baseline level) and slope (effect size) for the relationship between x and the outcome variable. By treating the group level term as a fixed effect, the model estimates *specific parameter values for each group*.\n\nIf we are not explicitly interested in the outcomes or differences for each individual group (but wish to account for them) - this may not be the best option as it can lead to *overfitting* and it uses a lot more degrees of freedom - impacting estimates and widening our confidence intervals. As with running multiple models above, there is limited ability to make inferences outside of observed groups, and it does not handle missing data or unbalanced designs well. \n\n$$Y_i = \\beta_0 + \\beta_1X_i + \\beta_2.group_i+\\beta_3(X_i.group_i)+\\epsilon_i$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nadditive_model <- lm(y ~ x*group, data = data)\n\nsummary(additive_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = y ~ x * group, data = data)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-24.8614  -6.2579   0.2044   6.9342  28.5474 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   6.8125     1.8881   3.608 0.000346 ***\nx             3.0644     0.3379   9.070  < 2e-16 ***\ngroup2        6.4526     2.7289   2.365 0.018505 *  \ngroup3       44.8356     2.8539  15.710  < 2e-16 ***\ngroup4       15.8607     2.7184   5.835 1.08e-08 ***\ngroup5       22.9090     4.0772   5.619 3.51e-08 ***\nx:group2     -0.5481     0.4875  -1.124 0.261560    \nx:group3     -1.6739     0.4781  -3.501 0.000513 ***\nx:group4     -1.3787     0.4830  -2.855 0.004522 ** \nx:group5     -3.1400     0.7479  -4.198 3.28e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 9.801 on 420 degrees of freedom\nMultiple R-squared:  0.7246,\tAdjusted R-squared:  0.7187 \nF-statistic: 122.8 on 9 and 420 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n## Our first mixed model\n\nA mixed model is a good choice here: it will allow us to use all the data we have (higher sample size) and account for the correlations between data coming from the groups. We will also estimate fewer parameters and avoid problems with multiple comparisons that we would encounter while using separate regressions.\n\nWe can now join our random effect $U_j$ to the full dataset and define our y values as \n\n$$Y_{ij} = β_0 + β_1*X_{ij} + U_j + ε_{ij}$$.\n\n\nWe have a response variable, and we are attempting to explain part of the variation in test score through fitting an independent variable as a fixed effect. But the response variable has some residual variation (i.e. unexplained variation) associated with group. By using random effects, we are modeling that unexplained variation through variance.\n\nWe now want to know if an association between `y ~ x` exists after controlling for the variation in group.\n\n### Running mixed effects models with lmerTest\n\nThis section will detail how to run mixed models with the `lmer` function in the R package `lmerTest` (@R-lmerTest). This builds on the older `lme4` (@R-lme4) package, and in particular add p-values that were not previously included. There are other R packages that can be used to run mixed-effects models including the `nlme` package (@R-nlme) and the `glmmTMB` package (@R-glmmTMB). Outside of R there are also other packages and software capable of running mixed-effects models, though arguably none is better supported than R software.\n\n\n<div class='webex-solution'><button>Plotting random intercepts</button>\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot_function2 <- function(model, title = \"Data Coloured by Group\"){\n  \ndata <- data |>  \n  mutate(fit.m = predict(model, re.form = NA),\n         fit.c = predict(model, re.form = NULL))\n\ndata |> \n  ggplot(aes(x = x, y = y, col = group)) +\n  geom_point(pch = 16, alpha = 0.6) +\n  geom_line(aes(y = fit.c, col = group), linewidth = 2)  +\n  coord_cartesian(ylim = c(-40, 100))+\n  labs(title = title, \n       x = \"Independent Variable\", \n       y = \"Dependent Variable\") \n}\n\nmixed_model <- lmer(y ~ x + (1|group), data = data)\n\nplot_function2(mixed_model, \"Random intercept\")\n```\n:::\n\n\n\n</div>\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](mixed-model_files/figure-html/unnamed-chunk-18-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# random intercept model\nmixed_model <- lmer(y ~ x + (1|group), data = data)\n\nsummary(mixed_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML. t-tests use Satterthwaite's method [\nlmerModLmerTest]\nFormula: y ~ x + (1 | group)\n   Data: data\n\nREML criterion at convergence: 3224.4\n\nScaled residuals: \n     Min       1Q   Median       3Q      Max \n-2.61968 -0.63654 -0.03584  0.66113  3.13597 \n\nRandom effects:\n Groups   Name        Variance Std.Dev.\n group    (Intercept) 205      14.32   \n Residual             101      10.05   \nNumber of obs: 430, groups:  group, 5\n\nFixed effects:\n            Estimate Std. Error       df t value Pr(>|t|)    \n(Intercept)  23.2692     6.4818   4.1570    3.59   0.0215 *  \nx             2.0271     0.1703 424.0815   11.90   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nCorrelation of Fixed Effects:\n  (Intr)\nx -0.131\n```\n\n\n:::\n:::\n\n\n\nHere our groups clearly explain a lot of variance \n\n```\n\n205/(205 + 101) = 0.669 / 66.9%\n\n```\n\nSo the differences between groups explain ~67% of the variance that’s “left over” *after* the variance explained by our fixed effects.\n\n\n### Partial pooling\n\nIt is worth noting that random effect estimates are a function of the group-level information and the overall (grand) mean of the random effect. Group levels with low sample size or poor information (i.e., no strong relationship) are more strongly influenced by the grand mean, which adds information to an otherwise poorly-estimated group. However, a group with a large sample size or strong information (i.e., a strong relationship) will have very little influence from the grand mean and largely reflect the information contained entirely within the group. This process is called partial pooling (as opposed to no pooling, where no effect is considered, or total pooling, where separate models are run for the different groups). Partial pooling results in the phenomenon known as shrinkage, which refers to the group-level estimates being shrunk toward the mean. What does all this mean? If you use a random effect, you should be prepared for your factor levels to have some influence from the overall mean of all levels. With a good, clear signal in each group, you won’t see much impact from the overall mean, but you will with small groups or those without much signal.\n\nBelow we can take a look at the estimates and standard errors for three of our previously constructed models:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npooled <- basic_model |>  \n  broom::tidy() |>  \n  mutate(Approach = \"Pooled\", .before = 1) |>  \n  select(term, estimate, std.error, Approach)\n\nno_pool <- additive_model |>  \n  broom::tidy() |>  \n  mutate(Approach = \"No Pooling\", .before = 1) |>  \n  select(term, estimate, std.error, Approach)\n\npartial_pool <- mixed_model |>  \n  broom.mixed::tidy() |>  \n  mutate(Approach = \"Mixed Model/Partial Pool\", .before = 1) |>  \n  select(Approach, term, estimate, std.error)\n\nbind_rows(pooled, no_pool, partial_pool) |>  \n  filter(term %in% c(\"x\" , \"(Intercept)\") )\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|term        |  estimate| std.error|Approach                 |\n|:-----------|---------:|---------:|:------------------------|\n|(Intercept) | 21.054614| 1.6490185|Pooled                   |\n|x           |  2.578217| 0.2853798|Pooled                   |\n|(Intercept) |  6.812481| 1.8881155|No Pooling               |\n|x           |  3.064394| 0.3378685|No Pooling               |\n|(Intercept) | 23.269187| 6.4818211|Mixed Model/Partial Pool |\n|x           |  2.027065| 0.1703423|Mixed Model/Partial Pool |\n\n</div>\n:::\n:::\n\n\nPooling helps to improve the precision of the estimates by borrowing strength from the entire dataset. However, this can also lead to differences in the estimates and standard errors compared to models without pooling. \n\n- Pooled: in the pooled model the averaged estimates may not accurately reflect the true values within each group. As a result, the estimates in pooled models can be biased towards the average behavior across all groups. We can see this in the too small standard error of the intercept, underestimating the variance in our dataset. At the same time if there is substantial variability in the relationships between groups, the pooled estimates can be less precise. This increased variability across groups can contribute to larger standard errors of the difference (SED) for fixed effects in pooled models.\n\n- No pooling: This model is extremely precise with the smallest errors, however these estimates reflect conditions only for the first group in the model\n\n- Partial pooling/Mixed models: this model reflects the greater uncertainty of the Mean and SE of the intercept. However, the SED in a partial pooling model accounts for both the variability within groups and the uncertainty between groups. Compared to a no pooling approach, the SED in a partial pooling model tends to be smaller because it incorporates the pooled information, which reduces the overall uncertainty. This adjusted SED provides a more accurate measure of the uncertainty associated with the estimated differences between groups or fixed effects.\n\n## Predictions\n\nOne misconception about mixed-effects models is that we cannot produce estimates of the relationships for each group.\n\nBut how do we do this? \n\nWe can use the `coef()` function to extract the estimates (strictly these are predictions) for the random effects. This output has several components. \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncoef(mixed_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$group\n  (Intercept)        x\n1    11.82356 2.027066\n2    15.68146 2.027066\n3    47.94678 2.027066\n4    21.01028 2.027066\n5    19.88385 2.027066\n\nattr(,\"class\")\n[1] \"coef.mer\"\n```\n\n\n:::\n:::\n\n\nThis function produces our 'best linear unbiased predictions' (BLUPs) for the intercept and slope of the regression at each site. The predictions given here are different to those we would get if we ran individual models on each site, as BLUPs are a product of the compromise of complete-pooling and no-pooling models.  Now the predicted intercept is influenced by other sites leading to a process called 'shrinkage'. \n\nWhy are these called predictions and not estimates? Because we have estimated the variance at each site and from here essentially borrowed information across sites to improve the accuracy, to combine with the fixed effects. So in the strictest sense we are *predicting* relationships rather than through direct observation.\n\nThis generous ability to make predictions is one of the main advantages of a mixed-model. \n\nThe `summary()` function has already provided the estimates of the fixed effects, but they can also be extracted with the `fixef()` function. \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfixef(mixed_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)           x \n  23.269187    2.027066 \n```\n\n\n:::\n:::\n\n\nWe can also apply `anova()` to a single model to get an F-test for the fixed effect\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nanova(mixed_model)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|   |   Sum Sq|  Mean Sq| NumDF|    DenDF|  F value| Pr(>F)|\n|:--|--------:|--------:|-----:|--------:|--------:|------:|\n|x  | 14303.23| 14303.23|     1| 424.0815| 141.6089|      0|\n\n</div>\n:::\n:::\n\n\n\n### Shrinkage in mixed models\n\nThe graph below demonstrates the compromise between complete pooling and no pooling. It plots the overall regression line/mean (the fixed effects from the `lmer` model), the predicted slopes at each site from the mixed-effects model, and compares this to the estimates from each site (nested lm).  \n\nAs you can see most of the groups show shrinkage, that is they deviate less from the overall mean, most obviously in group 5, where the sample size is deliberately reduced. Here you can see the predicted line is much closer to the overall regression line, reflecting the greater uncertainty. The slope is drawn towards the overall mean by shrinkage. \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Nesting the data by group\nnested_data <- data |>  \n    group_by(group) |>  \n    nest()\n\n# Fitting linear regression models and obtaining predictions for each group\nnested_models <- map(nested_data$data, ~ lm(y ~ x, data = .)) |>  \n    map(predict)\n```\n:::\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Creating a new dataframe and adding predictions from different models\ndata1 <- data |>  \n  mutate(fit.m = predict(mixed_model, re.form = NA),\n         fit.c = predict(mixed_model, re.form = NULL)) |>  \n  arrange(group,obs) |>  \n  mutate(fit.l = unlist(nested_models)) \n\n# Creating a plot to visualize the predictions\ndata1 |>  \n  ggplot(aes(x = x, y = y, colour = group)) +\n    geom_point(pch = 16) + \n  geom_line(aes(y = fit.l, linetype = \"lm\"), colour = \"black\")+\n  geom_line(aes(y = fit.c, linetype = \"lmer\"))+ \n  geom_line(aes(y = fit.m, linetype = \"Mean\"), colour = \"grey\")+\n   scale_linetype_manual(name = \"Model Type\", \n                        labels = c(\"Mean\", \"lmer\", \"lm\"),\n                        values = c(\"dotdash\", \"solid\", \"dashed\"))+\n  facet_wrap( ~ group)+\n  guides(colour = \"none\")\n```\n\n::: {.cell-output-display}\n![Regression relationships from fixed-effects and mixed effects models, note shrinkage in group 5](mixed-model_files/figure-html/unnamed-chunk-25-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n`re.form = NA`: When re.form is set to NA, it indicates that the random effects should be ignored during prediction. This means that the prediction will be based solely on the fixed effects of the model, ignoring the variation introduced by the random effects. This is useful when you are interested in estimating the overall trend or relationship described by the fixed effects, without considering the specific random effects of individual groups or levels.\n\n`re.form = NULL`: Conversely, when re.form is set to NULL, it indicates that the random effects should be included in the prediction. This means that the prediction will take into account both the fixed effects and the random effects associated with the levels of the random effect variable. The model will use the estimated random effects to generate predictions that account for the variation introduced by the random effects. This is useful when you want to visualize and analyze the variation in the response variable explained by different levels of the random effect.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\nIt's not always easy/straightforward to make prediciton or confidence intervals from complex general and generalized linear mixed models, luckily there are some excellent R packages that will do this for us. \n\n### `ggeffects`\n\n`ggeffects` (@R-ggeffects) is a light-weight package that aims at easily calculating marginal effects and adjusted predictions\n\n#### `ggpredict`\n\nThe argument `type = random` in the `ggpredict` function (from the ggeffects package @R-ggeffects) is used to specify the type of predictions to be generated in the context of mixed effects models. The main difference between using `ggpredict` with and without `type = random` lies in the type of predictions produced:\n\nWithout `type = random`: `ggpredict` will generate **fixed-effects predictions**. These estimates are based solely on the fixed effects of the model, ignoring any variability associated with the random effects. The resulting estimate represent the average or expected values of the response variable for specific combinations of predictor values, considering only the fixed components of the model.\n\nEstimated mean fixed effects provide a comprehensive view of the average effect of dependent variables on the response variable. By plotting the estimated mean fixed effects using ggpredict, you can visualize how the response variable changes across different levels or values of the predictors while considering the effects of other variables in the model.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(ggeffects)\n\nggpredict(mixed_model, terms = \"x\") |>  \nplot(x = _, show_data = TRUE)\n```\n\n::: {.cell-output-display}\n![](mixed-model_files/figure-html/unnamed-chunk-27-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\nWith `type = random`: ggpredict will generate **predictions** that **incorporate both fixed and random effects**. These predictions take into account the variability introduced by the random effects in the model. The resulting predictions reflect not only the average trend captured by the fixed effects but also the additional variability associated with the random effects at different levels of the grouping factor(s). \n\nBy default the figure now produces **prediciton intervals**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggpredict(mixed_model, terms = c(\"x\", \"group\"), type = \"random\") |>  \nplot(x = _, show_data = TRUE)\n```\n\n::: {.cell-output-display}\n![](mixed-model_files/figure-html/unnamed-chunk-28-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\nFurthermore, `ggpredict()` enables you to explore group-level predictions, which provide a deeper understanding of how the response variable varies across different levels of the grouping variable. By specifying the desired grouping variable in ggpredict when `type = random`, you can generate plots that depict the predicted values for each group separately, allowing for a comparative analysis of group-level effects.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggpredict(mixed_model, terms = c(\"x\", \"group\"), type = \"random\") |>  \nplot(x = _, show_data = TRUE) + \n  facet_wrap(~group)+\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](mixed-model_files/figure-html/unnamed-chunk-29-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n### `sjPlot`\n\nAnother way to visualise mixed model results is with the package `sjPlot`(@R-sjPlot), and if you are interested in showing the variation among levels of your random effects, you can plot the departure from the overall model estimate for intercepts - *and slopes, if you have a random slope model*:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(sjPlot)\n\nplot_model(mixed_model, terms = c(\"x\", \"group\"), type = \"re\")/\n  (plot_model(mixed_model, terms = c(\"x\", \"group\"), type = \"est\")+ggtitle(\"Fixed Effects\"))\n```\n\n::: {.cell-output-display}\n![](mixed-model_files/figure-html/unnamed-chunk-30-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n:::{.callout-warning}\n\nThe values you see are NOT actual values, but rather the difference between the general intercept or slope value found in your model summary and the estimate for this specific level of random/fixed effect. \n\n:::\n\n\n`sjPlot` is also capable of producing prediction plots in the same way as `ggeffects`:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot_model(mixed_model,type=\"pred\",\n           terms=c(\"x\", \"group\"),\n           pred.type=\"re\",\n           show.data = T)+\n  facet_wrap( ~ group)\n```\n\n::: {.cell-output-display}\n![](mixed-model_files/figure-html/unnamed-chunk-31-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n\n\n## Advanced information on intervals\n\nUntil now we have used predict functions or emmeans to produce mean estimates and 95%CI, whichever methods we use we get the same results. Now however, we might see subtle differences depending on whether we use `ggemmeans`, `ggpredict` or `emmeans`. \n\nThese differences can be explained based on whether we are making our predictions based on:\n\n- Marginal or conditional variance\n\n- Calculated df\n\n- Confidence or prediction intervals\n\n### Marginal or conditional variance\n\nTry comparing the outputs from `ggpredict` and `ggemmeans`:\n\n::: {.panel-tabset}\n\n## ggpredict\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggpredict(mixed_model, terms = \"x\")\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|  x| predicted| std.error| conf.low| conf.high|group |\n|--:|---------:|---------:|--------:|---------:|:-----|\n|  0|  23.26919|  6.481821| 10.52885|  36.00952|1     |\n|  2|  27.32332|  6.446136| 14.65313|  39.99351|1     |\n|  4|  31.37745|  6.428332| 18.74225|  44.01265|1     |\n|  6|  35.43158|  6.428560| 22.79594|  48.06722|1     |\n|  8|  39.48571|  6.446816| 26.81418|  52.15724|1     |\n| 10|  43.53984|  6.482949| 30.79729|  56.28239|1     |\n\n</div>\n:::\n:::\n\n\n## ggemmeans\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggemmeans(mixed_model, terms = \"x\")\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|  x| predicted| std.error| conf.low| conf.high|group |\n|--:|---------:|---------:|--------:|---------:|:-----|\n|  0|  23.26919|  6.481821| 10.56505|  35.97332|1     |\n|  2|  27.32332|  6.446136| 14.68912|  39.95751|1     |\n|  4|  31.37745|  6.428332| 18.77815|  43.97675|1     |\n|  6|  35.43158|  6.428560| 22.83183|  48.03133|1     |\n|  8|  39.48571|  6.446816| 26.85018|  52.12124|1     |\n| 10|  43.53984|  6.482949| 30.83350|  56.24619|1     |\n\n</div>\n:::\n:::\n\n\n:::\n\nYou should see that the emmeans results produce narrower confidence intervals - there is some more information [here](https://www.andrewheiss.com/blog/2022/11/29/conditional-marginal-marginaleffects/#magnussons-data-and-model-the-effect-of-a-treatment-on-gambling-losses). But briefly `ggpredict` calculates conditional variance (what is the certainty of each particular point estimate) while `ggemmeans` uses marginal variance - the **average** uncertainty across all predictions. This second option usually shrinks variance. \n\n\n### Df approximations\n\nNow lets compare using `ggemmeans` and `emmeans` directly:\n\n::: {.panel-tabset}\n\n\n## ggemmeans\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggemmeans(mixed_model, terms = \"x\")\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|  x| predicted| std.error| conf.low| conf.high|group |\n|--:|---------:|---------:|--------:|---------:|:-----|\n|  0|  23.26919|  6.481821| 10.56505|  35.97332|1     |\n|  2|  27.32332|  6.446136| 14.68912|  39.95751|1     |\n|  4|  31.37745|  6.428332| 18.77815|  43.97675|1     |\n|  6|  35.43158|  6.428560| 22.83183|  48.03133|1     |\n|  8|  39.48571|  6.446816| 26.85018|  52.12124|1     |\n| 10|  43.53984|  6.482949| 30.83350|  56.24619|1     |\n\n</div>\n:::\n:::\n\n\n## emmeans\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nemmeans::emmeans(mixed_model, specs = \"x\", at = list(x = seq(0,10,2)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  x emmean   SE   df lower.CL upper.CL\n  0   23.3 6.48 4.14     5.51     41.0\n  2   27.3 6.45 4.05     9.51     45.1\n  4   31.4 6.43 4.01    13.54     49.2\n  6   35.4 6.43 4.01    17.59     53.3\n  8   39.5 6.45 4.05    21.68     57.3\n 10   43.5 6.48 4.14    25.78     61.3\n\nDegrees-of-freedom method: kenward-roger \nConfidence level used: 0.95 \n```\n\n\n:::\n:::\n\n\n:::\n\n\nIn mixed models, df are not straightforward because of:\n\n- The hierarchical structure (e.g., subjects nested in groups),\n\n- Random effects, which reduce the effective number of independent observations.\n\n\n| Method             | What it does                                   | Used by                              |\n| ------------------ | ---------------------------------------------- | ------------------------------------ |\n| **Satterthwaite**  | Estimates df based on uncertainty in SE        | `lmerTest`, `emmeans()`              |\n| **Kenward-Roger**  | More advanced, adjusts SE and df               | `emmeans()`                           |\n| **Asymptotic (∞)** | Assumes large sample, uses normal distribution | `lme4`, `ggpredict()`, `ggemmeans()` |\n\n\nWhen df is assumed to be essentially infinite (∞) - we default to the z-distribution, which will produce the narrowest confidence intervals.\n\n\n### Interval types\n\n\n#### Confidence Intervals:\n\nA confidence interval is used to estimate the range of plausible values for a population parameter, such as the mean or the regression coefficient, based on a sample from that population. It provides a range within which the true population parameter is likely to fall with a certain level of confidence. For example, a 95% confidence interval implies that if we were to repeat the sampling process many times, **95% of the resulting intervals would contain the true population mean**.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggpredict(mixed_model, terms = \"x\", interval = \"confidence\")\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|  x| predicted| std.error| conf.low| conf.high|group |\n|--:|---------:|---------:|--------:|---------:|:-----|\n|  0|  23.26919|  6.481821| 10.52885|  36.00952|1     |\n|  2|  27.32332|  6.446136| 14.65313|  39.99351|1     |\n|  4|  31.37745|  6.428332| 18.74225|  44.01265|1     |\n|  6|  35.43158|  6.428560| 22.79594|  48.06722|1     |\n|  8|  39.48571|  6.446816| 26.81418|  52.15724|1     |\n| 10|  43.53984|  6.482949| 30.79729|  56.28239|1     |\n\n</div>\n:::\n:::\n\n\n#### Prediction Intervals:\n\nOn the other hand, a prediction interval is used to estimate the range of plausible values for an individual observation or a future observation from the population. It takes into account both the uncertainty in the estimated model parameters and the inherent variability within the data. A 95% prediction interval provides a range **within which a specific observed or predicted value is likely to fall with a certain level of confidence**. The wider the prediction interval, the greater the uncertainty around the specific value being predicted.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggpredict(mixed_model, terms = \"x\", interval = \"prediction\")\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|  x| predicted| std.error|   conf.low| conf.high|group |\n|--:|---------:|---------:|----------:|---------:|:-----|\n|  0|  23.26919|  11.95906| -0.2369238|  46.77530|1     |\n|  2|  27.32332|  11.93976|  3.8551499|  50.79149|1     |\n|  4|  31.37745|  11.93015|  7.9281549|  54.82674|1     |\n|  6|  35.43158|  11.93028| 11.9820450|  58.88111|1     |\n|  8|  39.48571|  11.94012| 16.0168209|  62.95460|1     |\n| 10|  43.53984|  11.95967| 20.0325298|  67.04715|1     |\n\n</div>\n:::\n:::\n\n\n## Checking model assumptions\n\n\nWe need to be just as conscious of testing the assumptions of mixed effects models as we are with any other. The assumptions are:\n\n1. Within-group errors are independent and normally distributed with mean zero and variance $\\sigma^2$\n \n2. Within-group errors are independent of the random effects.\n\n3. Random effects are normally distributed with mean zero.\n\n4. Random effects are independent for different groups, except as specified by nesting (more on this later)\n\n\nSeveral model check plots would help us to confirm/deny these assumptions, but note that QQ-plots may not be relevant because of the model structure. Two commonly-used plots are:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot(mixed_model) \n```\n\n::: {.cell-output-display}\n![](mixed-model_files/figure-html/unnamed-chunk-38-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nqqnorm(resid(mixed_model))\nqqline(resid(mixed_model)) \n```\n\n::: {.cell-output-display}\n![](mixed-model_files/figure-html/unnamed-chunk-39-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\nIt can often be useful to check the distribution of residuals in each of the groups (e.g. blocks) to check assumptions 1 and 2. We can do this by plotting the residuals against the fitted values, separately for each level of the random effect, using the  `coplot()` function:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncoplot(resid(mixed_model) ~ fitted(mixed_model) | data$group)\n```\n\n::: {.cell-output-display}\n![](mixed-model_files/figure-html/unnamed-chunk-40-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\nEach sub-figure of this plot, which refers to an individual group, doesn’t contain much data. It can be hard to judge whether the spread of residuals around fitted values is the same for each group when observations are low.\n\nWe can check assumption 3 with a histogram (here the more levels we have, the more we can be assured):\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrand_dist <- as.data.frame(ranef(mixed_model)) |>  \n  mutate(group = grp,\n         b0_hat = condval,\n         intercept_cond = b0_hat + summary(mixed_model)$coef[1,1],\n         .keep = \"none\")\n\nhist(rand_dist$b0_hat)\n```\n\n::: {.cell-output-display}\n![](mixed-model_files/figure-html/unnamed-chunk-41-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\nOverlaying the random distribution of our intercept over the regression line produces a plot like the below: \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndata1 |> \n  ggplot(aes(x = x, y = y)) +\n  geom_point(pch = 16, col = \"grey\") +\n  geom_violinhalf(data = rand_dist, \n                  aes(x = 0, y = intercept_cond), \n                  trim = FALSE, \n                  width = 4, \n                  adjust = 2, \n                  fill = NA)+\n  geom_line(aes(y = fit.m), linewidth = 2)  +\n  coord_cartesian(ylim = c(-40, 100))+\n  labs(x = \"Independent Variable\", \n       y = \"Dependent Variable\")\n```\n\n::: {.cell-output-display}\n![Marginal fit, heavy black line from the random effect model with a histogram of the of the distribution of conditional intercepts](mixed-model_files/figure-html/unnamed-chunk-42-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n### performance\n\nThe `check_model()` function from the performance package in R is a useful tool for evaluating the performance and assumptions of a statistical model, particularly in the context of mixed models. It provides a comprehensive set of diagnostics and visualizations to assess the model's fit, identify potential issues, and verify the assumptions underlying the model, which can be difficult with complex models\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(performance)\ncheck_model(mixed_model)\n```\n\n::: {.cell-output-display}\n![](mixed-model_files/figure-html/unnamed-chunk-43-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n### DHARma\n\nSimulation-based methods, like those available with DHARMa (@R-DHARMa), are often preferred for model validation and assumption checking because they offer flexibility and do not rely on specific assumptions. Simulation is particularly useful for evaluating complex models with multiple levels of variability, non-linearity, or complex hierarchical structures. Such models may not be adequately evaluated by solely examining residuals, and simulation provides a more robust approach to assess their assumptions and performance.\n\nRead the authors summary [here](https://theoreticalecology.wordpress.com/2016/08/28/dharma-an-r-package-for-residual-diagnostics-of-glmms/)\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(DHARMa)\n\nresid.mm <- simulateResiduals(mixed_model)\n\nplot(resid.mm)\n```\n\n::: {.cell-output-display}\n![](mixed-model_files/figure-html/unnamed-chunk-44-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n:::{.callout-warning}\n\nWhen you have a lot of data, even minimal deviations from the expected distribution will become significant (this is discussed in the help/vignette for the DHARMa package). You will need to assess the distribution and decide if it is important for yourself.\n\n:::\n\n\n\n## Practice Questions\n\n1. In mixed-effects models, independent variables are also called: \n\n<select class='webex-select'><option value='blank'></option><option value=''>Random Effects</option><option value='answer'>Fixed Effects</option><option value=''>Mediators</option><option value=''>Variance</option></select>\n\n2. A random effect is best described as?\n\n<div class='webex-radiogroup' id='radio_AVDVAHGRRG'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_AVDVAHGRRG\" value=\"\"></input> <span>A variable that is noisier than other variables</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_AVDVAHGRRG\" value=\"\"></input> <span>An effect that cannot be predicted based on group membership</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_AVDVAHGRRG\" value=\"answer\"></input> <span>A variable where subgroups influence the outcome</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_AVDVAHGRRG\" value=\"\"></input> <span>Choosing slope values with a random number generator</span></label></div>\n\n\n3. Which of the following is **not** an advantage of mixed-effects models?\n\n<div class='webex-radiogroup' id='radio_ZVVSOMCMUY'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_ZVVSOMCMUY\" value=\"\"></input> <span>They can cope with situations where individuals contribute different numbers of observations</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_ZVVSOMCMUY\" value=\"\"></input> <span>They can handle group-level differences in the outcome</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_ZVVSOMCMUY\" value=\"\"></input> <span>They can deal with variation due to different groups</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_ZVVSOMCMUY\" value=\"answer\"></input> <span>They are guaranteed to give significant results when ANOVAs do not</span></label></div>\n\n\n4. Mixed-effects models cope well with missing data because?\n\n<div class='webex-radiogroup' id='radio_FXDDCXESDJ'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_FXDDCXESDJ\" value=\"answer\"></input> <span>They can still estimate parameters even when some observations are missing</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_FXDDCXESDJ\" value=\"\"></input> <span>They delete observations with missing data</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_FXDDCXESDJ\" value=\"\"></input> <span>They set all values to 0</span></label></div>\n\n\n\n# Worked Example 1 - Dolphins\n\n\n## How do I decide if it is a fixed or random effect?\n\nOne of the most common questions in mixed-effects modelling is how to decide if an effect should be considered as fixed or random. This can be quite a complicated question, as we have touched upon briefly before the definition of a random effect is not universal. It is a considered process that can include the hypothesis or question you are asking. \n\n1 ) Are you directly interested in the effect in question. If the answer is yes it should be a fixed effect.\n\n2 ) Is the variable continuous? If the answer is yes it should be a fixed effect.\n\n3 ) Does the variable have less than five levels? If ther answer is yes it should be a fixed effect.\n\n\n## Dolphins\n\nThis dataset was collected to measure resting lung function in 32 bottlenose dolphins. The main dependent variable was the tidal volume ($V_T$) measured in litres, as an index of lung capacity. \n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<a href=\"https://raw.githubusercontent.com/UEABIO/intro-mixed-models/main/book/files/dolphins.csv\">\n<button class=\"btn btn-success\"><i class=\"fa fa-save\"></i> Download Dolphins data</button>\n</a>\n```\n\n:::\n:::\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndolphins <- read_csv(\"files/dolphins.csv\") \n\ndolphins$direction <- factor(dolphins$direction)\n\ndolphins <- drop_na(dolphins)\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\nHere we are interested in the relationship between ($V_T$) and body mass (kg), we have measurements which are taken on the breath *in* and the breath *out*, and each dolphin has been observed between one and four times.\n\nWe need to determine our fixed effects, random effects and model structure:\n\n1) Body Mass <select class='webex-select'><option value='blank'></option><option value=''>Random Effect</option><option value='answer'>Fixed Effect</option></select>\n\n2) Direction <select class='webex-select'><option value='blank'></option><option value=''>Random Effect</option><option value='answer'>Fixed Effect</option></select>\n\n3) Animal 1) Body Mass <select class='webex-select'><option value='blank'></option><option value='answer'>Random Effect</option><option value=''>Fixed Effect</option></select>\n\n4) With the basic structure `y ~ x + z + (1|group)` what do you think this model should be?:\n\n<input class='webex-solveme nospaces' size='20' data-answer='[\"vt ~ bodymass + direction + (1|animal)\",\"vt ~  direction + bodymass + (1|animal)\"]'/>\n\n\n<div class='webex-solution'><button>Solution</button>\n\n\n1) We are clearly interested in the effect of body mass on ($V_T$) so this is a **fixed effect**.\n\n2) We may think that the relationship with ($V_T$) and body mass may be different on the in and out breath. We may not be *directly* interested in this, but it has fewer than fivel levels so this is a **fixed effect**. (outbreath coded as 1, inbreath coded as 2).\n\n3) Individual dolphins - if we averaged across measurements for each dolphin, our measurement precision would be different for each animal. If we include each data point, we would be double-counting some animals and our observations would not be independent. To account for the multiple observations we should treat animal as a **random effect**.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndolphmod <- lmer(vt ~ bodymass + direction + (1|animal), data=dolphins)\n```\n:::\n\n\n\n</div>\n\n\n\nWith our basic linear model in place - we should carry out model fit checks with `DHARMa` or `performance::check_model()`, but assuming this is a good fit we can look at interpretation:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(dolphmod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML. t-tests use Satterthwaite's method [\nlmerModLmerTest]\nFormula: vt ~ bodymass + direction + (1 | animal)\n   Data: dolphins\n\nREML criterion at convergence: 387.4\n\nScaled residuals: \n     Min       1Q   Median       3Q      Max \n-2.30795 -0.51983  0.04156  0.62404  2.26396 \n\nRandom effects:\n Groups   Name        Variance Std.Dev.\n animal   (Intercept) 1.039    1.019   \n Residual             1.158    1.076   \nNumber of obs: 112, groups:  animal, 31\n\nFixed effects:\n             Estimate Std. Error        df t value Pr(>|t|)    \n(Intercept)  2.226398   0.627115 28.758081   3.550  0.00135 ** \nbodymass     0.016782   0.003259 26.720390   5.150  2.1e-05 ***\ndirection2   1.114821   0.203389 77.414421   5.481  5.1e-07 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nCorrelation of Fixed Effects:\n           (Intr) bdymss\nbodymass   -0.927       \ndirection2 -0.162  0.000\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndolphins.1 <- dolphins |>  \n    mutate(fit.m = predict(dolphmod, re.form = NA),\n           fit.c = predict(dolphmod, re.form = NULL))\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndolphins.1 |> \n  ggplot(aes(x = bodymass, y = vt, group = direction)) +\n  geom_point(pch = 16, aes(colour = direction)) +\n  geom_line(aes(y = fit.m, \n                linetype = direction), \n            linewidth = 1)  +\n  labs(x = \"Body Mass\", \n       y = \"VT\") \n```\n\n::: {.cell-output-display}\n![Scatter plot of VT as a function of body mass for dolphins. Different directions of breath are represented by different colors. The solid lines indicate the marginal fitted values from our model.](mixed-model_files/figure-html/unnamed-chunk-51-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot_model(dolphmod,type=\"pred\",\n           terms=c(\"bodymass\", \"direction\"),\n           pred.type=\"fe\",\n           show.data = T)\n```\n\n::: {.cell-output-display}\n![](mixed-model_files/figure-html/unnamed-chunk-52-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n\n<div class='webex-solution'><button>A brief summary</button>\n\n\nWe fitted a linear mixed model (estimated using REML and nloptwrap optimizer) to predict ($V_T$) with bodymass(kg) and direction (in/out breath). 95% Confidence Intervals (CIs) and p-values were computed using a Wald t-distribution approximation. We included a random intercept effect of animal to account for repeated measurements (of between 1 to 4 observations) across a total of 32 bottlenosed dolphins. \n\nWe found that for every 1kg increase in bodymass, ($V_T$) increased by 0.02 litres (95% CI [0.01 - 0.02]), . The inbreath had on average a higher volume than the outbreath (1.11 litre difference [0.71 - 1.52]..\n\n**Q.** This is not a perfect write-up, what else could we consider including?\n\n\n</div>\n\n\n\n\n# Multiple random effects\n\nPreviously we used `(1|group)` to fit our random effect. Whatever is on the right side of the `|` operator is a factor and referred to as a “grouping factor” for the term. \n\n### Crossed or Nested\n\nWhen we have more than one possible random effect these can be **crossed** or **nested** - it depends on the relationship between the variables. Let’s have a look.\n\nA common issue that causes confusion is this issue of specifying random effects as either  ‘crossed’ or ‘nested’. In reality, the way you specify your random effects will be determined  by your experimental or sampling design. A simple  example can illustrate the difference. \n\n#### 1. Crossed Random Effects:\n\nCrossed random effects occur when the levels of two or more grouping variables are crossed or independent of each other. In this case, the grouping variables are unrelated, and each combination of levels is represented in the data.\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"grViz html-widget html-fill-item-overflow-hidden html-fill-item\" id=\"htmlwidget-1dd1551a06de9eda58cd\" style=\"width:100%;height:480px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-1dd1551a06de9eda58cd\">{\"x\":{\"diagram\":\"\\ndigraph boxes_and_circles {\\n\\n  # a \\\"graph\\\" statement\\n  graph [overlap = true, fontsize = 10]\\n\\n  # several \\\"node\\\" statements\\n  node [shape = box,\\n        fontname = Helvetica]\\n  I; II; 1; 2; 3\\n\\n  # several \\\"edge\\\" statements\\n  I->1 I ->2 I ->3\\n  II ->1  II ->2 II ->3\\n}\\n\",\"config\":{\"engine\":\"dot\",\"options\":null}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n\nFully Crossed\n:::\n:::\n\n\n> Example 1: Let's consider a study examining the academic performance of students from different schools and different cities. The grouping variables are \"School\" and \"City\". Each school can be located in multiple cities, and each city can have multiple schools. The random effects of \"School\" and \"City\" are crossed since the levels of these variables are independent of each other.\n\n`lmer(y ~ x + (1 | School) + (1 | City), data = dataset)`\n\n\n> Example 2: Imagine there is a long-term study on breeding success in passerine birds across multiple woodlands, and the researcher returns every year for five  years to carry out measurements. Here  \"Year\" is a  crossed  random  effect with \"Woodland\" as each Woodland can appear in multiple years of study.\nImagine a researcher was interested in understanding  the factors affecting the clutch mass of a passerine bird. They have a study population  spread across five separate woodlands, each containing 30 nest boxes. Every week during  breeding they measure the foraging rate of females at feeders, and measure their  subsequent clutch mass. Some females have multiple clutches in a season and contribute multiple data points. \n\n`lmer(y ~ x + (1 | Year) + (1 | Woodland), data = dataset)`\n\n#### 2. Nested Random Effects:\n\nNested random effects occur when the levels of one grouping variable are completely nested within the levels of another grouping variable. In other words, the levels of one variable are uniquely and exclusively associated with specific levels of another variable.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"grViz html-widget html-fill-item-overflow-hidden html-fill-item\" id=\"htmlwidget-6c8b9398b6097a79d72f\" style=\"width:100%;height:480px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-6c8b9398b6097a79d72f\">{\"x\":{\"diagram\":\"\\ndigraph boxes_and_circles {\\n\\n  # a \\\"graph\\\" statement\\n  graph [overlap = true, fontsize = 10]\\n\\n  # several \\\"node\\\" statements\\n  node [shape = box,\\n        fontname = Helvetica]\\n  I; II; 1; 2; 3; 4; 5; 6\\n\\n  # several \\\"edge\\\" statements\\n  I->1 I ->2 I ->3\\n  II ->4  II ->5 II ->6\\n}\\n\",\"config\":{\"engine\":\"dot\",\"options\":null}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n\nFully Nested\n:::\n:::\n\n\n> Example 1. Consider a study on the job performance of employees within different departments of an organization. The grouping variables are \"Employee\" and \"Department\". Each employee belongs to one specific department, and no employee can be part of multiple departments. The random effects of \"Employee\" are nested within the random effects of \"Department\" since each employee is uniquely associated with a specific department.\n\n`lmer(y ~ x + (1 | Department/Employee), data = dataset)`\n\n> Example 2: In the same bird study female ID is said to be  nested within woodland : each woodland  contains multiple females unique to that woodland (that never move among woodlands).  The nested random effect controls for the fact that (i) clutches from the same female  are not independent, and (ii) females from the same woodland may have clutch masses  more similar to one another than to females from other woodlands \n\n`lmer(y ~ x + (1 | Woodland/Female ID), data = dataset)`\n\n*or if we remember year we have a model with both crossed and nested random effects*\n\n`lmer(y ~ x + (1 | Woodland/Female ID) + (1|Year), data = dataset)`\n\n\nFor more on designing models around crossed and nested designs check out [this amazing nature paper](https://www.nature.com/articles/nmeth.3137) @krzywinski_2014\n\n\n# Worked Example 2 - Nested design\n\nThis experiment involved a simple one-way anova with 3 treatments given to 6 rats, the researchers the measured glycogen levels in their liver. The analysis was complicated by the fact that three preparations were taken from the liver of each rat, and two readings of glycogen content were taken from each preparation. This generated 6 pseudoreplicates per rat to give a total of 36 readings in all.\n\nClearly, it would be a mistake to analyse these data as if they were a straightforward one-way anova, because that would give us 33 degrees of freedom for error. In fact, since there are only two rats in each treatment, we have only one degree of freedom per treatment, giving a total of 3 d.f. for error.\n\nThe variance is likely to be different at each level of this nested analysis because:\n\nthe readings differ because of variation in the glycogen detection method within each liver sample (measurement error);\nthe pieces of liver may differ because of heterogeneity in the distribution of glycogen within the liver of a single rat;\nthe rats will differ from one another in their glycogen levels because of sex, age, size, genotype, etc.;\nrats allocated different experimental treatments may differ as a result of the fixed effects of treatment.\nIf all we want to test is whether the experimental treatments have affected the glycogen levels, then we are not interested in liver bits within rat’s livers, or in preparations within liver bits. We could combine all the pseudoreplicates together, and analyse the 6 averages. This would have the virtue of showing what a tiny experiment this really was. This latter approach also ignores the nested sources of uncertainties. Instead we will use a linear mixed model.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<a href=\"https://raw.githubusercontent.com/UEABIO/intro-mixed-models/main/book/files/rats.rds\">\n<button class=\"btn btn-success\"><i class=\"fa fa-save\"></i> Download as rds</button>\n</a>\n```\n\n:::\n:::\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrats <- readRDS(\"rats.rds\")\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrats |>  \n  aggregate(Glycogen ~ Rat + Treatment + Liver, data = _, mean)\n```\n:::\n\n\n```\n   Glycogen Rat Treatment Liver\n1       131   1         1     1\n2       130   1         1     1\n3       131   1         1     2\n4       125   1         1     2\n5       136   1         1     3\n6       142   1         1     3\n7       150   2         1     1\n8       148   2         1     1\n9       140   2         1     2\n10      143   2         1     2\n11      160   2         1     3\n12      150   2         1     3\n13      157   3         2     1\n14      145   3         2     1\n15      154   3         2     2\n16      142   3         2     2\n17      147   3         2     3\n18      153   3         2     3\n19      151   4         2     1\n20      155   4         2     1\n21      147   4         2     2\n22      147   4         2     2\n23      162   4         2     3\n24      152   4         2     3\n25      134   5         3     1\n26      125   5         3     1\n27      138   5         3     2\n28      138   5         3     2\n29      135   5         3     3\n30      136   5         3     3\n31      138   6         3     1\n32      140   6         3     1\n33      139   6         3     2\n34      138   6         3     2\n35      134   6         3     3\n36      127   6         3     3\n\n```\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrats_lmer.1 <- lmer(Glycogen ~ Treatment + (1 | Rat) + (1 | Liver), data = rats)\nsummary(rats_lmer.1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML. t-tests use Satterthwaite's method [\nlmerModLmerTest]\nFormula: Glycogen ~ Treatment + (1 | Rat) + (1 | Liver)\n   Data: rats\n\nREML criterion at convergence: 221.9\n\nScaled residuals: \n     Min       1Q   Median       3Q      Max \n-1.79334 -0.66536  0.01792  0.59281  2.05206 \n\nRandom effects:\n Groups   Name        Variance Std.Dev.\n Rat      (Intercept) 39.187   6.260   \n Liver    (Intercept)  2.168   1.472   \n Residual             30.766   5.547   \nNumber of obs: 36, groups:  Rat, 6; Liver, 3\n\nFixed effects:\n            Estimate Std. Error      df t value Pr(>|t|)    \n(Intercept)  140.500      4.783   3.174  29.373 5.65e-05 ***\nTreatment2    10.500      6.657   3.000   1.577    0.213    \nTreatment3    -5.333      6.657   3.000  -0.801    0.482    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nCorrelation of Fixed Effects:\n           (Intr) Trtmn2\nTreatment2 -0.696       \nTreatment3 -0.696  0.500\n```\n\n\n:::\n:::\n\n\n**Q. Why is this model above wrong**\n\n\n<div class='webex-solution'><button>Solution</button>\n\n\nIt is wrong because this would add two random effect terms, one for rat 1 and one for rat 2. In fact there are 6 rats altogether. The way that the data have been coded allows for these kinds of mistakes to happen. The same is true for Liver, which is coded as a 1, 2 or 3. This means that we could write this thinking that we are including the correct random effects for Rat and Liver. In fact, this assumes that the data come from a crossed design, in which there are 2 rats and 3 parts of the liver, and that Liver = 1 corresponds to the same type of measurement in rats 1 and 2 and so on. Sometimes this is appropriate, but not here!\n\nThe nature of the way that many data sets are coded makes these kinds of mistakes very easy to make!\n\n\n</div>\n\n\n\nA better design is the one below:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrats_lmer.2 <- lmer(Glycogen ~ Treatment + (1 | Rat / Liver), data = rats)\nsummary(rats_lmer.2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML. t-tests use Satterthwaite's method [\nlmerModLmerTest]\nFormula: Glycogen ~ Treatment + (1 | Rat/Liver)\n   Data: rats\n\nREML criterion at convergence: 219.6\n\nScaled residuals: \n     Min       1Q   Median       3Q      Max \n-1.48212 -0.47263  0.03062  0.42934  1.82935 \n\nRandom effects:\n Groups    Name        Variance Std.Dev.\n Liver:Rat (Intercept) 14.17    3.764   \n Rat       (Intercept) 36.06    6.005   \n Residual              21.17    4.601   \nNumber of obs: 36, groups:  Liver:Rat, 18; Rat, 6\n\nFixed effects:\n            Estimate Std. Error      df t value Pr(>|t|)    \n(Intercept)  140.500      4.707   3.000  29.848 8.26e-05 ***\nTreatment2    10.500      6.657   3.000   1.577    0.213    \nTreatment3    -5.333      6.657   3.000  -0.801    0.482    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nCorrelation of Fixed Effects:\n           (Intr) Trtmn2\nTreatment2 -0.707       \nTreatment3 -0.707  0.500\n```\n\n\n:::\n:::\n\n\nAnd we can see the effects in the figures below:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot(ggpredict(rats_lmer.2, terms = c(\"Treatment\")))\n```\n\n::: {.cell-output-display}\n![](mixed-model_files/figure-html/unnamed-chunk-61-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot(ggpredict(rats_lmer.2, \n               terms = c(\"Treatment\", \"Rat\"), \n               type = \"random\"), \n     show_data = TRUE)\n```\n\n::: {.cell-output-display}\n![](mixed-model_files/figure-html/unnamed-chunk-62-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n# Types of Random Effects\n\n## Random slopes\n\nSo far we have looked at random effects where each group has its own *intercept*. This means that we fit a regression line across all five groups, which has a constant slope but is allowed to shift up or down for each group. This is what is represented in panel B. \n\nAn alternative to the random intercepts model is the *random slopes* model, shown in panel C. In this model the slopes are permitted to vary, but the intercept is fixed across all groups. For our current data the random slopes model does a fair job as well. \n\nFinally we can allow *both the intercepts and slope* to vary between groups, as shown in panel D. This captures both the shallower slope of some of our groups and the vertical offsets present. If you inspect the original data set we generated, you can see that the random effect for group was calculated as both a product of random distribution on the intercept and slope, so it is not surprising that here this model fits the data best. \n\nThis model will use more degrees of freedom than the other two, as these must be used to calculate variance for both intercept and slope.\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](mixed-model_files/figure-html/unnamed-chunk-64-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# random intercept model\nlmer1 <- lmer(y ~ x + (1|group), data = data)\n\nplot_function(lmer1, \"Random intercept\")\n\n# Random slope model\n\nlmer2 <- lmer(y ~ x + (0 + x | group), data = data)\n\nplot_function(lmer2, \"Random slope\")\n\n# Random slope and intercept model\n\nlmer3 <- lmer(y ~ x + (x | group), data = data)\n```\n:::\n\n\nMixed-effects models are enormously flexible. The decision about whether to include random intercepts, random slopes, or both will depend heavily on your hypotheses. It is generally quite rare to see random slopes models only, and more commonly it will be a question of whether random intercepts or random intercepts *and* random slopes are necessary. \n\nAs the combine random slopes and intercept model requries more degrees of freedom, it may be the case that using likelihood ratio tests (LRT) are advisable to decide which model describes the data best (more on this later). \n\nBecause random intercepts models require fewer degrees of freedome, these may be easier to fit when data sets have fewer observations.\n\n\n:::{.callout-note}\n\nIn a random effects model, the random effects are assumed to be a random sample from a population of possible random effects. These random effects capture the variation between different groups or clusters in the data. The number of random effects is typically smaller than the total number of observations, as the random effects represent the distinct groups or clusters in the dataset.\n\nThe degrees of freedom associated with the random effects in a linear mixed model reflect the number of independent groups or clusters in the data, rather than the number of individual observations. For example, if you have data from 100 individuals, but they belong to only 10 distinct groups, the random effects would have 10 degrees of freedom, not 100.\n\nBy using fewer degrees of freedom for the random effects, the model accounts for the fact that the group-level variation is estimated based on a smaller number of parameters. This approach helps prevent overfitting and provides a more appropriate estimation of the variance components associated with the random effects.\n\n:::\n\n\n\n\n## Model refining / Likelihood Ratio Tests\n\nOnce we have produce an initial model with a random effects structure, we may wish to perform model selection by comparing different nested models with varying random effects structures. It allows us to assess whether the inclusion of additional random effects or changes in the random effects structure significantly improve the model fit. By comparing the likelihood values of different nested models, we can determine which model provides a better fit to the data.\n\nPreviously we looked at the random intercepts vs. random intercepts *and* slopes model and concluded that the latter looked like it fit the data best. \n\nWe can use a likelihood ratio test with the `anova()` function if we want to determine if the fit is significantly different to the simpler randome intercepts only model. \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nanova(lmer1, lmer3)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|      | npar|      AIC|      BIC|    logLik| deviance|    Chisq| Df| Pr(>Chisq)|\n|:-----|----:|--------:|--------:|---------:|--------:|--------:|--:|----------:|\n|lmer1 |    4| 3236.091| 3252.347| -1614.046| 3228.091|       NA| NA|         NA|\n|lmer3 |    6| 3228.442| 3252.825| -1608.221| 3216.442| 11.64947|  2|  0.0029536|\n\n</div>\n:::\n:::\n\n\n\n:::{.callout-warning}\n\nThere is a literature on the idea of model selection, that is, an automated (or sometimes manual) way of testing many versions of a model with a different subset of the predictors in an attempt to find the model that fits best. These are sometimes called “stepwise” procedures.\n\nOthers argue this method has a number of flaws, including: \n\n- Doing this is basically “p-value mining”, that is, running a lot of tests till you find a p-value you like.\n\n- Your likelihood of making a false positive is very high.\n\n- Adding/removing a new variable can have an effect on other predictors.\n\nInstead of doing model selection, you should use your knowledge of the data to select a subset of the variables which are either a) of importance to you, or b) theoretically influential on the outcome. Then you can fit a single model including all of this. \n\nHowever, I would argue that while the inclusion of random effects and their structure should have a clear rationale before implementation, adjustments to better understand the best type of random effects structure is perfectly reasonable. \n\n:::\n\n\n\n<div class='webex-solution'><button>ML vs. REML</button>\n\n\n### Maximum Likelihood\n\nFrequentist fit used by LMM through lme4 / lmer is based on the **Maximum Likelihood principle**, where we maximize the likelihood $L(y)$ of observing the data $y$, which is equivalent to minimizing residuals of the model, the Ordinary Least Squares (OLS) approach.  It measures the probability of observing the data given a specific set of parameter values. \n\nWhen we are attempting to optimise a model we can use the likelihood ratio test (LRT). Given two nested models, denoted as Model 1 and Model 2, the LRT compares the likelihood values of these models to assess whether the more complex Model 2 provides a significantly better fit to the data compared to the simpler Model 1. The LRT statistic, denoted as $D$, is calculated as the difference between the log-likelihood values of Model 1 and Model 2, multiplied by 2:\n\n$$D = -2~*~(ln(L_1)-ln(L_2))$$\n\nHere $L_1$ represents the likelihood value of Model 1, and $L_2$ represents the likelihood value of Model 2. **The LRT statistic follows a chi-square ($\\chi^2$) distribution** with degrees of freedom equal to the difference in the number of parameters between the two models.\n\nTo determine the statistical significance of the LRT statistic, one can compare it to the critical value from the chi-square distribution with the appropriate degrees of freedom. If the LRT statistic exceeds the critical value, it indicates that the more complex Model 2 provides a significantly better fit to the data compared to the simpler Model 1.\n\nML estimation is often used to perform hypothesis tests, including the chi-square test. The chi-square test compares the observed data to the expected data predicted by a statistical model. It assesses the goodness-of-fit between the observed data and the model's predictions.\n\n### REML\n\nREML (Restricted Maximum Likelihood) estimation is a variant of ML estimation that addresses the issue of bias in the estimation of random effects in mixed effects models. In mixed effects models, random effects account for the variation at the group or individual level that is not explained by the fixed effects. However, the inclusion of random effects introduces a bias in the ML estimates, as they are influenced by the variability of the random effects. \n\nREML estimation addresses this bias by optimizing the likelihood function conditional on the fixed effects only, effectively removing the influence of the random effects on the estimation. This approach provides unbiased estimates of the fixed effects and is especially useful when the primary interest lies in the fixed effects rather than the random effects.\n\n### ML vs. REML fitting\n\n**Maximum Likelihood (ML) estimation is preferable when comparing nested models** because it allows for the direct comparison of the likelihood values between different models. ML estimation provides a quantitative measure of how well a given model fits the observed data, based on the likelihood function.\n\nIn this context, ML estimation is preferable because it allows for a formal statistical comparison between nested models. It provides a rigorous and objective way to assess whether the inclusion of additional parameters in the more complex model leads to a significantly better fit to the data compared to the simpler model. This approach ensures that model comparisons are based on sound statistical principles and helps in determining the most appropriate model for the given data.\n\n**REML can be preferable when producing unbiased estimates of the fixed effects**. Older versions of model fitting packages like `lmer` used to require the manual switch between REML and ML when fitting models in order to switch between the objectives of assessing goodness-of-fit and interpreting estimates. But you will notice that when you perform an LRT with the `anova()` function it informs you the switch is being made automatically. \n\n\n</div>\n\n\n\n## Practice Questions\n\n1. The formula `y ~ x + (x|group)` would fit a model with \n<div class='webex-radiogroup' id='radio_VGYNMLTYWJ'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_VGYNMLTYWJ\" value=\"\"></input> <span>Random Slopes</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_VGYNMLTYWJ\" value=\"\"></input> <span>Random Intercepts</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_VGYNMLTYWJ\" value=\"answer\"></input> <span>Random Slopes and Intercepts</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_VGYNMLTYWJ\" value=\"\"></input> <span>An intercept fixed at 0</span></label></div>\n\n\n2. Which formula would fit a random intercepts model?\n<div class='webex-radiogroup' id='radio_ZXPUNUXSTV'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_ZXPUNUXSTV\" value=\"\"></input> <span>y ~ x + (x|group)</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_ZXPUNUXSTV\" value=\"answer\"></input> <span>y ~ x + (1|group)</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_ZXPUNUXSTV\" value=\"\"></input> <span>y ~ x + (y | group)</span></label></div>\n\n\n\n# Worked Example 3 - Sleep study\n\nIn this chapter, we'll be working with some real data from a study looking at the effects of sleep deprivation on psychomotor performance @belenky_2003. The dataset `sleepstudy` is built-in to the lme4 package. \n\nAccess the documentation by typing `??sleepstudy` in the console\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\nA good way to start every analysis is to plot the data.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(sleepstudy, aes(x = Days, y = Reaction)) +\n  geom_point() +\n  scale_x_continuous(breaks = 0:9) +\n  facet_wrap(~Subject)\n```\n\n::: {.cell-output-display}\n![](mixed-model_files/figure-html/unnamed-chunk-68-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\nTo model the data appropriately, first we need to know more about about the design - according to the study this went as follows:\n\n>The first 3 days (T1, T2 and B) were adaptation and training (T1 and T2) and baseline (B) and subjects were required to be in bed from 23:00 to 07:00 h [8 h required time in bed (TIB)]. On the third day (B), baseline measures were taken. Beginning on the fourth day and continuing for a total of 7 days (E1–E7) subjects were in one of four sleep conditions [9 h required TIB (22:00–07:00 h), 7 h required TIB (24:00–07:00 h), 5 h required TIB (02:00–07:00 h), or 3 h required TIB (04:00–07:00 h)], effectively one sleep augmentation condition, and three sleep restriction conditions.\n\nThere were seven nights of sleep restriction, with the first night of restriction occurring after the third day. The first two days, coded as 0, 1, were adaptation and training. The day coded as 2, where the baseline measurement was taken, should be the place where we start our analysis. If we include the days 0 and 1 in our analysis, this might bias our results, since any changes in performance during the first two days have to do with training, not sleep restriction.\n\n### Activity\n\nRemove from the dataset observations where Days is coded 0 or 1, and then make a new variable days_deprived from the Days variable so that the sequence starts at day 2, with day 2 being re-coded as day 0, day 3 as day 1, day 4 as day 2, etc. This new variable now tracks the number of days of sleep deprivation. Store the new table as sleep2.\n\n\n\n\n<div class='webex-solution'><button>Solution</button>\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsleep2 <- sleepstudy |> \n  filter(Days >= 2L) |> \n  mutate(days_deprived = Days - 2L)\n\nhead(sleep2)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| Reaction| Days|Subject | days_deprived|\n|--------:|----:|:-------|-------------:|\n| 250.8006|    2|308     |             0|\n| 321.4398|    3|308     |             1|\n| 356.8519|    4|308     |             2|\n| 414.6901|    5|308     |             3|\n| 382.2038|    6|308     |             4|\n| 290.1486|    7|308     |             5|\n\n</div>\n:::\n:::\n\n\n\n\n</div>\n\n\n\nTake a moment to think about how me might model the relationship between days_deprived and Reaction. Does reaction time increase or decrease with increasing sleep deprivation? Is the relationship roughly stable or does it change with time?\n\n\n| Model | Syntax                                     |\n|-------|--------------------------------------------|\n| Random intercepts    | Reaction ~ days_deprived + (1 | Subject)                       |\n| Random intercepts and slopes     | Reaction ~ days_deprived + (days_deprived | Subject)        |\n| Random slopes    | Reaction ~ days_deprived + (0 + days_deprived | Subject)        |\n\nThe most reasonable model is Model 2 - different patients may have different initial reaction times & they may respond to sleep deprivation differently. \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsleep_model <- lmer(Reaction ~ days_deprived + (days_deprived | Subject), data = sleep2)\nsummary(sleep_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML. t-tests use Satterthwaite's method [\nlmerModLmerTest]\nFormula: Reaction ~ days_deprived + (days_deprived | Subject)\n   Data: sleep2\n\nREML criterion at convergence: 1404.1\n\nScaled residuals: \n    Min      1Q  Median      3Q     Max \n-4.0157 -0.3541  0.0069  0.4681  5.0732 \n\nRandom effects:\n Groups   Name          Variance Std.Dev. Corr\n Subject  (Intercept)   958.35   30.957       \n          days_deprived  45.78    6.766   0.18\n Residual               651.60   25.526       \nNumber of obs: 144, groups:  Subject, 18\n\nFixed effects:\n              Estimate Std. Error      df t value Pr(>|t|)    \n(Intercept)    267.967      8.266  17.000  32.418  < 2e-16 ***\ndays_deprived   11.435      1.845  16.999   6.197 9.75e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nCorrelation of Fixed Effects:\n            (Intr)\ndays_deprvd -0.062\n```\n\n\n:::\n:::\n\n\nWe can compare this against a simpler intercept model to check this fit\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsleep_model_intercept <- lmer(Reaction ~ days_deprived + (1| Subject), data = sleep2)\n\nanova(sleep_model_intercept, sleep_model)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|                      | npar|      AIC|      BIC|    logLik| deviance|    Chisq| Df| Pr(>Chisq)|\n|:---------------------|----:|--------:|--------:|---------:|--------:|--------:|--:|----------:|\n|sleep_model_intercept |    4| 1446.490| 1458.369| -719.2451| 1438.490|       NA| NA|         NA|\n|sleep_model           |    6| 1425.158| 1442.977| -706.5790| 1413.158| 25.33213|  2|    3.2e-06|\n\n</div>\n:::\n:::\n\n\nQ. What does the LRT indicate about the effect of the random slopeon our model?\n\nShould we remove it from our model? <select class='webex-select'><option value='blank'></option><option value=''>Yes</option><option value='answer'>No</option></select>\n\n\n<div class='webex-solution'><button>Solution</button>\n\n\nThe LRT indicates that removing random slope from the design of our model explains significantly less variance, and should be left in the model. \n\n\n</div>\n\n\n\n# Reporting Mixed Model Results\n\nOnce you get your model, you have to **present** it in an accurate, clear and attractive form.\n\nThe `summary()` function provides us with some useful numbers such as the amount of variance left over after fitting our fixed effects that can be assigned to each of our random effects. It also provides information on how correlated our random effects are, which may be of interest in understanding the structure of our data as well.\n\nWe can use it to check that the modelled random effect structure matches our data.\n\nIt includes the coefficient estimates, t-statistics and p-values of our fixed effects\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(sleep_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML. t-tests use Satterthwaite's method [\nlmerModLmerTest]\nFormula: Reaction ~ days_deprived + (days_deprived | Subject)\n   Data: sleep2\n\nREML criterion at convergence: 1404.1\n\nScaled residuals: \n    Min      1Q  Median      3Q     Max \n-4.0157 -0.3541  0.0069  0.4681  5.0732 \n\nRandom effects:\n Groups   Name          Variance Std.Dev. Corr\n Subject  (Intercept)   958.35   30.957       \n          days_deprived  45.78    6.766   0.18\n Residual               651.60   25.526       \nNumber of obs: 144, groups:  Subject, 18\n\nFixed effects:\n              Estimate Std. Error      df t value Pr(>|t|)    \n(Intercept)    267.967      8.266  17.000  32.418  < 2e-16 ***\ndays_deprived   11.435      1.845  16.999   6.197 9.75e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nCorrelation of Fixed Effects:\n            (Intr)\ndays_deprvd -0.062\n```\n\n\n:::\n:::\n\n\n:::{.callout-note}\n\nNote that the t values only appear with df and a p value when using the lmerTest version of lmer(). This is because the degrees of freedom in a mixed-effects model are not well-defined. Often people will treat them as Wald z- values, i.e., as observations from the standard normal distribution. Because the t-distribution asymptotes the standard normal distribution as the number of observations goes to infinity, this \"t-as-z\" practice is legitimate if you have a large enough set of observations.\n\nThe lmerTest function produces estimated degrees of freedom with a satterthwaite approximation (another common method is the \"kenward approximation\"), which will have the effect of widening confidence intervals. It is important to know what method you are using, and to be consistent across your presentation/write-up \n\n:::\n\nWe can also produce an `anova()` type summary of our fixed effects\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nanova(sleep_model)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|              |   Sum Sq|  Mean Sq| NumDF|   DenDF|  F value|  Pr(>F)|\n|:-------------|--------:|--------:|-----:|-------:|--------:|-------:|\n|days_deprived | 25023.83| 25023.83|     1| 16.9995| 38.40382| 9.8e-06|\n\n</div>\n:::\n:::\n\n\nWe may also wish to report $R^2$ values from our model fit. This requires the `MuMIn` package. \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(MuMIn)\nr.squaredGLMM(sleep_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           R2m       R2c\n[1,] 0.2055824 0.8062353\n```\n\n\n:::\n:::\n\n\nThis calculates two values the first $R^2_{m}$ is the marginal $R^2$ value, representing the proportion of variance explained by our fixed effects. The second $R^2_{c}$ is the conditional $R^2$, which is the proportion of variance explained by the full model, with both fixed and random effects. \n\n## Tables\n\nThere are a few packages for producing beautiful summary tables from regression models, but not all of them can handle mixed-effects models, the `sjPlot` @R-sjPlot package is one of the most robust and produces a simple HTML table detailing fixed and random effects, produces 95% confidence intervals for fixed effects and calculates those $R^2$ values for you:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsjPlot::tab_model(sleep_model, \n                  df.method = \"satterthwaite\")\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table style=\"border-collapse:collapse; border:none;\">\n<tr>\n<th style=\"border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; \">&nbsp;</th>\n<th colspan=\"3\" style=\"border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; \">Reaction</th>\n</tr>\n<tr>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; \">Predictors</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">Estimates</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">CI</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">p</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">(Intercept)</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">267.97</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">250.53&nbsp;&ndash;&nbsp;285.41</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>&lt;0.001</strong></td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">days deprived</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">11.44</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">7.54&nbsp;&ndash;&nbsp;15.33</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>&lt;0.001</strong></td>\n</tr>\n<tr>\n<td colspan=\"4\" style=\"font-weight:bold; text-align:left; padding-top:.8em;\">Random Effects</td>\n</tr>\n\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;\">&sigma;<sup>2</sup></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"3\">651.60</td>\n</tr>\n\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;\">&tau;<sub>00</sub> <sub>Subject</sub></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"3\">958.35</td>\n\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;\">&tau;<sub>11</sub> <sub>Subject.days_deprived</sub></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"3\">45.78</td>\n\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;\">&rho;<sub>01</sub> <sub>Subject</sub></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"3\">0.18</td>\n\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;\">ICC</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"3\">0.76</td>\n\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;\">N <sub>Subject</sub></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"3\">18</td>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;\">Observations</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;\" colspan=\"3\">144</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;\">Marginal R<sup>2</sup> / Conditional R<sup>2</sup></td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"3\">0.206 / 0.806</td>\n</tr>\n\n</table>\n\n`````\n:::\n:::\n\n\n## Figures\n\nWe have covered some of the packages that allow us to easily produce marginal and conditional fits, along with 95% confidence or prediction intervals: these will output `ggplot2` figures, allowing plenty of customisation for presentation\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Custom colors\ncustom.col <- c(\"#000000\", \"#E69F00\", \"#56B4E9\", \"#009E73\",\n                \"#F0E442\", \"#0072B2\", \"#D55E00\", \"#CC79A7\")\n\ncols <- colorRampPalette(custom.col)(18)\n\n\nggpredict(sleep_model, terms = c(\"days_deprived\", \"Subject\" ), \n          type = \"random\") |>  \nplot(x = _, show_data = TRUE) + \n  scale_color_manual(values = cols)+\n  facet_wrap(~group)+theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](mixed-model_files/figure-html/unnamed-chunk-76-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n\n## Write-ups\n\n> We fitted a linear mixed model (estimated using REML) to predict reaction time (ms) with days of sleep deprivation. The\nmodel included a random slope and intercept design to allow for the repeated measure design of measuring patients on multiple days and for the effect o sleep deprivation to vary by patient. The model's total explanatory power is substantial (conditional R^2 = 0.81), and the part related to the fixed effects alone (marginal R2) is of 0.21. \nThe mean reaction time at Day 0 was  267.97ms (95% CI[250.53, 285.41], t(17) = 32.42, p < .001). The effect of sleep deprivation was a steady increase to the reaction time of 11.44ms per day of sleep loss ([7.54 - 15.33], t(17) = 6.2, p < 0.001). \nThese 95% Confidence Intervals (CIs) and p-values were computed using a satterthwaite approximation of the degrees of freedom and a t-distribution approximation.\n\n\n\n# Summary\n\nHere is a suggested workflow:\n\n1. Start with a model containing only fixed effects: Begin by fitting a model with the fixed effects that are relevant to your research question. Include the main predictors and any potential interactions you hypothesize might exist. For example, if you have predictors A and B, you might start with a model like response ~ A + B + A:B.\n\n2. Assess fixed effects and interactions: Evaluate the significance, direction, and magnitude of the fixed effects coefficients. Look for interactions that show significant effects and consider their interpretation in the context of your research question. This step allows you to identify the key variables and interactions that are important in explaining the variation in the response variable.\n\n3. Model evaluation and refinement: Assess the goodness of fit of the fixed effects model using appropriate measures like AIC, BIC, or model deviance. Consider conducting model comparison to evaluate different models with alternative fixed effects structures. This process helps you refine the model and select the most appropriate combination of variables and interactions. *However - this should be no substitution for carefully considered hypotheses and experimental design*. \n\n4. Incorporate random effects: Once you have identified the significant fixed effects and relevant interactions, you can then consider the inclusion of random effects. Random effects capture the variation at different levels and can account for individual differences or clustering within groups. Evaluate the need for random intercepts, random slopes, or crossed random effects based on your research design and the nature of the data.\n\n5. Assess and compare models with random effects: Fit models with random effects and compare their fit to the fixed effects model. Consider appropriate measures such as likelihood ratio tests, AIC, or BIC for model comparison. Evaluate the contribution of the random effects to the model.*However - this should be no substitution for carefully considered hypotheses and experimental design*. And we have seen examples where we leave random effects in place despite LRT tests.\n\n6. Validate and interpret the final model: Validate the final model by assessing assumptions, checking for influential observations, and performing sensitivity analysis. Interpret the estimated coefficients, including fixed effects and random effects, in the context of your research question. Report the results with figures, summary tables and carefully considered text summarising the analysis.\n\nBy initially focusing on the fixed effects, you can establish the foundation of your model and identify the significant predictors and interactions. This step allows you to better understand the relationships in your data and guide the subsequent inclusion of random effects if appropriate.\n\n\n## Mixed Model extensions\n\n\n## Practical problems\n\nBelow are two common issues or warnings you will likely encounter when fitting linear models:\n\n- `boundary (singular) fit: see help('isSingular')`: Your model did fit, but it generated that warning because some of your random effects are very small, common with complex mixed-effect models. You can read more about this in [help page](https://rdrr.io/cran/lme4/man/isSingular.html)\n\n- Convergence warnings: Values for the mixed-effects models are determined using optimisation algorithms. Sometimes these algorithms fail to converge on a best parameter estimate, which will produce an error. There are several possible solutions:\n\n    - Normalise and rescale: Rescaling the variables can mitigate issues caused by the differences in scales or magnitudes of the predictors, which can affect the optimization process. You can rescale the fixed effects predictors by subtracting the mean and dividing by the standard deviation. This centers the variables around zero and scales them to have a standard deviation of 1. This can be done using the scale() function in R.\n    - Try alternative optimisation algorithms:\n    \n    `lmer3 <- lmer(y ~ x + (x | group), data = data, \n    control = lmerControl(optimizer =\"Nelder_Mead\"))`\n    \n    - Finally, although it pains me to admit it, you should try running the model using a different package - each has their own unique and slightly different optimisation protocols. \n\n\n## Further Reading\n\nSome essential reading to continue your mixed-model journey! \n\n- [A brief introduction to mixed effects modelling and multi-model inference in ecology](https://peerj.com/articles/4794/) @xav_2018\n\n- [Mixed Effects Models and Extensions in Ecology with R](https://link.springer.com/book/10.1007/978-0-387-87458-6) @zuur_2009\n\n- [Perils and pitfalls of mixed-effects regression models in biology](https://peerj.com/articles/9522/) @silk_2020\n",
    "supporting": [
      "mixed-model_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"site_libs/font-awesome-5.13.0/js/script.js\"></script>\n<script src=\"site_libs/htmlwidgets-1.6.2/htmlwidgets.js\"></script>\n<script src=\"site_libs/viz-1.8.2/viz.js\"></script>\n<link href=\"site_libs/DiagrammeR-styles-0.2/styles.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/grViz-binding-1.0.10/grViz.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}