<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Chapter 11 Paired designs | Introduction to Statistics</title>
<meta name="author" content="Philip T. Leftwich">
<meta name="description" content="The structure of our linear model so far has produced the output for a standard two-sample Student's t-test. However, when we first calculated our estimates by hand - we started by making an...">
<meta name="generator" content="bookdown 0.34 with bs4_book()">
<meta property="og:title" content="Chapter 11 Paired designs | Introduction to Statistics">
<meta property="og:type" content="book">
<meta property="og:url" content="https://ueabio.github.io/physalia-intro-stats-2023/paired-designs.html">
<meta property="og:image" content="https://ueabio.github.io/physalia-intro-stats-2023/images/logos/twitter_card.png">
<meta property="og:description" content="The structure of our linear model so far has produced the output for a standard two-sample Student's t-test. However, when we first calculated our estimates by hand - we started by making an...">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Chapter 11 Paired designs | Introduction to Statistics">
<meta name="twitter:description" content="The structure of our linear model so far has produced the output for a standard two-sample Student's t-test. However, when we first calculated our estimates by hand - we started by making an...">
<meta name="twitter:image" content="https://ueabio.github.io/physalia-intro-stats-2023/images/logos/twitter_card.png">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.5.0/transition.js"></script><script src="libs/bs3compat-0.5.0/tabs.js"></script><script src="libs/bs3compat-0.5.0/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="libs/font-awesome-5.13.0/js/script.js"></script><script src="libs/kePrint-0.0.1/kePrint.js"></script><link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<script src="libs/htmlwidgets-1.6.2/htmlwidgets.js"></script><script src="libs/viz-1.8.2/viz.js"></script><link href="libs/DiagrammeR-styles-0.2/styles.css" rel="stylesheet">
<script src="libs/grViz-binding-1.0.10/grViz.js"></script><!-- Global site tag (gtag.js) - Google Analytics --><script async src="https://www.googletagmanager.com/gtag/js?id=G-6NP3MF25W3"></script><script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-6NP3MF25W3');
    </script><script language="javascript"> 
        function toggle(id) {
            var ele = document.getElementById("toggleText" + id);
            var text = document.getElementById("displayText" + id);
            var buttonText = text.innerHTML.replace("Show ", "");
            buttonText = buttonText.replace("Hide ", "");
            if(ele.style.display == "block") {
                ele.style.display = "none";
                text.innerHTML = "Show " + buttonText;
            } else {
                ele.style.display = "block";
                text.innerHTML = "Hide " + buttonText;
            }
        } 
    </script><script language="javascript">
        function openCode(evt, codeName, id) {
            var i, tabcontent, tablinks;
            tabcontent = document.getElementsByClassName("tabcontent" + id);
            for (i = 0; i < tabcontent.length; i++) {
                tabcontent[i].style.display = "none";
            }
            tablinks = document.getElementsByClassName("tablinks" + id);
            for (i = 0; i < tablinks.length; i++) {
                tablinks[i].className = tablinks[i].className.replace(" active", "");
            }
            document.getElementById(codeName).style.display = "block";
            evt.currentTarget.className += " active";
        }
    </script><script language="javascript">
        function hide(id){
            document.getElementById(id).style.display = "none";
        }
    </script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><style type="text/css">
    
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  </style>
<style type="text/css">
    /* Used with Pandoc 2.11+ new --citeproc when CSL is used */
    div.csl-bib-body { }
    div.csl-entry {
      clear: both;
        }
    .hanging div.csl-entry {
      margin-left:2em;
      text-indent:-2em;
    }
    div.csl-left-margin {
      min-width:2em;
      float:left;
    }
    div.csl-right-inline {
      margin-left:2em;
      padding-left:1em;
    }
    div.csl-indent {
      margin-left: 2em;
    }
  </style>
<link rel="stylesheet" href="include/psyteachr.css">
<link rel="stylesheet" href="include/webex.css">
<link rel="stylesheet" href="include/style.css">
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="A guide for Biologists and Ecologists">Introduction to Statistics</a>:
        <small class="text-muted">A guide for Biologists and Ecologists</small>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">Overview</a></li>
<li class="book-part">Exploring Data</li>
<li><a class="" href="loading-data.html"><span class="header-section-number">1</span> Loading data</a></li>
<li><a class="" href="data-wrangling-part-one.html"><span class="header-section-number">2</span> Data wrangling part one</a></li>
<li><a class="" href="data-wrangling-part-two.html"><span class="header-section-number">3</span> Data wrangling part two</a></li>
<li><a class="" href="data-visualisation-with-ggplot2.html"><span class="header-section-number">4</span> Data visualisation with ggplot2</a></li>
<li class="book-part">Descriptive Statistics</li>
<li><a class="" href="data-quality.html"><span class="header-section-number">5</span> Data Quality</a></li>
<li><a class="" href="data-insights.html"><span class="header-section-number">6</span> Data insights</a></li>
<li class="book-part">Linear models</li>
<li><a class="" href="introduction-to-statistics.html"><span class="header-section-number">7</span> Introduction to statistics</a></li>
<li><a class="" href="introduction-to-linear-models.html"><span class="header-section-number">8</span> Introduction to Linear Models</a></li>
<li><a class="" href="assumption-checking.html"><span class="header-section-number">9</span> Assumption checking</a></li>
<li><a class="" href="testing.html"><span class="header-section-number">10</span> Testing</a></li>
<li><a class="active" href="paired-designs.html"><span class="header-section-number">11</span> Paired designs</a></li>
<li><a class="" href="regression.html"><span class="header-section-number">12</span> Regression</a></li>
<li><a class="" href="anova.html"><span class="header-section-number">13</span> ANOVA</a></li>
<li class="book-part">Multiple regression</li>
<li><a class="" href="multi-factor-anova.html"><span class="header-section-number">14</span> Multi factor ANOVA</a></li>
<li><a class="" href="complex-models.html"><span class="header-section-number">15</span> Complex models</a></li>
<li class="book-part">Generalized Linear Models</li>
<li><a class="" href="generalized-linear-models.html"><span class="header-section-number">16</span> Generalized Linear Models</a></li>
<li><a class="" href="poisson-regression-for-count-data-or-rate-data.html"><span class="header-section-number">17</span> Poisson regression (for count data or rate data)</a></li>
<li><a class="" href="logistic-regression-for-binary-data.html"><span class="header-section-number">18</span> Logistic regression (for binary data)</a></li>
<li class="book-part">Mixed Models</li>
<li><a class="" href="foundations-of-mixed-modelling.html"><span class="header-section-number">19</span> Foundations of Mixed Modelling</a></li>
<li><a class="" href="worked-example-1---dolphins.html"><span class="header-section-number">20</span> Worked Example 1 - Dolphins</a></li>
<li><a class="" href="multiple-random-effects.html"><span class="header-section-number">21</span> Multiple random effects</a></li>
<li><a class="" href="worked-example-2---nested-design.html"><span class="header-section-number">22</span> Worked Example 2 - Nested design</a></li>
<li><a class="" href="types-of-random-effects.html"><span class="header-section-number">23</span> Types of Random Effects</a></li>
<li><a class="" href="worked-example-3---sleep-study.html"><span class="header-section-number">24</span> Worked Example 3 - Sleep study</a></li>
<li><a class="" href="reporting-mixed-model-results.html"><span class="header-section-number">25</span> Reporting Mixed Model Results</a></li>
<li><a class="" href="worked-example-4.html"><span class="header-section-number">26</span> Worked Example 4</a></li>
<li><a class="" href="summary-11.html"><span class="header-section-number">27</span> Summary</a></li>
</ul>

        <div class="book-extra">
          <p><a id="book-repo" href="https://github.com/UEABIO/physalia-intro-stats-2023">View book source <i class="fab fa-github"></i></a></p>
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="paired-designs" class="section level1" number="11">
<h1>
<span class="header-section-number">11</span> Paired designs<a class="anchor" aria-label="anchor" href="#paired-designs"><i class="fas fa-link"></i></a>
</h1>
<p>The structure of our linear model so far has produced the output for a standard two-sample Student's <em>t</em>-test. However, when we <em>first</em> <a href="introduction-to-statistics.html#differences-between-groups">calculated our estimates by hand</a> - we started by making an average of the paired differences in height. To generate the equivalent of a paired <em>t</em>-test, we simply have to add the factor for pairs to our linear model formula:</p>
<div class="tab">
<button class="tablinks= T active" onclick="javascript:openCode(event, 'option1= T', '= T');">
Base R
</button>
<button class="tablinks= T" onclick="javascript:openCode(event, 'option2= T', '= T');">
<tt>tidyverse</tt>
</button>
</div>
<div id="option1= T" class="tabcontent= T">
<p>Note that I have made pair a factor - pair 2 is not greater than pair 1 - so it does not make sense to treat these as number values.</p>
<div class="sourceCode" id="cb213"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">lsmodel_darwin</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">height</span> <span class="op">~</span> <span class="va">type</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">pair</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">darwin</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">lsmodel_darwin</span><span class="op">)</span></span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = height ~ type + factor(pair), data = darwin)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -5.4958 -0.9021  0.0000  0.9021  5.4958 
## 
## Coefficients:
##                Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)     21.7458     2.4364   8.925 3.75e-07 ***
## typeSelf        -2.6167     1.2182  -2.148   0.0497 *  
## factor(pair)2   -4.2500     3.3362  -1.274   0.2234    
## factor(pair)3    0.0625     3.3362   0.019   0.9853    
## factor(pair)4    0.5625     3.3362   0.169   0.8685    
## factor(pair)5   -1.6875     3.3362  -0.506   0.6209    
## factor(pair)6   -0.3750     3.3362  -0.112   0.9121    
## factor(pair)7   -0.0625     3.3362  -0.019   0.9853    
## factor(pair)8   -2.6250     3.3362  -0.787   0.4445    
## factor(pair)9   -3.0625     3.3362  -0.918   0.3742    
## factor(pair)10  -0.6250     3.3362  -0.187   0.8541    
## factor(pair)11  -0.6875     3.3362  -0.206   0.8397    
## factor(pair)12  -0.9375     3.3362  -0.281   0.7828    
## factor(pair)13  -3.0000     3.3362  -0.899   0.3837    
## factor(pair)14  -1.1875     3.3362  -0.356   0.7272    
## factor(pair)15  -5.4375     3.3362  -1.630   0.1254    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 3.336 on 14 degrees of freedom
## Multiple R-squared:  0.469,  Adjusted R-squared:  -0.09997 
## F-statistic: 0.8243 on 15 and 14 DF,  p-value: 0.6434</code></pre>
</div>
<div id="option2= T" class="tabcontent= T">
<div class="sourceCode" id="cb215"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">darwin</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>pair <span class="op">=</span> <span class="fu"><a href="https://forcats.tidyverse.org/reference/as_factor.html">as_factor</a></span><span class="op">(</span><span class="va">pair</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">height</span> <span class="op">~</span> <span class="va">type</span> <span class="op">+</span> <span class="va">pair</span>, data <span class="op">=</span> <span class="va">.</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu">broom</span><span class="fu">::</span><span class="fu"><a href="https://generics.r-lib.org/reference/tidy.html">tidy</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<div class="kable-table">
<div class="inline-table"><table class="table table-sm">
<thead><tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">21.745833</td>
<td align="right">2.436389</td>
<td align="right">8.9254352</td>
<td align="right">0.0000004</td>
</tr>
<tr class="even">
<td align="left">typeSelf</td>
<td align="right">-2.616667</td>
<td align="right">1.218195</td>
<td align="right">-2.1479875</td>
<td align="right">0.0497029</td>
</tr>
<tr class="odd">
<td align="left">pair2</td>
<td align="right">-4.250000</td>
<td align="right">3.336163</td>
<td align="right">-1.2739185</td>
<td align="right">0.2234352</td>
</tr>
<tr class="even">
<td align="left">pair3</td>
<td align="right">0.062500</td>
<td align="right">3.336163</td>
<td align="right">0.0187341</td>
<td align="right">0.9853176</td>
</tr>
<tr class="odd">
<td align="left">pair4</td>
<td align="right">0.562500</td>
<td align="right">3.336163</td>
<td align="right">0.1686069</td>
<td align="right">0.8685176</td>
</tr>
<tr class="even">
<td align="left">pair5</td>
<td align="right">-1.687500</td>
<td align="right">3.336163</td>
<td align="right">-0.5058206</td>
<td align="right">0.6208532</td>
</tr>
<tr class="odd">
<td align="left">pair6</td>
<td align="right">-0.375000</td>
<td align="right">3.336163</td>
<td align="right">-0.1124046</td>
<td align="right">0.9120984</td>
</tr>
<tr class="even">
<td align="left">pair7</td>
<td align="right">-0.062500</td>
<td align="right">3.336163</td>
<td align="right">-0.0187341</td>
<td align="right">0.9853176</td>
</tr>
<tr class="odd">
<td align="left">pair8</td>
<td align="right">-2.625000</td>
<td align="right">3.336163</td>
<td align="right">-0.7868320</td>
<td align="right">0.4444963</td>
</tr>
<tr class="even">
<td align="left">pair9</td>
<td align="right">-3.062500</td>
<td align="right">3.336163</td>
<td align="right">-0.9179707</td>
<td align="right">0.3741786</td>
</tr>
<tr class="odd">
<td align="left">pair10</td>
<td align="right">-0.625000</td>
<td align="right">3.336163</td>
<td align="right">-0.1873410</td>
<td align="right">0.8540813</td>
</tr>
<tr class="even">
<td align="left">pair11</td>
<td align="right">-0.687500</td>
<td align="right">3.336163</td>
<td align="right">-0.2060750</td>
<td align="right">0.8396990</td>
</tr>
<tr class="odd">
<td align="left">pair12</td>
<td align="right">-0.937500</td>
<td align="right">3.336163</td>
<td align="right">-0.2810114</td>
<td align="right">0.7828120</td>
</tr>
<tr class="even">
<td align="left">pair13</td>
<td align="right">-3.000000</td>
<td align="right">3.336163</td>
<td align="right">-0.8992366</td>
<td align="right">0.3837329</td>
</tr>
<tr class="odd">
<td align="left">pair14</td>
<td align="right">-1.187500</td>
<td align="right">3.336163</td>
<td align="right">-0.3559478</td>
<td align="right">0.7271862</td>
</tr>
<tr class="even">
<td align="left">pair15</td>
<td align="right">-5.437500</td>
<td align="right">3.336163</td>
<td align="right">-1.6298663</td>
<td align="right">0.1254148</td>
</tr>
</tbody>
</table></div>
</div>
</div>
<script> javascript:hide('option2= T') </script><p>The table of coefficients suddenly looks a lot more complicated! This is because <strong>now</strong> the intercept is the height of the crossed plant from pair 1:</p>
<ul>
<li><p>The second row now compares the mean heights of Crossed and Selfed plants when they are in the same pair</p></li>
<li><p>rows three to 16 compare the average difference of each pair (Crossed and Selfed combined) against pair 1</p></li>
</ul>
<p>Again the linear model computes every possible combination of <em>t</em>-statistic and <em>P</em>-value, however the only one we care about is the difference in Cross and Self-pollinated plant heights. If we ignore the pair comparisons the second row gives us a <em>paired t</em>-test. 'What is the difference in height between Cross and Self-pollinated plants when we hold pairs constant.'</p>
<div id="activity-1-compare-paired-model-designs" class="section level2" number="11.1">
<h2>
<span class="header-section-number">11.1</span> Activity 1: Compare paired model designs<a class="anchor" aria-label="anchor" href="#activity-1-compare-paired-model-designs"><i class="fas fa-link"></i></a>
</h2>
<p>We previously compared the difference in plant heights by subtracting the difference between each pair of plants. Check our reasoning on the model design above by making another linear model based on the difference between pairs and check whether this is significantly different from 0, <code>lm(difference ~ 1)</code></p>
<button id="displayTextunnamed-chunk-9" onclick="javascript:toggle('unnamed-chunk-9');">
Show Solution
</button>
<div id="toggleTextunnamed-chunk-9" style="display: none">
<div class="panel panel-default">
<div class="panel-heading panel-heading1">
Solution
</div>
<div class="panel-body">
<p>darwin_wide &lt;- darwin %&gt;%
# pivot/reshape the data from long to wide format
pivot_wider(names_from = type, values_from = height) %&gt;%
# Calculate the difference between 'Cross' and 'Self' heights for each pair
mutate(difference = Cross - Self)</p>
<p>wide_model &lt;- lm(difference ~ 1, data = darwin_wide)</p>
<p>summary(wide_model)</p>
</div>
</div>
</div>
<p>For completeness let's generate the confidence intervals for the <em>paired t</em>-test and compare them to our <em>unpaired t</em>-test.</p>
<div class="sourceCode" id="cb216"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">height</span> <span class="op">~</span> <span class="va">type</span>, data <span class="op">=</span> <span class="va">darwin</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>   <span class="fu">broom</span><span class="fu">::</span><span class="fu"><a href="https://generics.r-lib.org/reference/tidy.html">tidy</a></span><span class="op">(</span><span class="va">.</span>, conf.int<span class="op">=</span><span class="cn">T</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>    <span class="fu"><a href="https://dplyr.tidyverse.org/reference/slice.html">slice</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fl">2</span><span class="op">)</span> </span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">height</span> <span class="op">~</span> <span class="va">type</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">pair</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">darwin</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu">broom</span><span class="fu">::</span><span class="fu"><a href="https://generics.r-lib.org/reference/tidy.html">tidy</a></span><span class="op">(</span><span class="va">.</span>, conf.int<span class="op">=</span><span class="cn">T</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/slice.html">slice</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fl">2</span><span class="op">)</span> <span class="co"># just show first two rows</span></span></code></pre></div>
<div class="kable-table">
<div class="inline-table"><table class="table table-sm">
<colgroup>
<col width="16%">
<col width="13%">
<col width="13%">
<col width="13%">
<col width="13%">
<col width="12%">
<col width="15%">
</colgroup>
<thead><tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
<th align="right">conf.low</th>
<th align="right">conf.high</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">20.191667</td>
<td align="right">0.7592028</td>
<td align="right">26.595880</td>
<td align="right">0.0000000</td>
<td align="right">18.63651</td>
<td align="right">21.7468231</td>
</tr>
<tr class="even">
<td align="left">typeSelf</td>
<td align="right">-2.616667</td>
<td align="right">1.0736749</td>
<td align="right">-2.437113</td>
<td align="right">0.0214145</td>
<td align="right">-4.81599</td>
<td align="right">-0.4173433</td>
</tr>
</tbody>
</table></div>
</div>
<div class="kable-table">
<div class="inline-table"><table class="table table-sm">
<colgroup>
<col width="16%">
<col width="13%">
<col width="13%">
<col width="13%">
<col width="13%">
<col width="13%">
<col width="15%">
</colgroup>
<thead><tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
<th align="right">conf.low</th>
<th align="right">conf.high</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">21.745833</td>
<td align="right">2.436389</td>
<td align="right">8.925435</td>
<td align="right">0.0000004</td>
<td align="right">16.520298</td>
<td align="right">26.9713683</td>
</tr>
<tr class="even">
<td align="left">typeSelf</td>
<td align="right">-2.616667</td>
<td align="right">1.218195</td>
<td align="right">-2.147988</td>
<td align="right">0.0497029</td>
<td align="right">-5.229434</td>
<td align="right">-0.0038992</td>
</tr>
</tbody>
</table></div>
</div>
<p>We can see that estimate of the mean difference is identical but the 95% confidence intervals are now slightly different. So in this particular version we have actually increased our level of uncertainty by including the pair parameter.</p>
<div class="sourceCode" id="cb217"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">m1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">height</span> <span class="op">~</span> <span class="va">type</span>, data <span class="op">=</span> <span class="va">darwin</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu">broom</span><span class="fu">::</span><span class="fu"><a href="https://generics.r-lib.org/reference/tidy.html">tidy</a></span><span class="op">(</span><span class="va">.</span>, conf.int<span class="op">=</span><span class="cn">T</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/slice.html">slice</a></span><span class="op">(</span><span class="fl">2</span><span class="op">:</span><span class="fl">2</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>model<span class="op">=</span><span class="st">"unpaired"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">m2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">height</span> <span class="op">~</span> <span class="va">type</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">pair</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">darwin</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu">broom</span><span class="fu">::</span><span class="fu"><a href="https://generics.r-lib.org/reference/tidy.html">tidy</a></span><span class="op">(</span><span class="va">.</span>, conf.int<span class="op">=</span><span class="cn">T</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/slice.html">slice</a></span><span class="op">(</span><span class="fl">2</span><span class="op">:</span><span class="fl">2</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>model<span class="op">=</span><span class="st">"paired"</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/cbind.html">rbind</a></span><span class="op">(</span><span class="va">m1</span>,<span class="va">m2</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span><span class="va">model</span>, <span class="va">estimate</span><span class="op">)</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_linerange.html">geom_pointrange</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>ymin<span class="op">=</span><span class="va">conf.high</span>, ymax<span class="op">=</span><span class="va">conf.low</span><span class="op">)</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_hline</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>yintercept<span class="op">=</span><span class="fl">0</span><span class="op">)</span>, linetype<span class="op">=</span><span class="st">"dashed"</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_minimal</a></span><span class="op">(</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/coord_flip.html">coord_flip</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="14-Testing_files/figure-html/unnamed-chunk-11-1.png" width="100%" style="display: block; margin: auto;"></div>
<div class="info">
<p>
Choosing the right model
</p>
<p>
In this case we had a good <em>a priori</em> reason to include pair
in our model, so I would argue that it should stay - alternative
approaches are model simplification and stepwise removal. We will
discuss these later.
</p>
</div>
</div>
<div id="effect-sizes" class="section level2" number="11.2">
<h2>
<span class="header-section-number">11.2</span> Effect sizes<a class="anchor" aria-label="anchor" href="#effect-sizes"><i class="fas fa-link"></i></a>
</h2>
<p>We have discussed the importance of using confidence intervals to talk about effect sizes. When our 95% confidence intervals do not overlap the intercept, this indicates we have difference in our means which is significant at <span class="math inline">\(\alpha\)</span> = 0.05. More interestingly than this it allows us to talk about the 'amount of difference' between our treatments, the lower margin of our confidence intervals is the smallest/minimum effect size. On the response scale of our variables this is very useful, we can report for example that there is <em>at least</em> a 0.4 inch height difference between self and crossed fertilised plants at <span class="math inline">\(\alpha\)</span> = 0.05.</p>
</div>
<div id="type-1-and-type-2-errors" class="section level2" number="11.3">
<h2>
<span class="header-section-number">11.3</span> Type 1 and Type 2 errors<a class="anchor" aria-label="anchor" href="#type-1-and-type-2-errors"><i class="fas fa-link"></i></a>
</h2>
<p>The repeatability of results is a key part of the scientific method. Unfortunately there is often an emphasis in the literature on 'novel findings', which means that unusual/interesting results that happen to reach statistical significance may be more likely to be published. The reality is that we know if we set an <span class="math inline">\(\alpha\)</span> = 0.05, that we run the risk of rejecting the null hypothesis incorrectly in 1 in 20 of our experiments (A Type 1 error).</p>
<p>Type 2 errors. Statistical tests provide you with the probability of making a Type 1 error (rejecting the null hypothesis incorrectly) in the form of <em>P</em>. But what about Type 2 errors? Keeping the null hypothesis, when we should be rejecting it? Or not finding an effect.</p>
<p>The probability of making a Type 2 error is known as <span class="math inline">\(1-\beta\)</span>, where <span class="math inline">\(\beta\)</span> refers to your statistical 'power'. Working out statistical power is is very straightforward for simple tests, and then becomes rapidly more diffcult as the complexity of your analysis increases... but it is an important concept to understand.</p>
<p>On the other side of the coin is experimental <em>power</em> - this is strength of your experiment to detect a statistical effect <em>when there is one</em>. Power is expressed as 1-<span class="math inline">\(\beta\)</span>. You want beta error typically to be less than 20%. So, you want a power of about 80%. That is you have an 80% chance of finding an effect <strong>if it's there</strong>.</p>
<div class="info">
<p>
All experiments/statistical analyses will become <em>statistically
significant</em> if you make the sample size large enough. In this
respect it shows how misleading a significant result can be. It is not
that interesting if a result is statistically significant, but the
effect size is tiny.
</p>
</div>
</div>
<div id="repeatability" class="section level2" number="11.4">
<h2>
<span class="header-section-number">11.4</span> Repeatability<a class="anchor" aria-label="anchor" href="#repeatability"><i class="fas fa-link"></i></a>
</h2>
<p>It is <strong>not possible</strong> for you to know from a single experiment whether you have made Type 1 or Type 2 errors. However, over time as experiments are eventually repeated the literature builds up allowing us to synthesise the evidence. Let's try that now &amp; imagine a scenario where Darwin's experiment has been repeated another 20 times.</p>
<p>In the example below we have made a for loop that assumes we 'know' the true mean difference of crossed and fertilised plants and the standard deviation of the 'population'(we have taken Darwin's experimental data for this). The for loop then creates 20 new sampling experiments, and calculates the estimated mean difference for each experiment</p>
<div class="sourceCode" id="cb218"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Set the seed for reproducibility</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">1234</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Create an empty list with 20 elements</span></span>
<span><span class="va">myList</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/vector.html">vector</a></span><span class="op">(</span><span class="st">"list"</span>, <span class="fl">20</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Create an empty tibble</span></span>
<span><span class="va">y</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Perform a loop for each element in myList</span></span>
<span><span class="kw">for</span> <span class="op">(</span><span class="va">i</span> <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span><span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">myList</span><span class="op">)</span><span class="op">)</span> <span class="op">{</span> </span>
<span></span>
<span>  <span class="co"># Generate a random sample of 12 values from a normal distribution</span></span>
<span>  <span class="va">x</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span>n <span class="op">=</span> <span class="fl">12</span>, mean <span class="op">=</span> <span class="fl">2.6</span>, sd <span class="op">=</span> <span class="fl">2.83</span><span class="op">)</span></span>
<span>  </span>
<span>  <span class="co"># Create a tibble with the values of x</span></span>
<span>  <span class="va">data</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span><span class="va">x</span><span class="op">)</span></span>
<span>  </span>
<span>  <span class="co"># Fit a linear regression model with x as the response variable and a constant as the predictor</span></span>
<span>  <span class="va">temp</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">x</span> <span class="op">~</span> <span class="fl">1</span>, data <span class="op">=</span> <span class="va">data</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>    <span class="fu">broom</span><span class="fu">::</span><span class="fu"><a href="https://generics.r-lib.org/reference/tidy.html">tidy</a></span><span class="op">(</span>conf.int <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span> </span>
<span>  </span>
<span>  <span class="co"># Append the model summary to the y tibble</span></span>
<span>  <span class="va">y</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/cbind.html">rbind</a></span><span class="op">(</span><span class="va">y</span>, <span class="va">temp</span><span class="op">)</span>  </span>
<span></span>
<span><span class="op">}</span></span>
<span></span>
<span><span class="co"># Add a column to y indicating the experiment number</span></span>
<span><span class="va">y</span><span class="op">$</span><span class="va">`experiment number`</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fl">20</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># The new dataframe y contains the results of 20 new experiments</span></span>
<span></span>
<span></span>
<span><span class="co"># the new dataframe y contains the results of 20 new experiments</span></span></code></pre></div>
</div>
<div id="activity-2-experimental-repeatability" class="section level2" number="11.5">
<h2>
<span class="header-section-number">11.5</span> Activity 2: Experimental Repeatability<a class="anchor" aria-label="anchor" href="#activity-2-experimental-repeatability"><i class="fas fa-link"></i></a>
</h2>
<div class="panel panel-default">
<div class="panel-heading">
Task
</div>
<div class="panel-body">
Using this newly generated data how many experiments found a significant difference and how many did not? - What would you conclude from this?
</div>
</div>
<button id="displayTextunnamed-chunk-16" onclick="javascript:toggle('unnamed-chunk-16');">
Show Solution
</button>
<div id="toggleTextunnamed-chunk-16" style="display: none">
<div class="panel panel-default">
<div class="panel-heading panel-heading1">
Solution
</div>
<div class="panel-body">
<div class="sourceCode" id="cb219"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Mutate a new column `p value &lt; 0.05` based on the condition of p.value</span></span>
<span><span class="va">y</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>`p value &lt; 0.05` <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/if_else.html">if_else</a></span><span class="op">(</span><span class="va">p.value</span> <span class="op">&gt;</span> <span class="fl">0.049</span>, <span class="st">"non-significant"</span>, <span class="st">"significant"</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="co"># Group the data by the `p value &lt; 0.05` column</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">`p value &lt; 0.05`</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="co"># Summarize the number of experiments in each group</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span>`number of experiments` <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/context.html">n</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<div class="kable-table">
<div class="inline-table"><table class="table table-sm">
<thead><tr class="header">
<th align="left">p value &lt; 0.05</th>
<th align="right">number of experiments</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">non-significant</td>
<td align="right">6</td>
</tr>
<tr class="even">
<td align="left">significant</td>
<td align="right">14</td>
</tr>
</tbody>
</table></div>
</div>
</div>
</div>
</div>
<p>In <strong>my</strong> example nearly a third of the experiments did not find a statistically significant difference. A less formal review of the research might tally these <em>P</em>-values and conclude that there are inconsistent results in the literature.</p>
<p>A <strong>better</strong> way would be to look at the estimates and calculated confidence intervals</p>
<div class="panel panel-default">
<div class="panel-heading">
Task
</div>
<div class="panel-body">
Using this newly generated data compare the estimates and confidence intervals? - What do you conclude from this?
</div>
</div>
<button id="displayTextunnamed-chunk-18" onclick="javascript:toggle('unnamed-chunk-18');">
Show Solution
</button>
<div id="toggleTextunnamed-chunk-18" style="display: none">
<div class="panel panel-default">
<div class="panel-heading panel-heading1">
Solution
</div>
<div class="panel-body">
<div class="sourceCode" id="cb220"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Create a plot using ggplot</span></span>
<span><span class="va">y</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">`experiment number`</span>, y <span class="op">=</span> <span class="va">estimate</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="co"># Add point estimates with error bars</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_linerange.html">geom_pointrange</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>ymin <span class="op">=</span> <span class="va">conf.low</span>, ymax <span class="op">=</span> <span class="va">conf.high</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="co"># Add y-axis label</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>y <span class="op">=</span> <span class="st">"Estimated mean effect of outcrossing"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="co"># Add a dashed horizontal line at y = 0.05</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_hline</a></span><span class="op">(</span>linetype <span class="op">=</span> <span class="st">"dashed"</span>, yintercept <span class="op">=</span> <span class="fl">0.05</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="co"># Apply a minimal theme to the plot</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_minimal</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="14-Testing_files/figure-html/unnamed-chunk-23-1.png" width="100%" style="display: block; margin: auto;"></div>
</div>
</div>
</div>
<p>By illustrating this visually, it is clearer to see that the results are not really inconsistent, the negative effects of inbreeding depression are clear to see in all of the experiments - we are simply observing the effect of sampling error.</p>
<p>All 20 studies showed the effect of inbreeding depression, and all the experiments have identical levels of uncertainty. We can clearly see that estimates and intervals are a substantial improvement in the way we report experiments, and that they make comparisons across repeated studies more valuable.</p>
</div>
<div id="activity-3-write-up" class="section level2" number="11.6">
<h2>
<span class="header-section-number">11.6</span> Activity 3: Write-up<a class="anchor" aria-label="anchor" href="#activity-3-write-up"><i class="fas fa-link"></i></a>
</h2>
<div class="panel panel-default">
<div class="panel-heading">
Task
</div>
<div class="panel-body">
Can you write a summary of the <strong>Results</strong>?
</div>
</div>
<button id="displayTextunnamed-chunk-20" onclick="javascript:toggle('unnamed-chunk-20');">
Show Solution
</button>
<div id="toggleTextunnamed-chunk-20" style="display: none">
<div class="panel panel-default">
<div class="panel-heading panel-heading1">
Solution
</div>
<div class="panel-body">
<p>We analysed the difference in heights between selfed and cross-pollinated maize plants using a paired analysis of 15 pairs of plants. On average we found plants that have been cross pollinated (20.2 inches [18.3, 22], (mean [95% CI])) were taller than the self-pollinated plants (t(14) = -2.148, p = 0.0497), with a mean difference in height of 2.62 [0.004, 5.23] inches .</p>
</div>
</div>
</div>
</div>
<div id="summary-4" class="section level2" number="11.7">
<h2>
<span class="header-section-number">11.7</span> Summary<a class="anchor" aria-label="anchor" href="#summary-4"><i class="fas fa-link"></i></a>
</h2>
<p>This chapter finally allowed us to calculate <em>P</em>-values and test statistical significance for our experiments using linear models. We also compared the linear model structures for producing a paired vs. unpaired <em>t</em>-test.</p>
<p>However we also learned to appreciate the potential issues around making Type 1 and Type 2 errors, and how an appreciation of confidence intervals and standardised effect sizes can be used to assess these.</p>
<p>A single experiment is never definitive, and a reliance on reporting <em>P</em>-values is uninformative and can be misleading. Instead reporting estimates and confidence intervals allows us to report our levels of uncertainty, and provides results which are more informative for comparitive studies.</p>

</div>
</div>
<script>

/* update total correct if #webex-total_correct exists */
update_total_correct = function() {
  console.log("webex: update total_correct");

  if (t = document.getElementById("webex-total_correct")) {
    var correct = document.getElementsByClassName("webex-correct").length;
    var solvemes = document.getElementsByClassName("webex-solveme").length;
    var radiogroups = document.getElementsByClassName("webex-radiogroup").length;
    var selects = document.getElementsByClassName("webex-select").length;
    
    t.innerHTML = correct + " of " + (solvemes + radiogroups + selects) + " correct";
  }
}

/* webex-solution button toggling function */
b_func = function() {
  console.log("webex: toggle hide");
  
  var cl = this.parentElement.classList;
  if (cl.contains('open')) {
    cl.remove("open");
  } else {
    cl.add("open");
  }
}

/* function for checking solveme answers */
solveme_func = function(e) {
  console.log("webex: check solveme");

  var real_answers = JSON.parse(this.dataset.answer);
  var my_answer = this.value;
  var cl = this.classList;
  if (cl.contains("ignorecase")) {
    my_answer = my_answer.toLowerCase();
  }
  if (cl.contains("nospaces")) {
    my_answer = my_answer.replace(/ /g, "")
  }

  if (my_answer == "") {
    cl.remove("webex-correct");
    cl.remove("webex-incorrect");
  } else if (real_answers.includes(my_answer)) {
    cl.add("webex-correct");
    cl.remove("webex-incorrect");
  } else {
    cl.add("webex-incorrect");
    cl.remove("webex-correct");
  }

  // match numeric answers within a specified tolerance
  if(this.dataset.tol > 0){
    var tol = JSON.parse(this.dataset.tol);
    var matches = real_answers.map(x => Math.abs(x - my_answer) < tol)
    if (matches.reduce((a, b) => a + b, 0) > 0) {
      cl.add("webex-correct");
    } else {
      cl.remove("webex-correct");
    }
  }

  // added regex bit
  if (cl.contains("regex")){
    answer_regex = RegExp(real_answers.join("|"))
    if (answer_regex.test(my_answer)) {
      cl.add("webex-correct");
    }
  }

  update_total_correct();
}

/* function for checking select answers */
select_func = function(e) {
  console.log("webex: check select");
  
  var cl = this.classList
  
  /* add style */
  cl.remove("webex-incorrect");
  cl.remove("webex-correct");
  if (this.value == "answer") {
    cl.add("webex-correct");
  } else if (this.value != "blank") {
    cl.add("webex-incorrect");
  }
  
  update_total_correct();
}

/* function for checking radiogroups answers */
radiogroups_func = function(e) {
  console.log("webex: check radiogroups");

  var checked_button = document.querySelector('input[name=' + this.id + ']:checked');
  var cl = checked_button.parentElement.classList;
  var labels = checked_button.parentElement.parentElement.children;
  
  /* get rid of styles */
  for (i = 0; i < labels.length; i++) {
    labels[i].classList.remove("webex-incorrect");
    labels[i].classList.remove("webex-correct");
  }
  
  /* add style */
  if (checked_button.value == "answer") {
    cl.add("webex-correct");
  } else {
    cl.add("webex-incorrect");
  }
  
  update_total_correct();
}

window.onload = function() {
  console.log("onload");
  /* set up solution buttons */
  var buttons = document.getElementsByTagName("button");

  for (var i = 0; i < buttons.length; i++) {
    if (buttons[i].parentElement.classList.contains('webex-solution')) {
      buttons[i].onclick = b_func;
    }
  }

  /* set up webex-solveme inputs */
  var solveme = document.getElementsByClassName("webex-solveme");

  for (var i = 0; i < solveme.length; i++) {
    /* make sure input boxes don't auto-anything */
    solveme[i].setAttribute("autocomplete","off");
    solveme[i].setAttribute("autocorrect", "off");
    solveme[i].setAttribute("autocapitalize", "off");
    solveme[i].setAttribute("spellcheck", "false");
    solveme[i].value = "";

    /* adjust answer for ignorecase or nospaces */
    var cl = solveme[i].classList;
    var real_answer = solveme[i].dataset.answer;
    if (cl.contains("ignorecase")) {
      real_answer = real_answer.toLowerCase();
    }
    if (cl.contains("nospaces")) {
      real_answer = real_answer.replace(/ /g, "");
    }
    solveme[i].dataset.answer = real_answer;

    /* attach checking function */
    solveme[i].onkeyup = solveme_func;
    solveme[i].onchange = solveme_func;
  }
  
  /* set up radiogroups */
  var radiogroups = document.getElementsByClassName("webex-radiogroup");
  for (var i = 0; i < radiogroups.length; i++) {
    radiogroups[i].onchange = radiogroups_func;
  }
  
  /* set up selects */
  var selects = document.getElementsByClassName("webex-select");
  for (var i = 0; i < selects.length; i++) {
    selects[i].onchange = select_func;
  }

  update_total_correct();
}

</script><script>
$( document ).ready(function() {
  var cite = ' ';
  var license = ' <a rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/" target="blank"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png"></a>';

  $("footer div.row div:eq(1) p").html(
    license
  );
});
</script><div class="chapter-nav">
<div class="prev"><a href="testing.html"><span class="header-section-number">10</span> Testing</a></div>
<div class="next"><a href="regression.html"><span class="header-section-number">12</span> Regression</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#paired-designs"><span class="header-section-number">11</span> Paired designs</a></li>
<li><a class="nav-link" href="#activity-1-compare-paired-model-designs"><span class="header-section-number">11.1</span> Activity 1: Compare paired model designs</a></li>
<li><a class="nav-link" href="#effect-sizes"><span class="header-section-number">11.2</span> Effect sizes</a></li>
<li><a class="nav-link" href="#type-1-and-type-2-errors"><span class="header-section-number">11.3</span> Type 1 and Type 2 errors</a></li>
<li><a class="nav-link" href="#repeatability"><span class="header-section-number">11.4</span> Repeatability</a></li>
<li><a class="nav-link" href="#activity-2-experimental-repeatability"><span class="header-section-number">11.5</span> Activity 2: Experimental Repeatability</a></li>
<li><a class="nav-link" href="#activity-3-write-up"><span class="header-section-number">11.6</span> Activity 3: Write-up</a></li>
<li><a class="nav-link" href="#summary-4"><span class="header-section-number">11.7</span> Summary</a></li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
<li><a id="book-source" href="https://github.com/UEABIO/physalia-intro-stats-2023/blob/main/book/14-Testing.Rmd">View source <i class="fab fa-github"></i></a></li>
          <li><a id="book-edit" href="https://github.com/UEABIO/physalia-intro-stats-2023/edit/main/book/14-Testing.Rmd">Edit this page <i class="fab fa-github"></i></a></li>
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>Introduction to Statistics</strong>: A guide for Biologists and Ecologists" was written by Philip T. Leftwich. It was last built on 2024-07-12.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
