{
  "hash": "6175ab5baf8bd95d77497f4be3d36255",
  "result": {
    "engine": "knitr",
    "markdown": "# Complex models\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Required packages\nlibrary(here)\nlibrary(tidyverse)\nlibrary(GGally)\nlibrary(skimr)\nlibrary(GGally)\nlibrary(ggridges)\nlibrary(performance)\nlibrary(patchwork)\n```\n:::\n\n\n\n## Designing a Model\n\nWe are introduced to the fruitfly dataset Partridge and Farquhar (1981)^[https://nature.com/articles/294580a0]. From our understanding of sexual selection and reproductive biology in fruit flies, we know there is a well established 'cost' to reproduction in terms of reduced longevity for female fruitflies. The data from this experiment is designed to test whether increased sexual activity affects the lifespan of male fruitflies.\n\nThe flies used were an outbred stock, sexual activity was manipulated by supplying males with either new virgin females each day, previously mated females ( Inseminated, so remating rates are lower), or provide no females at all (Control). All groups were otherwise treated identically.\n\n* **type**: type of female companion (virgin, inseminated, control(partners = 0))\n\n* **longevity**: lifespan in days\n\n* **thorax**: length of thorax in micrometres (a proxy for body size)\n\n* **sleep**: percentage of the day spent sleeping\n\n\n## Hypothesis\n\nBefore you start any formal analysis you should think clearly about the sensible parameters to test. In this example, we are *most* interested in the effect of sexual activity on longevity. But it is possible that other factors may also affect longevity and we should include these in our model as well, and we should think **hard** about what terms might reasonably be expected to *interact* with sexual activity to affect longevity. \n\n\n:::{.task}\n\n::::{.task-header}\nWhich terms do you think we should include in our model?\n::::\n\n::::{.task-container}\n\n- Identify the dependent variable\n\n- Identify the independent variable(s)\n\n- Write out your hypotheses\n\n- Make sure your linear model reflects your written hypothesis\n\n- Discuss this with someone else in class before checking your answers\n\n::::\n\n:::\n\n\n\n<div class='webex-solution'><button>Solution</button>\n\n\nIn this exercise I have just asked you to try and think logically about suitable predictors. For a more formal investigation you should support this with evidence where possible: \n\n\n* longevity - this is the **dependent** variable\n\n### Independent variables\n\n* type - should definitely be included. \n\n* thorax - the size of the flies could determine longevity. Carreira et al (2009)^[https://www.nature.com/articles/hdy2008117]\n\n* sleep - sleep could easily help determine longevity. Thompson et al (2020)^[https://journals.biologists.com/bio/article/9/9/bio054361/225803/Sleep-length-differences-are-associated-with]\n\n### Hypotheses\n\n- Flies paired with non-virgin females do not live as long, they expend more energy trying to mate with previously mated females.\n\n- Larger male flies live longer than smaller flies.\n\n- Flies that sleep more live longer.\n\n```\n\nlm(longevity ~ type + thorax + sleep, data = dros_clean)\n\n```\n\n### Possible interactions\n\n* type:sleep - the amount that sleep (rest) helps promote longevity could change depending on how much activity the fly engages in when awake. Chen et al (2017)^[https://www.nature.com/articles/s41467-017-00087-5#:~:text=In%20this%20study%2C%20we%20show,but%20aroused%20females%20sleep%20more]\n\n### Hypothesis\n\n- Sleep reduces or offsets the reduction in lifespan experience by males paired with non-virgin females. (rest helps mitigate the stress).\n\nOther interactions *could* be included but you should have a strong reason for them. \n\nMore complex models can be compared to simpler ones and reported with F-tests as to whether they explain a significant amount of variance:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfull_model <- lm(longevity ~ type + thorax + sleep + type:sleep, data = dros_clean)\n\nreduced_model <- lm(longevity ~ type + thorax + sleep, data = dros_clean)\n\nanova(reduced_model, full_model)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| Res.Df|      RSS| Df| Sum of Sq|         F|    Pr(>F)|\n|------:|--------:|--:|---------:|---------:|---------:|\n|    120| 15124.57| NA|        NA|        NA|        NA|\n|    118| 14994.43|  2|  130.1431| 0.5120865| 0.6005695|\n\n</div>\n:::\n:::\n\n\nOur initial model included an interaction term for type and sleep, but this was removed from the final model as it did not explain a statistically significant amount of variance F~2,118~ = 0.51, p = 0.6. \n\n\n\n</div>\n\n\n\n## Checking the data\n\nYou should have imported, cleaned and tidied your data. Making sure it is in tidy format, all variables have useful names, and there are no mistakes, missing data or typos.\n\nBased on the variables you have decided to test you should start with some simple visualisations, to understand the distribution of your data, and investigate visually the relationships you wish to test.\n\nThis is a full two-by-two plot of the entire dataset, but you should try and follow this up with some specific plots. \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nGGally::ggpairs(dros_clean)\n```\n\n::: {.cell-output-display}\n![](14-complex-models_files/figure-html/unnamed-chunk-4-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n## Activity 1: Think about your data\n\nThink carefully about the plots you should make to investigate the potential differences and relationships you wish to investigate - try and answer the questions first before checking the examples hidden behind dropdowns.\n\n:::{.task}\n::::{.task-header}\n\n::::\n::::{.task-container}\n\n- Make Density distributions of longevity split by the female type with which males have been paired\n\n- Make a scatterplot of size against longevity.\n\n- Make a scatterplot of sleep against longevity.\n\n- With someone in class - discuss which variables you think are most likely to be statistically significant.\n\n::::\n:::\n\n\n\n<div class='webex-solution'><button>Solution</button>\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncolours <- c(\"cyan\", \"darkorange\", \"purple\")\n\ndros_clean |> \n  ggplot(aes(x = longevity, y = type, fill = type))+\n  geom_density_ridges(alpha = 0.5)+\n  scale_fill_manual(values = colours)+\n  theme_minimal()+\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![A density distribution of longevity across the three sexual activity treatments](14-complex-models_files/figure-html/unnamed-chunk-5-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndros_clean |> \n  ggplot(aes(x = thorax, y = longevity, colour = type))+\n  geom_point()+\n  scale_colour_manual(values = colours)+\n  theme_minimal()+\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](14-complex-models_files/figure-html/unnamed-chunk-6-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndros_clean |> \n  ggplot(aes(x=sleep, y = longevity, group = type, colour = type))+\n  geom_point( alpha = 0.6)+\n  scale_colour_manual(values = colours)+\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](14-complex-models_files/figure-html/unnamed-chunk-7-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n</div>\n\n\n## Designing a model\n\nIn this section, we explore how to construct a statistical model to analyze biological data. Specifically, we will build a linear model to examine the effects of mating type, body size, and sleep on longevity in Drosophila melanogaster. We will define our dependent variable (longevity) and include relevant predictor variables (mating type, thorax length, and sleep duration).\n\nUsing the `lm()` function in R, we fit a model to our cleaned dataset, and generate a summary of the results. This approach allows us to assess the significance of each predictor and interpret how these factors influence longevity. By the end of this section, you will understand how to structure a model, choose appropriate variables, and interpret statistical outputs.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# a full model\nflyls1 <- lm(longevity ~ type + thorax + sleep, data = dros_clean)\n\nsummary(flyls1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = longevity ~ type + thorax + sleep, data = dros_clean)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-28.153  -6.836  -2.191   7.196  29.046 \n\nCoefficients:\n                 Estimate Std. Error t value Pr(>|t|)    \n(Intercept)     -56.04502   11.17882  -5.013 1.87e-06 ***\ntypeInseminated   3.62796    2.77122   1.309    0.193    \ntypeVirgin      -13.24603    2.76198  -4.796 4.70e-06 ***\nthorax          144.43008   13.11616  11.012  < 2e-16 ***\nsleep            -0.05281    0.06383  -0.827    0.410    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 11.23 on 120 degrees of freedom\nMultiple R-squared:  0.6046,\tAdjusted R-squared:  0.5914 \nF-statistic: 45.88 on 4 and 120 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n:::{.callout-important}\n\nBefore we try to interpret the coefficients for a model, we must first check that the model is a good fit for our data. We do this by checking the residuals\n\n:::\n\n\n## Model checking & collinearity\n\nBefore we start playing with the terms in our model, we should check to see if this is even a good way of fitting and measuring our data. We should check the assumptions of our model are being met.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nperformance::check_model(flyls1,\n                         detrend = F)\n```\n\n::: {.cell-output-display}\n![](14-complex-models_files/figure-html/unnamed-chunk-9-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n- Posterior Predictive Check – Assesses whether the model’s predicted values align well with the observed data, indicating good model fit.\n\n- Linearity Check – Ensures that the relationship between predictor variables and the outcome is approximately linear, a key assumption of linear regression.\n\n- Homogeneity of Variance Check – Tests whether residuals (errors) have constant variance across all levels of predictors, known as homoscedasticity.\n\n- Influential Observation Check – Identifies individual data points that have a disproportionately large impact on the model’s estimates.\n\n- Collinearity Check – Detects whether predictor variables are highly correlated with each other, which can distort model estimates and reduce interpretability.\n\n- Normality Check – Examines whether the residuals of the model follow a normal distribution, an assumption necessary for reliable inference in linear regression.\n\n### Homogeneity of variance\n\n**Question - IS the assumption of homogeneity of variance met?** <select class='webex-select'><option value='blank'></option><option value='answer'>Yes</option><option value=''>No</option></select>\n\n\n<div class='webex-solution'><button>Solution</button>\n\n\n* Mostly - the reference line is fairly flat (there is a slight curve).\n\n* It looks as though there might be some increasing heterogeneity with larger values, though very minor.\n\nVERDICT, pretty much ok, should be fine for making inferences. \n\nWith a slight curvature this could indicate that you *might* get a better fit with a transformation, or perhaps that there is a missing variable that if included in the model would improve the residuals. In this instance I wouldn't be overly concerned. See here for a great explainer on intepreting residuals^[https://www.qualtrics.com/support/stats-iq/analyses/regression-guides/interpreting-residual-plots-improve-regression/].\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Runs a Breusch-Pagan Test for heteroscedasticity\n# Sensitive to outliers, non-normality and sample size\nperformance::check_heteroscedasticity(flyls1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOK: Error variance appears to be homoscedastic (p = 0.155).\n```\n\n\n:::\n:::\n\n\n\n</div>\n\n\n### Normality of residuals\n\n<select class='webex-select'><option value='blank'></option><option value='answer'>Yes</option><option value=''>No</option></select>\n\n\n<div class='webex-solution'><button>Solution</button>\n\nYes - the QQplot looks pretty good, a very minor indication of a right skew, but nothing to worry about. \n\n[Interpreting QQ plots][What is a Quantile-Quantile (QQ) plot?]\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Runs a Shapiro Wilk test of normality\n# Sensitive to outliers, sample size\nperformance::check_normality(flyls1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOK: residuals appear as normally distributed (p = 0.065).\n```\n\n\n:::\n:::\n\n\n\n</div>\n\n\n\n\n### Collinearity\n\n**Question - IS their an issue with Collinearity?** <select class='webex-select'><option value='blank'></option><option value=''>Yes</option><option value='answer'>No</option></select>\n\n:::{.callout-tip}\n\nWhat can you do about collinearity in main effects? 1) Nothing 2) Transform 3) Drop one of the terms. \n\nThe `check_performance()` function produces a visual summary of a Variance Inflation Factor produced from the `vif()` function. This is a measure of the standard error of each estimated coefficient. If this is very larger (greater than 5 or 10), this indicates the model has problems estimating the coefficient. This does not affect model predictions, but makes it more difficult to determine the estimate change from a predictor. \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncar::vif(flyls1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           GVIF Df GVIF^(1/(2*Df))\ntype   1.016134  2        1.004009\nthorax 1.015354  1        1.007648\nsleep  1.010512  1        1.005242\n```\n\n\n:::\n:::\n\n\n:::\n\n\n### Model Interpretation\n\nThe `drop1()` function helps assess whether a predictor (e.g. type) significantly improves the model. If removing a variable results in a large decrease in model fit (i.e., a significant drop in the F-statistic), it suggests that the variable is an important contributor to explaining the outcome.\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# use drop1 function to remove top-level terms\ndrop1(flyls1, test = \"F\")\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|       | Df|   Sum of Sq|      RSS|      AIC|    F value|    Pr(>F)|\n|:------|--:|-----------:|--------:|--------:|----------:|---------:|\n|<none> | NA|          NA| 15124.57| 609.4702|         NA|        NA|\n|type   |  2|  7576.86233| 22701.43| 656.2337|  30.057833| 0.0000000|\n|thorax |  1| 15282.82102| 30407.39| 694.7659| 121.255596| 0.0000000|\n|sleep  |  1|    86.27949| 15210.85| 608.1813|   0.684551| 0.4096663|\n\n</div>\n:::\n:::\n\n\nBased on this ANOVA table, we can conclude that type and thorax are both significant predictors of longevity, while sleep is not. We can go on now to look at directionality and effect size for each level of our predictors. \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(flyls1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = longevity ~ type + thorax + sleep, data = dros_clean)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-28.153  -6.836  -2.191   7.196  29.046 \n\nCoefficients:\n                 Estimate Std. Error t value Pr(>|t|)    \n(Intercept)     -56.04502   11.17882  -5.013 1.87e-06 ***\ntypeInseminated   3.62796    2.77122   1.309    0.193    \ntypeVirgin      -13.24603    2.76198  -4.796 4.70e-06 ***\nthorax          144.43008   13.11616  11.012  < 2e-16 ***\nsleep            -0.05281    0.06383  -0.827    0.410    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 11.23 on 120 degrees of freedom\nMultiple R-squared:  0.6046,\tAdjusted R-squared:  0.5914 \nF-statistic: 45.88 on 4 and 120 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n#### Coefficients and Their Meaning\nEach row represents a predictor variable in the model:\n\n- Intercept (-56.05, t(120) = -5.013, p < 0.001): The expected longevity when all predictor variables are zero (not always biologically meaningful but serves as a reference point).\n\n- typeInseminated (3.63, t(120) = 1.31, p = 0.193): Males paired with inseminated females lived on average 3.63 days longer than the reference group (control), but this effect is not statistically significant (p > 0.05).\n\n- typeVirgin (-13.25, t(120) = -4.8,  p < 0.001): Males paired with virgin females lived significantly shorter lives, about 13.25 days less than the control group (p < 0.001, highly significant).\n\n- thorax (144.43, t(120) = 11.01,  p < 0.001): Body size (thorax length) has a strong positive effect on longevity—each 1 mm increase in thorax length is associated with an increase of ~144 days in lifespan (p < 0.001).\n\n- sleep (-0.05, t(120) = -0.83, p = 0.41): Sleep has a very small negative effect on longevity, but this effect is not statistically significant (p > 0.05).\n\n### Model Fit Metrics\n\n- Residual standard error (11.23): Measures how much the observed longevity values deviate from the model’s predictions on average.\n\n- R-squared (0.6046): About 60% of the variability in longevity is explained by this model, which suggests a reasonably strong fit.\n\n- F-statistic (45.88, p < 2.2e-16): Indicates that the model overall is statistically significant, meaning at least one predictor contributes significantly to explaining longevity.\n\n### Key Takeaways\n\n- Body size (thorax) has the strongest and most significant effect on longevity.\n\n- Being paired with virgin females significantly reduces male longevity.\n\n- Sleep and pairing with inseminated females do not have significant effects.\n\n- The model explains a substantial portion (60%) of the variation in longevity.\n\n## Reporting Uncertainty\n\nReporting mean differences along with 95% confidence intervals (CIs) provides several important benefits in reporting:\n\n- Precision and Uncertainty:\n\nA 95% confidence interval tells you the range within which the true population mean difference likely falls, with 95% confidence. It provides more context than just reporting a single point estimate (the mean difference). This gives the reader a sense of how reliable your estimate is.\n\n- Statistical Significance:\n\nIf the 95% CI for a mean difference does not include zero, it suggests that the difference is statistically significant at the 5% level. This is a quick way to interpret the results without solely relying on P-values.\n\n- Practical Significance:\n\nThe confidence interval gives a sense of the magnitude of the effect and whether it’s large enough to be of practical significance. Even a statistically significant result might not have real-world relevance if the confidence interval is very narrow and the effect size is small.\n\n- Informed Decision-Making:\n\nReporting both the point estimate and the confidence interval helps stakeholders, including researchers, practitioners, and policymakers, make better-informed decisions. It reflects both the strength of evidence and its precision.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# confint(flyls1)\n\nbroom::tidy(flyls1,conf.int = T)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|term            |    estimate|  std.error| statistic|   p.value|    conf.low|   conf.high|\n|:---------------|-----------:|----------:|---------:|---------:|-----------:|-----------:|\n|(Intercept)     | -56.0450154| 11.1788237| -5.013498| 0.0000019| -78.1783084| -33.9117223|\n|typeInseminated |   3.6279641|  2.7712182|  1.309159| 0.1929819|  -1.8588550|   9.1147833|\n|typeVirgin      | -13.2460301|  2.7619784| -4.795849| 0.0000047| -18.7145551|  -7.7775051|\n|thorax          | 144.4300750| 13.1161611| 11.011612| 0.0000000| 118.4609889| 170.3991611|\n|sleep           |  -0.0528074|  0.0638251| -0.827376| 0.4096663|  -0.1791767|   0.0735619|\n\n</div>\n:::\n:::\n\n\n\n## Posthoc\n\nUsing the [emmeans](https://aosmith.rbind.io/2019/03/25/getting-started-with-emmeans/) package is a very easy way to produce the estimate mean values (rather than mean differences) for different categories `emmeans`. \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nemmeans::emmeans(flyls1, \n                 specs = ~ type + thorax + sleep)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n type        thorax sleep emmean   SE  df lower.CL upper.CL\n Control      0.821  23.5   61.3 2.26 120     56.8     65.8\n Inseminated  0.821  23.5   64.9 1.59 120     61.8     68.1\n Virgin       0.821  23.5   48.0 1.59 120     44.9     51.2\n\nConfidence level used: 0.95 \n```\n\n\n:::\n:::\n\n\n\nIf the term `pairwise` is included then it will also include post-hoc pairwise comparisons between all levels with a tukey test (adjustment for multiple comparisons) `contrasts`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# add pairwise ~\nemmeans::emmeans(flyls1, \n                 specs = pairwise ~ type + thorax + sleep)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$emmeans\n type        thorax sleep emmean   SE  df lower.CL upper.CL\n Control      0.821  23.5   61.3 2.26 120     56.8     65.8\n Inseminated  0.821  23.5   64.9 1.59 120     61.8     68.1\n Virgin       0.821  23.5   48.0 1.59 120     44.9     51.2\n\nConfidence level used: 0.95 \n\n$contrasts\n contrast                                                                 \n Control thorax0.82096 sleep23.464 - Inseminated thorax0.82096 sleep23.464\n Control thorax0.82096 sleep23.464 - Virgin thorax0.82096 sleep23.464     \n Inseminated thorax0.82096 sleep23.464 - Virgin thorax0.82096 sleep23.464 \n estimate   SE  df t.ratio p.value\n    -3.63 2.77 120  -1.309  0.3929\n    13.25 2.76 120   4.796  <.0001\n    16.87 2.25 120   7.508  <.0001\n\nP value adjustment: tukey method for comparing a family of 3 estimates \n```\n\n\n:::\n:::\n\n\n:::{.callout-tip}\n\nFor continuous variables (sleep and thorax) - `emmeans` has set these to the mean value within the dataset, so comparisons are constant between categories at the average value of all continuous variables. If we wish to model continuous predictions we need to specify these:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nemmeans::emmeans(flyls1, \n                 specs = ~ type + thorax + sleep,\n                 at = list(thorax = seq(0.64,0.94, .1)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n type        thorax sleep emmean   SE  df lower.CL upper.CL\n Control       0.64  23.5   35.2 3.42 120     28.4     41.9\n Inseminated   0.64  23.5   38.8 2.79 120     33.2     44.3\n Virgin        0.64  23.5   21.9 2.83 120     16.3     27.5\n Control       0.74  23.5   49.6 2.58 120     44.5     54.7\n Inseminated   0.74  23.5   53.2 1.87 120     49.5     56.9\n Virgin        0.74  23.5   36.3 1.90 120     32.6     40.1\n Control       0.84  23.5   64.0 2.25 120     59.6     68.5\n Inseminated   0.84  23.5   67.7 1.62 120     64.5     70.9\n Virgin        0.84  23.5   50.8 1.61 120     47.6     54.0\n Control       0.94  23.5   78.5 2.63 120     73.3     83.7\n Inseminated   0.94  23.5   82.1 2.28 120     77.6     86.6\n Virgin        0.94  23.5   65.2 2.25 120     60.8     69.7\n\nConfidence level used: 0.95 \n```\n\n\n:::\n:::\n\n\n:::\n\n## Tables\n\n`sjPlot` A really nice package that helps produce model summaries for you automatically\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(sjPlot)\ntab_model(flyls1)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table style=\"border-collapse:collapse; border:none;\">\n<tr>\n<th style=\"border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; \">&nbsp;</th>\n<th colspan=\"3\" style=\"border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; \">longevity</th>\n</tr>\n<tr>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; \">Predictors</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">Estimates</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">CI</td>\n<td style=\" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  \">p</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">(Intercept)</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">&#45;56.05</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">&#45;78.18&nbsp;&ndash;&nbsp;-33.91</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>&lt;0.001</strong></td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">type [Inseminated]</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">3.63</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">&#45;1.86&nbsp;&ndash;&nbsp;9.11</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.193</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">type [Virgin]</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">&#45;13.25</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">&#45;18.71&nbsp;&ndash;&nbsp;-7.78</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>&lt;0.001</strong></td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">thorax</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">144.43</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">118.46&nbsp;&ndash;&nbsp;170.40</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \"><strong>&lt;0.001</strong></td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; \">sleep</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">&#45;0.05</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">&#45;0.18&nbsp;&ndash;&nbsp;0.07</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  \">0.410</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;\">Observations</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;\" colspan=\"3\">125</td>\n</tr>\n<tr>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;\">R<sup>2</sup> / R<sup>2</sup> adjusted</td>\n<td style=\" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;\" colspan=\"3\">0.605 / 0.591</td>\n</tr>\n\n</table>\n\n`````\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(gtsummary)\ntbl_regression(flyls1)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"vjvxwkwnkr\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#vjvxwkwnkr table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#vjvxwkwnkr thead, #vjvxwkwnkr tbody, #vjvxwkwnkr tfoot, #vjvxwkwnkr tr, #vjvxwkwnkr td, #vjvxwkwnkr th {\n  border-style: none;\n}\n\n#vjvxwkwnkr p {\n  margin: 0;\n  padding: 0;\n}\n\n#vjvxwkwnkr .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#vjvxwkwnkr .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#vjvxwkwnkr .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#vjvxwkwnkr .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#vjvxwkwnkr .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#vjvxwkwnkr .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vjvxwkwnkr .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#vjvxwkwnkr .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#vjvxwkwnkr .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#vjvxwkwnkr .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#vjvxwkwnkr .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#vjvxwkwnkr .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#vjvxwkwnkr .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#vjvxwkwnkr .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#vjvxwkwnkr .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#vjvxwkwnkr .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#vjvxwkwnkr .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#vjvxwkwnkr .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#vjvxwkwnkr .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vjvxwkwnkr .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#vjvxwkwnkr .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#vjvxwkwnkr .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#vjvxwkwnkr .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vjvxwkwnkr .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#vjvxwkwnkr .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#vjvxwkwnkr .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vjvxwkwnkr .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vjvxwkwnkr .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#vjvxwkwnkr .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vjvxwkwnkr .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#vjvxwkwnkr .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#vjvxwkwnkr .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#vjvxwkwnkr .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vjvxwkwnkr .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#vjvxwkwnkr .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#vjvxwkwnkr .gt_left {\n  text-align: left;\n}\n\n#vjvxwkwnkr .gt_center {\n  text-align: center;\n}\n\n#vjvxwkwnkr .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#vjvxwkwnkr .gt_font_normal {\n  font-weight: normal;\n}\n\n#vjvxwkwnkr .gt_font_bold {\n  font-weight: bold;\n}\n\n#vjvxwkwnkr .gt_font_italic {\n  font-style: italic;\n}\n\n#vjvxwkwnkr .gt_super {\n  font-size: 65%;\n}\n\n#vjvxwkwnkr .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#vjvxwkwnkr .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#vjvxwkwnkr .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#vjvxwkwnkr .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#vjvxwkwnkr .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#vjvxwkwnkr .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#vjvxwkwnkr .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Characteristic&lt;/strong&gt;\"><strong>Characteristic</strong></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Beta&lt;/strong&gt;\"><strong>Beta</strong></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;95% CI&lt;/strong&gt;&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>95% CI</strong><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;p-value&lt;/strong&gt;\"><strong>p-value</strong></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">type</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\"></td>\n<td headers=\"ci\" class=\"gt_row gt_center\"></td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Control</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">—</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">—</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Inseminated</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">3.6</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">-1.9, 9.1</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.2</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Virgin</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-13</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">-19, -7.8</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">thorax</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">144</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">118, 170</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">sleep</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-0.05</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">-0.18, 0.07</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.4</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"4\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span> CI = Confidence Interval</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n## Figures\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmarginal1 <- dros_clean |> \n  ggplot()+\n  geom_density(aes(x = thorax, fill = type),\n               alpha = 0.5)+\n  scale_fill_manual(values = colours)+\n  theme_void()+\n  theme(legend.position = \"none\")\n\n# density plot of longevity by treatment\nmarginal2 <- dros_clean |> \n  ggplot()+\n  geom_density(aes(x = longevity, fill = type),\n               alpha = 0.5)+\n  scale_fill_manual(values = colours)+\n  theme_void()+\n  coord_flip()\n\n\n# create a new dataset where all sleep values are set to a constant (mean) values - see the emmeans table\n\nmeans <- emmeans::emmeans(flyls1, \n                 specs = ~ type + thorax + sleep,\n                 at = list(thorax = seq(0.64,0.94, .1))) |> \n  as_tibble()\n\n# use the final model to produce model predictions set to the new constant sleep dataframe\nmodel_plot <- ggplot(means, aes(x=thorax, y = emmean, colour = type, fill = type))+\n  geom_ribbon(aes(ymin=lower.CL, ymax=upper.CL), alpha = 0.2)+\n    geom_line(linetype = \"dashed\", show.legend = FALSE)+\n  geom_point(data = dros_clean, aes(x = thorax, y = longevity),\n             show.legend = FALSE)+\n  scale_colour_manual(values = colours)+\n  scale_fill_manual(values = colours)+\n  labs(y = \"Lifespan in days\",\n       x = \"Thorax length (mm)\",\n       fill = \"Type of female exposure\")+\n  guides(colour = \"none\")+\n  theme_classic()+\n  theme(legend.position = \"none\")\n\nlayout <- \"\nAAA#\nBBBC\nBBBC\nBBBC\"\n\n\ndros_plot <- marginal1+model_plot+marginal2 +plot_layout(design = layout)\n\ndros_plot\n```\n\n::: {.cell-output-display}\n![](14-complex-models_files/figure-html/unnamed-chunk-21-1.png){fig-align='center' width=100%}\n:::\n:::\n\n",
    "supporting": [
      "14-complex-models_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}